### ISSUE TITLE
Dungeon Crawl Interaction SMP bug

### ISSUE THREAD

**Issue by Slither88** [noobanidus/Lootr#1]
Using forge 28.2.3 and lootr-1.14.4-0.0.1.1

In SSP the loot barrels in dungeon crawl dungeons have loot inside them as well as the chests. But in SMP none of the barrels have loot, only the chest. I had three players access 6 different chests and all were empty evey single time.

**Comment by noobanidus** [comment]
Oh, that's interesting! I'll definitely look into this. Can you send me or attach a copy of your latest.log from your server? It sounds like something might be interfering.

**Comment by Slither88** [comment]
Sure. There you go
[debug.log](https://github.com/noobanidus/Lootr/files/4470151/debug.log)
[latest.log](https://github.com/noobanidus/Lootr/files/4470152/latest.log)

**Comment by noobanidus** [comment]
This is interesting. The ASM seems to be loading and executing but it doesn't seem to be printing out the usual statements that it does.

Does it work for just plain normal chests, or is it purely barrels that it has an issue with?

**Comment by Slither88** [comment]
The normal chests are fine as far as I can tell. Only the barrels generate
empty for all players.

**Comment by noobanidus** [comment]
Final quick question: do you have a list of all other mods in the pack? I'm wondering if there might also be a conflict.

**Comment by Slither88** [comment]
Sure,

AdHooks-1.14.4-4.0.0.2-build.0072.jar
Aquaculture-1.14.4-2.0.7.jar
atmospheric-1.14.4-1.1.2.jar
AutoRegLib-1.4-35.jar
autumnity-1.0.0-1.14.4.jar
AzureRPGItems+1.14.4-1.0.6.jar
backpacked-1.4.0-1.14.4.jar
bambooblocks-1.2.12.jar
BetterAdvancements-1.14.4-0.1.0.90.jar
BetterCaves-1.14.4-1.1.1.jar
bloomful-1.2.4.jar
Bountiful Baubles-1.14.4-0.0.3.jar
branders-wellfedmod-1.14.4-1.3.0.jar
caelus-FORGE-1.14.4-1.0.1.2.jar
carrotslib-mc1.14.4-2.0.1.jar
CarryOn MC1.14.4 v1.12.4.jar
ceilingtorch-1.14.4-v1.5.jar
Charm-1.14.4-1.5.5.jar
citadel-1.0.0.jar
Clumps-4.0.1.jar
colytra-FORGE-1.14.4-2.0.0.1.jar
Controlling-5.0.6.jar
CookingForBlockheads_1.14.4-7.4.4.jar
corail_woodcutter-1.1.1-1.14.4.jar
CosmeticArmorReworked-1.14.4-v1b.jar
craftingstation-2.1.6.jar
CraftingTweaks_1.14.4-10.2.1.jar
create-mc1.14.4_v0.2.2a.jar
curios-FORGE-1.14.4-1.0.6.1.jar
curiouselytra-FORGE-1.14.4-1.0.jar
dankstorage-1.15.jar
dash-1.14.4-1.0.0.jar
deathbackup-1.14.4-1.0.0.jar
DoggyTalents-1.14.4-1.15.2.3.jar
Druidcraft-1.14-0.3.1.jar
DungeonCrawl-1.14.4-1.6.3.jar
enchantable-1.1.0-1.14.4.jar
EnchantmentDescriptions-1.14.4-1.3.14.jar
enderchests-1.14-1.5.1.jar
EnderMail-1.14.4-1.0.0.jar
EnigmaticLegacy-1.6.4.jar
EquipmentTooltips-1.14.4-1.3.2+10.jar
extcaves-1.5.jar
extraboats-1.2.6-1.14.4.jar
farlanders-1.14.4-1.1.2.jar
FarmingForBlockheads_1.14.4-5.3.2.jar
FastLeafDecay-v17.jar
forbidden_arcanus-1.14.4-1.5.jar
ForgeEndertech-1.14.4-5.2.2.0-build.0082.jar
furniture-7.0.0-pre15-1.14.4.jar
inventorysorter-1.14.4-16.2.0.jar
ironchest-1.14.4-9.1.5.jar
ironshulkerboxes-1.14.4-3.1.12.jar
janoeo-2.3.jar
jei-1.14.4-6.0.0.27.jar
journeymap-1.14.4-5.7.0b1.jar
JustEnoughResources-1.14.4-0.10.1.76.jar
lava-monster-1.14.4-1.0.2.jar
leap-1.14.4-1.0.0.jar
LLOverlayReloaded-1.2.4-mc1.14.4.jar
lootr-1.14.4-0.0.1.1.jar
mcw-bridges-1.0.4-mc1.14.4.jar
mcw-roofs-1.0.2-mc1.14.4.jar
mcw-windows-1.0.0-mc1.14.4.jar
mightyarchitect-mc1.14.4_v0.5.jar
Mine and Slash - Expansion-1.4.2.30.jar
Mine and Slash-1.14.4-2.9.4.jar
minecolonies-0.10.715-RELEASE-universal.jar
MouseTweaks-2.13-mc1.14.4.jar
MS Auto-Compat-1.14.4-1.6.0.jar
multibeds-1.14-1.5.2.jar
mysticallib-1.14.4-1.16.1.jar
mysticalmachinery-1.14.4-0.0.0.6.jar
mysticalworld-1.14.4-1.9.0.jar
NaturesCompass-1.14.4-1.8.5.jar
nethercraft-1.14.4-1.0.6.jar
NetherPortalFix_1.14.4-7.0.0.jar
noRecipeBook_v1.4.1formc1.14.4.jar
OfflineSkins-1.14.4-v1.jar
Paraglider-1.14.4-1.1.0.2.jar
Patchouli-1.14.4-1.1-26.jar
platforms-1.14-1.5.1.jar
prefab-1.4.0.12.jar
PreGenForge-0.0.5-mc1.14.4.jar
Quark-r2.0-212.jar
RandomThings-MC1.14.4-5.0.1.jar
Reliquary-1.14.4-1.3.4.947.jar
respawnable-pets-1.0.6.1.jar
SaveMyStronghold-1.14.4-1.0.0.jar
seals-1.14.4-1.0.2.jar
shetiphiancore-1.14-3.6.1.jar
SilentGear-1.14.4-1.4.6+72.jar
SilentGems-1.14.4-3.4.8+81.jar
SilentLib-1.14.4-4.4.0+44.jar
SimpleDivingGear-3.0.4+mc+1.14.4.jar
SpartanShields-1.14.4-2.0.0.jar
StorageDrawers-1.14.4-6.0.7.jar
Strange-1.14.4-1.0.0-beta.2.jar
structurize-0.10.245-ALPHA.jar
swampexpansion-1.4.9.jar
swingthroughgrass-1.14.4-1.3.2.jar
tekdungeons-1.0.jar
The-Endergetic-Expansion-1.14.4-v1.2.0.jar
theoneprobe-1.14-1.4.37.jar
ToolBelt-1.14.4-1.12.5.jar
torchmaster-2.0.0-rc2.jar
TrashSlot_1.14.4-10.4.8.jar
Upgrade-Aquatic-1.14.4-v1.4.10.jar
VampiresNeedUmbrellas-1.14.4-1.3.jar
Vampirism-1.14.4-1.6.0-beta.6.jar
VTweaks-1.14.4-3.1.6.jar
Waystones_1.14.4-5.1.1.jar
Wyrmroost-1.14.4-1.0.2.jar
xercamod-1.14.4-1.4.jar

**Comment by noobanidus** [comment]
Thanks! I'm hopeful I'll have time to look into it further tomorrow. I was wondering if perhaps there was a conflict with Riddle Chests, but you don't seem to have that installed. It may be just a simple failure when it comes to the NBT-setting from the read function...
