### ISSUE TITLE
Watchdog Crashes when opening Lootr chests that contain treasure maps (with Terralith et al)

### ISSUE THREAD

**Issue by Benjamboo** [noobanidus/Lootr#100]
https://pastebin.com/fUfBBUbk

**Comment by noobanidus** [comment]
It appears to be crashing when generating a treasure map. 

What version of Minecraft and Lootr is this?

**Comment by Bytestorm5** [comment]
I'm having a similar issue on my server with the same version of Lootr and Minecraft (0.2.16.52 & 1.18.2)
I'll post logs if it happens again, but I went through the log OP posted and I found these common mods between my server and OP's: [https://pastebin.com/ZdJMfKTh](https://pastebin.com/ZdJMfKTh)

I'm not sure what version of Forge OP is using, but I'm using Forge version 40.1.19 on my server.

**Comment by Benjamboo** [comment]
Apologies for the delay, I should have included the versions, here

MC 1.18.2
lootr-1.18.2-0.2.16.52
forge - 40.1.20
Server/Jelly mods
Radium Reforged (Lithium on Fabric) - 0.7.10.jar, could be causing issues?

**Comment by noobanidus** [comment]
This is an odd server deadlock that's happening when someone opens a chest.

Given that you're both using terralith and apparently having issues with exploration maps, could you test the following to ensure that it's not something Lootr is doing?

- Note the location of the chest
- Copy the world seed
- Disable lootr
- Create a new world using the exact same pack & settings with the current seed
- Open the chest without Lootr

If the crash doesn't occur, then it's definitely an issue with Lootr.

Unfortunately, without the world seed/identical set-up, there's no way for me to test it.

**Comment by noobanidus** [comment]
Conferring with https://github.com/FTBTeam/FTB-Modpack-Issues/issues/809 seems to indicate that this is an issue with world generation of some description, rather than an issue with Lootr, unfortunately.

**Comment by noobanidus** [comment]
@Benjamboo @AstronomyGuy This appears to be an issue with the dummy structures from Terralith, which are used for their exploration maps, not being found.

Please see [this comment](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/809#issuecomment-1136167755) on the Direwolf20 issue tracker for instructions on how to disable the map. There may be other mods involved (potentially Repurposed Structure's extension of the `locate` command, as well as Terrablender's biome changes) to actually cause the issue, but it doesn't appear to be specific to Lootr.
