### ISSUE TITLE
Integration with teams or team mods like FTB teams

### ISSUE THREAD

**Issue by EnderMelody** [noobanidus/Lootr#101]
it would be nice if there was a team system that made people on the same team only get loot from a chest once. This would allow groups of players who play together to get the correct amount of loot while still utilizing the mod for other players.

**Comment by noobanidus** [comment]
This would likely require a significant overhaul of how Lootr fetches and stores player-specific containers to use whatever team identifier from FTB teams.

I'll look into it, but at the minute it's not a large priority for me.

A possible alternative in the current versions released for Lootr would be to reduce the amount of loot found in chests by default.

**Comment by noobanidus** [comment]
I'm closing this issue as I don't have the time available to dedicate to this.
