### ISSUE TITLE
Exit Code -1 on AOF5 Server

### ISSUE THREAD

**Issue by MrVFox** [noobanidus/Lootr#105]
Playing Aof5 made a base above a lootr chest and now I can't walk near certain chunks or my game crashes Exit Code:-1
Only seems to be an issue for me and select few other players on na server, but not everyone. 

[crash-2022-05-24_06.38.30-client.txt](https://github.com/noobanidus/Lootr/files/8762452/crash-2022-05-24_06.38.30-client.txt)

**Comment by noobanidus** [comment]
Please update to the latest version of Lootr for Fabric.

**Comment by MrVFox** [comment]
Thank you kindly. 
I updated lootr and changed my video setting options to "animate only visual texture" and I didn't crash.

**Comment by noobanidus** [comment]
The error here was that the `blockEntityRendererDispatcher` value was only being set when the item of a chest was viewed (i.e., through an advancement). If you came across a chest, it tried to use *that value* without setting it, causing the null error.

I've fixed this to bypass this value and get the dispatcher from the Minecraft instance every time.

In this case, the "animate only visual textures" will make no difference as Lootr doesn't use animated textures.
