### ISSUE TITLE
Crash on SP startup

### ISSUE THREAD

**Issue by kottontop9898** [noobanidus/Lootr#109]
Added Lootr (Fabric) to modpack, along with Cloth Config.

Crash report attached
[crash-2022-06-11_19.46.31-server.txt](https://github.com/noobanidus/Lootr/files/8885920/crash-2022-06-11_19.46.31-server.txt)

**Comment by kottontop9898** [comment]
As further detail, the world appears to load fully to 100%, but I never actually *see* anything before the crash.

**Comment by ZestyBlaze** [comment]
I'll give it a check, what version of MC is this?

**Comment by kottontop9898** [comment]
1.18.1

**Comment by noobanidus** [comment]
The current 1.18 release only supports 1.18.2.

**Comment by ZestyBlaze** [comment]
Nooby is correct, we do not support 1.18.1. Basically Minecraft changed how Tag's worked between 1.18.1 and 1.18.2 iirc and that means the 1.18.2 files doesn't work on 1.18.1. If it's highly requested enough, I'll backport the tag workings back to 1.18.1 but it's not been brought up until now
If in doubt as to what versions of Minecraft Lootr works on, check the versions on the CF file page and it will tell you the versions that the mod works with

**Comment by kottontop9898** [comment]
Ah okay, that makes sense. Thanks for clearing it up for me, guys, really appreciate y'all.
