### ISSUE TITLE
[all] Convert blocks back to using loot tables instead of manual drops

### ISSUE THREAD

**Issue by Laifsyn** [noobanidus/Lootr#110]
I've added the Mining Level 5 tag for Lootr blocks, but I'm still able to get a drop

**Comment by noobanidus** [comment]
What exactly are you trying to achieve? There should be a configuration option that prevents chests from being destroyed or broken unless done in creative mode.

**Comment by Laifsyn** [comment]
Make it harder to break

**Comment by Laifsyn** [comment]
Make it harder to break, and to also dissuade them from breaking. I used CT to edit the block hardness, I would only be missing the harvestability tag compat, which Would force people to need to use a Harvest Level 5 tool to break the block in a "decent" time

**Comment by noobanidus** [comment]
This probably has to do with the fact that the chests aren't using loot tables but manual drops ... due to 1.14 code that's no longer relevant. That's a todo.

**Comment by noobanidus** [comment]
If this is still an issue for you, please open a new issue. This wasn't a huge priority for me especially given the custom code already in place to prevent people from breaking containers.
