### ISSUE TITLE
Buried Treasure Maps on a Converted World pointed to an empty chest

### ISSUE THREAD

**Issue by wertercatt** [noobanidus/Lootr#111]
Hi!

I added Lootr to my server recently, and was able to verify that it converted properly by exploring some Drowned Ruins. I got two Buried Treasure Maps, which both pointed to the same location. When I arrived, it was an empty unconverted chest, presumably previously found. Is this a known issue that Buried Treasure Maps don’t work properly?

**Comment by embeddedt** [comment]
I'm not sure that Lootr is able to convert previously opened chests as I don't think they retain the loot table information. However, newly generated chests should work properly.

**Comment by wertercatt** [comment]
Yeah, I was just confused by the fact that the buried treasure maps I found pointed towards an opened chest instead of a new buried_treasure structure. I’ve broken the offending block, so hopefully the next map I try to follow will lead to a Lootr Chest

**Comment by noobanidus** [comment]
Yeah, that's just something Vanilla does.
