### ISSUE TITLE
Lootr Server-Side Crash Java 1.12.2

### ISSUE THREAD

**Issue by EmyLightsaber** [noobanidus/Lootr#112]
lootr-1.12.2-0.1.1
Upon adding Lootr to my Vorps Reborn pack server, it crashes as soon as it gets to Lootr in the loading sequence.

https://www.curseforge.com/minecraft/modpacks/vorps-reborn/files/3832945

[crash-2022-06-19_03.58.27-server.txt](https://github.com/noobanidus/Lootr/files/8934741/crash-2022-06-19_03.58.27-server.txt)
[latest.log](https://github.com/noobanidus/Lootr/files/8934742/latest.log)

**Comment by embeddedt** [comment]
Thanks for the report! This should be fixed in 0.1.2.
