### ISSUE TITLE
Dimes A Dozen advancement typo

### ISSUE THREAD

**Issue by BakeJake** [noobanidus/Lootr#114]
![image](https://user-images.githubusercontent.com/52101762/176111533-5beaf2a9-c06f-4e56-9f3b-0a39e848f7c2.png)
As in the image above, I believe this is a typo? Disme? Dimes? ;)
*lootr-1.18.2-0.2.17.54*

**Comment by noobanidus** [comment]
Actually intentional, as it refers to a specific type of French coin. [Please see the translation guide.](https://github.com/noobanidus/Lootr/wiki/Translation)
