### ISSUE TITLE
Trapped chests not generating

### ISSUE THREAD

**Issue by Azzarg** [noobanidus/Lootr#115]
I am using version 0.2.17.4 for 1.18.2, and I am trying to implement a custom structure using a datapack. The structure uses trapped chests. When generated naturally, lootr replaces the trapped chests with normal ones, disarming the trap. I have tried using the setblock command, lootr commands, block picking, nothing will create a lootr trapped chest.

**Comment by noobanidus** [comment]
I believe this has been resolved in a past patch. If you still have problems, please open a new issue.
