### ISSUE TITLE
Passage of the chests in blue when opening in the special dimensions

### ISSUE THREAD

**Issue by maxoupidou** [noobanidus/Lootr#118]
lootr-1.12.2-0.2.1 - forge 14.23.5.2859 - Server
The color of "custom" chests does not change to blue when opened in custom dimensions like those added by JED

**Comment by embeddedt** [comment]
I can't reproduce this. I ran /tpj <id> to get into a JED dimension, then placed items in a vanilla chest, stood on top of it, and ran /lootr custom. Upon opening and closing the chest (it needs to close to change color) it changed to blue as expected.

**Comment by maxoupidou** [comment]
Ah weird I'm going to redo the tests it may be the config of my serv which is a bit particular which causes the problem

**Comment by maxoupidou** [comment]
I will test it and let you know

**Comment by maxoupidou** [comment]
ok, the problem seems to be gone... i reset my server and everything works... i should have filmed thin... for information, i am using Mohist on my server, so it is possible that it is bugs but not directly because of "lootr"
Thanks for your help and sorry for the inconvenience
