### ISSUE TITLE
Exception in Server Tick Loop with Iron Chest

### ISSUE THREAD

**Issue by reddvilzz** [noobanidus/Lootr#120]
Crash on 1.12.2, when walking around the world, the game just froze while the last log in multiMC was server has stopped

Here is the
[crashlog](https://github.com/noobanidus/Lootr/files/9041141/crash-2022-07-04_23.49.42-server.txt) mentioning Iron Chest.

Looks like Lootr trying to convert Iron Chest, maybe I need to add the mod into Blacklist?

**Comment by embeddedt** [comment]
@noobanidus What was the rationale for calling `removeBlockEntity` [here](https://github.com/noobanidus/Lootr/blob/3b32ea35d3ac9e637246c8d76ddc56ce9bb791da/src/main/java/noobanidus/mods/lootr/block/tile/TileTicker.java#L91) in 1.16? It looks like, at least in 1.12, the tile entity is already replaced properly by the vanilla logic.

**Comment by noobanidus** [comment]
@embeddedt I think this was to prevent chests from dropping loot/items; I think I switched to a different method in 1.18, so I'm not sure if it's still required.

**Comment by embeddedt** [comment]
0.3.1 should address this crash. However, please be sure to make a backup, as I do find it a little bit suspicious that it's trying to convert an iron chest to begin with.

**Comment by reddvilzz** [comment]
The iron chest was there because of some recurrent complex structures if that's what makes you curious about it, although I can't seem to reproduce the crash after it happened.

I just started Minecraft again then loaded up the world and there were no more crashes. 

Thank you for the quick fix, will try to update and test it.

**Comment by embeddedt** [comment]
> The iron chest was there because of some recurrent complex structures if that's what makes you curious about it

No problem then. I was worried it was trying to convert your storage. :slightly_smiling_face:

**Comment by reddvilzz** [comment]
Okay thank you
