### ISSUE TITLE
You can't /custom shulker boxes

### ISSUE THREAD

**Issue by Laifsyn** [noobanidus/Lootr#121]

**Comment by noobanidus** [comment]
Custom shulker boxes aren't actually implemented. The "custom" inventory itself is just a chest in reality. If there's demand for a custom shulker box, it can be implemented.

Otherwise, it would be better to use a chest instead, as reading a shulker box is a rather complicated process.

**Comment by Laifsyn** [comment]
Is it possible to directly affect a LootR Chest instead of needing to convert a normal chest? like "Oh, I want to add a couple more apples to this chest because I noticed WhateverReason

**Comment by embeddedt** [comment]
I don't think so, because regular Lootr chests are based on a loot table which is supposed to populate with separate loot for each player, while custom inventories are a fixed inventory which duplicates itself for each player.

**Comment by Laifsyn** [comment]
So doing it from scratch I guess

**Comment by Laifsyn** [comment]
Oh, Yes. I remembered why custom Shulkerboxes now. I had issues with some players when they tried to access a chest inside a claimed land(Flan for 1.18.2). They told me they couldn't open it. So I planned to set a ShulkerBox just right outside of the claim, and at the same time make them indestructible through CT.

If the issues of trying to open a chest inside a claimed land could be solved, then I wouldn't need the LootR Shulker workaround.

Issue about this is because I created the land it might smartly allow me to properly open the chest. I don't have reliable way to replicate it though. Since its Admin Owned Land, if I De-op, I effectively am not able at the least place blocks which confirms the rules are applying. but for my friends, they have issues trying to open the lootR chest. It seems if I open it, and leave the HUD open, they can now have access to the chest. (note that Even without OP I can open without issues the chest. I think I even had tried to deop-> restart server -> Try(successfully) to open the chest. So I coudln't replicate whatever was happening to my friends

**Comment by Laifsyn** [comment]
Possible cause could be the spawn area was too big(But should be discarded since I tried to open the chest while deop-ed)

**Comment by noobanidus** [comment]
You can use CraftTweaker to change the custom chest (`lootr:inventory` or whatever it's named -- it's been through a few changes)'s breakability/resistance, though by default they are indestructible and use that instead.

I don't really plan to implement custom shulker boxes at this time.
