### ISSUE TITLE
Error Replacing Certain Loots mostly Ice and Fire and Electroblob's Wizardry 1.12.2

### ISSUE THREAD

**Issue by reddvilzz** [noobanidus/Lootr#122]
Sorry to bother you with another report, so currently I was testing, every time the world is preloaded with Chunk Pregenerator mod Lootr seems to throw this kind of error on the console, and the mod in related was Ice and Fire dragon's lair.

![image](https://user-images.githubusercontent.com/6846358/177765154-d62f2063-162d-49a6-b9f0-e4929975eb5c.png)

Pretty much every chests that is spawned by Ice and Fire cannot be opened, and this is related to this comment https://github.com/noobanidus/Lootr/issues/119#issuecomment-1173080788

So I went to the coordinates of the error on the console and this is what happened to the chests, the items were scattered around and the chests cannot be opened when right clicked.

![image](https://user-images.githubusercontent.com/6846358/177765084-1f88f8ab-f092-44ff-839e-7c0740b01620.png)

Does that means it is an incompatibility between Lootr and Chunk Pregenerator mod? I'm on 1.12.2

**Comment by embeddedt** [comment]
This is helpful, thanks! I'll take a look and see what can be done.

**Comment by embeddedt** [comment]
There are two issues here:

* Lootr's replacement logic had some issues with Chunk Pregenerator. Items on the ground were one side effect.
* Ice and Fire's cave logic seems to cause any vanilla chests it happened to intersect when generating to drop their items. This seems to be unrelated to Lootr, at least in my testing.

I've prepared a beta JAR that fixes the first issue which you can download here: https://cdn.discordapp.com/attachments/994620334399557635/994620370105667604/lootr-1.12.2-0.3.2-BETA.jar

With this version, all chests will convert and open properly, but there may still be a few extra items scattered as a result of the second issue.

Can you let me know how this works?

**Comment by reddvilzz** [comment]
Hmm, now I'm getting this crash report which usually never happened before until now.

[crash log](https://github.com/noobanidus/Lootr/files/9066011/crash-2022-07-08_00.16.28-server.txt)

Though the world load just fine when I restarted minecraft, and I did a quick test to find some of the chests that can't be opened and it is now able to be opened, I'll do more test tomorrow and report back.

Also one more thing, this happens before but I forgot to mention it, sometimes the log will have lots of this line

> [01:42:13] [Server thread/WARN] [minecraft/LootTable]: Tried to over-fill a container

is it nothing to be worried about?

**Comment by embeddedt** [comment]
I can fix (or at least work around) the crash.

> sometimes the log will have lots of this line [overfilling warning]

Does this happen only with Lootr installed, or without it as well?

**Comment by reddvilzz** [comment]
Okay, it still happens without Lootr, so I guess that's vanilla issue or another mod's issue.

> [crash log](https://github.com/noobanidus/Lootr/files/9066011/crash-2022-07-08_00.16.28-server.txt)

But with the beta file this crash seems to be constantly appearing whenever I tried to pregen the world and never fully finished the pregen because of it.

**Comment by embeddedt** [comment]
@reddvilzz This build should hopefully solve the crash once and for all, I haven't been able to reproduce it since the last beta but I understand why it happens.

https://cdn.discordapp.com/attachments/994620334399557635/995328553178644570/lootr-1.12.2-0.3.2-BETA-2.jar

**Comment by reddvilzz** [comment]
Okay tried the new beta, and I got this crash now while pregenerating chunks, it worked the first time, but the 2nd time it gave me
[this](https://github.com/noobanidus/Lootr/files/9085527/crash-2022-07-11_22.40.52-server.txt)

**Comment by embeddedt** [comment]
There truly are an unlimited number of ways Minecraft mods can cause a crash. :laughing: 

https://cdn.discordapp.com/attachments/994620334399557635/996081793956593754/lootr-1.12.2-0.3.2-BETA-3.jar

**Comment by reddvilzz** [comment]
So far so good I think, ran it twice and both are successful without any errors. Tried finding and opening the chests and it's working fine, also there are no items scattered so far.

Thank you for the quick response and fix! I'm gonna keep testing it and will report back if I find some more issues regarding Lootr.

**Comment by reddvilzz** [comment]
So the dragon's lair on the underground section have their items scattered around and some of the chests were empty, I think that's because the actual loot was scattered around outside the chests, meanwhile the surface one doesn't.

I guess for now just let it be?

**Comment by embeddedt** [comment]
The underground lair implementation will scatter loot of any other structures it happens to intersect, at least from my testing in development. I'm not sure that this is a Lootr bug, since all I'm doing is replacing any chest that still happens to be in the world with items at that point. For now I think we'll just have to leave it. I'll get this released as 0.3.2 on CurseForge.

**Comment by reddvilzz** [comment]
Okay then thank you for the fix. I'll close this. Have a wonderful day.
