### ISSUE TITLE
[1.19] crash server  fabric

### ISSUE THREAD

**Issue by MrJorman** [noobanidus/Lootr#124]
[crash-2022-07-11_15.15.38-server.txt](https://github.com/noobanidus/Lootr/files/9083856/crash-2022-07-11_15.15.38-server.txt)

**Comment by noobanidus** [comment]
Okay, so the entity tracker also needs to be double-synchronized...

**Comment by MrJorman** [comment]
How to understand?

**Comment by MrJorman** [comment]
How to make it so that the chests could not be blown up with dynamite? My players break chests with dynamite.

**Comment by noobanidus** [comment]
> How to make it so that the chests could not be blown up with dynamite? My players break chests with dynamite.

Could you file a separate issue for this?

> How to understand?

There's a problem with the way minecart chests are replaced, it doesn't interact properly with another mod properly.

**Comment by MrJorman** [comment]
fix please!

**Comment by embeddedt** [comment]
This should be fixed in https://www.curseforge.com/minecraft/mc-mods/lootr-fabric/files/3873766, although on an off-topic note I would warn you that a lot of other mods are likely to have issues with C2ME.

**Comment by MrJorman** [comment]
Thank!
