### ISSUE TITLE
[1.19 Fabric] My players break chests with dynamite.

### ISSUE THREAD

**Issue by MrJorman** [noobanidus/Lootr#125]
How to make it so that the chests could not be blown up with dynamite? My players break chests with dynamite.

**Comment by MrJorman** [comment]
Fabric 1.19

**Comment by Laifsyn** [comment]
Install CraftTweaker. 

Edit the ExplosionResistance. And on the way, also edit the BlocksDefaultStates hardness so they can't "mine" it

Edit: You need about 16.0 Explosion resistance to make them unbreakable for vanilla TNT. You can find the numbers in Minecraft Wiki

**Comment by MrJorman** [comment]
I use Fabric, no craft tweaker, FIX mod Lootr.

**Comment by MrJorman** [comment]
**Please fix this value in the Lootr fashion itself. So that it was impossible to blow up the chests with beds in hell/edge and dynamites in the ordinary world.**

**Comment by noobanidus** [comment]
I appreciate your concern but whatever fixes are made will take place when I'm ready. There are a few considerations to make first, though, including things like the Desert Pyramid traps and similar, where the explosion is *meant* to destroy chests. I need to work out how to consider that properly.

**Comment by MrJorman** [comment]
> I appreciate your concern but whatever fixes are made will take place when I'm ready. There are a few considerations to make first, though, including things like the Desert Pyramid traps and similar, where the explosion is _meant_ to destroy chests. I need to work out how to consider that properly.

It's not a big deal. I just don't need them to explode there. It's not a big deal. I just don't need them to explode there. Make it so that you can't blow up these chests with anything at all, make them 99999 protection.

**Comment by MrJorman** [comment]
I really need it. Just output it as a separate function, many servers will need this theme.

**Comment by embeddedt** [comment]
@MrJorman Do you need this feature on custom chests or chests that are part of world generation?

**Comment by MrJorman** [comment]
lootr chest, lootr barrel, lootr shalkers, lootr minecarts.

**Comment by embeddedt** [comment]
Sorry, maybe I was unclear. Do you need the feature on chests you make yourself using `/lootr custom`, or chests that are made by replacing structure chests (like dungeons, mineshafts, etc) when a world is generated?

**Comment by MrJorman** [comment]
Option 2.

**Comment by Laifsyn** [comment]
I personally want the first. So it's a item id different to the ones in structures.

as for in case option2 would have to be implemented, then it is either all chests are blast resistant, or none at all. Which imo isn't practical due to your stated reasons about pyramid's chests

**Comment by embeddedt** [comment]
It'd be nice to avoid using additional IDs if possible because they are limited in 1.12 without additional extender mods. I'm not sure if it's possible to control explosion resistance with a block state property or not. In any case, I'll follow suit with whatever gets implemented for 1.18/1.19.

**Comment by MrJorman** [comment]
need 1.19 fabric really.

**Comment by Laifsyn** [comment]
> ossible because they are limited in 1.12 without additional extender mods. I'm not sure if it's possible to control explosion resistance

I thought we were talking about the current versions that LootR are available. Are there plans to backport to 1.12?

**Comment by embeddedt** [comment]
Lootr is available for 1.12.

**Comment by Laifsyn** [comment]
Oh, Forge version backported

**Comment by MrJorman** [comment]
Please add Lootr explosion protection, set the value to 9999 protection, as chests can explode creepers, dynamites, and other things from mods.
