### ISSUE TITLE
Minecart with Chest loot

### ISSUE THREAD

**Issue by Lartza** [noobanidus/Lootr#13]
Minecart with Chest never gets cleared and instead refills when you close it, effectively duping the original loot infinitely.

EDIT:
Probably should have not been as hasty but busy playing ;P
Enigmatica 6 so Forge 36.0.10 and lootr-1.16.4-0.0.4.13.jar
Regular loot chests in vanilla villages worked fine.

**Comment by ChloeDawn** [comment]
The minecart also does not drop a chest when destroyed

**Comment by noobanidus** [comment]
a) Hm. This could be an oops on my part.

b) Hm, the first I can do something about, the second I'm not sure.

**Comment by noobanidus** [comment]
So, with Forge 35.1.7 and 0.0.4.13, I'm not able to replicate this *in single player* which may be why I've missed it. Going to experiment with server now.

**Comment by Lartza** [comment]
Yeah sorry I was playing on a server too, forgot to mention.

**Comment by noobanidus** [comment]
This is fixed as of 0.0.4.15.
