### ISSUE TITLE
crash server Carpet + Lootr

### ISSUE THREAD

**Issue by MrJorman** [noobanidus/Lootr#130]
https://github.com/gnembon/fabric-carpet/issues/1496 check

**Comment by MrJorman** [comment]
[crash-2022-07-15_17.57.12-server.txt](https://github.com/noobanidus/Lootr/files/9121914/crash-2022-07-15_17.57.12-server.txt)

**Comment by noobanidus** [comment]
This looks to be an issue with carpet rather than with Lootr; I don't think there's anything I can do about it.

If reported otherwise, can you ask the carpet developers to contact us?
