### ISSUE TITLE
Compatible with other mod

### ISSUE THREAD

**Issue by Hakoyu** [noobanidus/Lootr#131]
[The Graveyard](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)
The coffin in The Graveyard can also be used as a loot

**Comment by noobanidus** [comment]
These can be added via the configuration (for Forge) or via a data pack (for Fabric), [see the default handling of Vanilla blocks for an example](https://github.com/noobanidus/Lootr/tree/fabric-1.18/src/main/resources/data/lootr/tags/blocks/convert).
