### ISSUE TITLE
[1.12.2] Loot dupe by breaking chest

### ISSUE THREAD

**Issue by Krutoy242** [noobanidus/Lootr#133]
After taking items from Lootr Chest, i can brake it and get double amount of loot.

https://user-images.githubusercontent.com/936618/179733007-f136dbde-d67c-4d9e-9a3a-b052f5582ece.mp4

 How i can disable this behavior?
I want loot chest still being breakable, but not drop additional list of items if i already looted it.

**Comment by embeddedt** [comment]
Thanks. This was an oversight when backporting; the chests should not drop loot and should also drop the equivalent vanilla item rather than a Lootr one. Fixed in 0.4.2.
