### ISSUE TITLE
[1.18.2] Lootr (lootr) has failed to load correctly

### ISSUE THREAD

**Issue by KajesLorian** [noobanidus/Lootr#134]
https://pastebin.com/11M4fXSi

Lootr version: lootr-1.18-0.1.17.54
Forge version: 1.18.2 40.1.68

**Comment by noobanidus** [comment]
I need a copy of the latest.log file; something is crashing during mod loading rather than necessarily Lootr failing.

**Comment by KajesLorian** [comment]
https://pastebin.com/hUNPMBd2

**Comment by noobanidus** [comment]
Ah, you're using the 1.18.0/1.18.1 version of Lootr. Please update to the 1.18.2 version.

**Comment by KajesLorian** [comment]
Oh, I see! The 1.18.0 version was the one showing up on the main page release. I didn't think to check the Files. Thank you!

**Comment by noobanidus** [comment]
> Oh, I see! The 1.18.0 version was the one showing up on the main page release. I didn't think to check the Files. Thank you!

Yeah, unfortunately CurseForge doesn't separate 1.18.0/1.18.1 and 1.18.2 into separate versions so this happens, while binaries compiled aren't necessarily compatible between them. Thanks, Mojang!
