### ISSUE TITLE
In the wightcraft modpack, chest content generation can run VERY long

### ISSUE THREAD

**Issue by andersje** [noobanidus/Lootr#136]
(link to modpack:  https://www.curseforge.com/minecraft/modpacks/wightcraft )
I have noticed that generating the contents of chests can take upwards of 120 seconds.
This causes java to kill the server unless max-tick-time is set to a high value.  This seems to happen when a buried treasure map is in the chest.

**Comment by noobanidus** [comment]
Does this occur without Lootr installed?

I'm pretty sure this would happen with a normal Vanilla loot chest as well. You might want to see if the asynchronous locate mod is available for your modpack. Please check out the pinned (but closed) issue on server watchdogs #100.
