### ISSUE TITLE
Modrinth Avaliability

### ISSUE THREAD

**Issue by BattleCh1cken** [noobanidus/Lootr#137]
It would be nice to have this mod available on Modrinth, an alternative to Curseforge. Their API is much more open, allowing for better 3rd party tools for server hosting, as well as 3rd party clients, and better distribution of modpacks.

**Comment by noobanidus** [comment]
At the minute, the time investment to get Modrinth up and running is too great for me compared to the benefits obtained, as it appears to have a small market share compared with CurseForge. I'll keep this open as a reminder to myself when I eventually have the time to dedicate to it.

**Comment by BattleCh1cken** [comment]
Alright. Thanks for contributing your time!
