### ISSUE TITLE
Lootr mod Fails to Load in v1.12.2

### ISSUE THREAD

**Issue by pakennyusa** [noobanidus/Lootr#139]
I am unable to launch my pack after adding lootr 1.12.2 beta build latest.

Below is the crash report from forge/technic launcher (which we use for the modpack)
[https://pastebin.com/Xs9uC4Xp](url)

sorry i can't paste the entire log file here ti was too big.

**Comment by noobanidus** [comment]
Unfortunately that crash report isn't valid. Can you try posting it to [gist.github.com](gist.github.com)?

**Comment by embeddedt** [comment]
The paste seems to have expired but please ensure you have installed MixinBooter.

**Comment by embeddedt** [comment]
I'm going to close this as there hasn't been any response.
