### ISSUE TITLE
Lootr Chests Refresh Issue

### ISSUE THREAD

**Issue by Cyranos** [noobanidus/Lootr#140]
Lootr Chests as stated in the discord but I will reinstate it here, currently if you have refresh all enabled, and the delay set to 0 or any small number requires players to first open a chest initially too get the initial loot, then they will need to close it wait the allotted delay, then re-open & close the chest then open it once more so that the player is able to get the new loot.
This was tested on fabric 1.18.2

**Comment by noobanidus** [comment]
Okay, I can replicate this on base 1.16.5. It looks like the issue is that, once refreshed, it doesn't check to see if it should begin refreshing again. I'll try to fix that.

**Comment by noobanidus** [comment]
I believe this was fixed; please comment if more recent versions don't work how you expect.
