### ISSUE TITLE
Lootr Chat Alternative Suggestion

### ISSUE THREAD

**Issue by Cyranos** [noobanidus/Lootr#141]
A suggestion would be instead of using the chat to give the player info to instead use the same system that beds use to inform you that you've set your respawn or that you can't sleep cause there are monsters nearby, etc.

**Comment by noobanidus** [comment]
This is done in 1.16.5 and is being released, I'll look at porting it forward now that I know where it is.

**Comment by noobanidus** [comment]
Okay, this is done and released for 1.16.5, 1.18 and 1.18.2. Turns out that I already transitioned to this in 1.19 because it's the only way to do it.
