### ISSUE TITLE
[1.19.2] Crash when trying to join any world or creating a world

### ISSUE THREAD

**Issue by Austin001316** [noobanidus/Lootr#142]
Happens when trying to create a world or join any already created world
https://bytebin.lucko.me/8WYhRf8f7p

**Comment by Xplodin** [comment]
disregard mine, it was 1.18.2 that im having problems

**Comment by noobanidus** [comment]
Sorry, it took me a while to get a handle on this. Looks as though the server-getter is failing for some reason, but that code isn't required so I'll remove it and post an update.

**Comment by noobanidus** [comment]
Can you try this build? https://cdn.discordapp.com/attachments/675675241493692450/1025974198692221018/lootr-1.19-0.4.23.62.jar

**Comment by Austin001316** [comment]
I fixed my problem by recreating my instance, I assume something got corrupted and haven't had a problem since. Sorry I didn't update the issue because I forgot

**Comment by noobanidus** [comment]
Ah, thanks.
