### ISSUE TITLE
Crash when making world. Or kicked to menu when first creating.

### ISSUE THREAD

**Issue by Xplodin** [noobanidus/Lootr#143]
https://gist.github.com/Xplodin/dfe650c27573d30190c78e721eb06076

**Comment by noobanidus** [comment]
Sorry for the delay in responding to this. Can you upload your `latest.log` file as well? I'd like to confirm that there's no corruption of the world state.

What's happening here is that the `overworld()` method is returning null, which should *never* happen and I'm rather confused as to why it is happening.

**Comment by Xplodin** [comment]
I would love to help by uploading the latestlog but hurricane told my power to stay off for days. I'll get to the log as soon as power is restored.As of right now it's been about 3 days without it 

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 29, 2022 at 9:26 PM, ***@***.***> wrote:   


Sorry for the delay in responding to this. Can you upload your latest.log file as well? I'd like to confirm that there's no corruption of the world state.

What's happening here is that the overworld() method is returning null, which should never happen and I'm rather confused as to why it is happening.

**Comment by noobanidus** [comment]
No worries! Keep yourself safe.
