### ISSUE TITLE
Crash on startup, along with 2 other mods with the same issue

### ISSUE THREAD

**Issue by StarrSage** [noobanidus/Lootr#148]
[crash-2022-10-30_17.21.00-fml.txt](https://github.com/noobanidus/Lootr/files/9897544/crash-2022-10-30_17.21.00-fml.txt)

**Comment by noobanidus** [comment]
It looks like one of your config files is corrupted. Check through them, specifically for the first line, looking for something that is ***not*** in the format of `key=value`.

EDIT: Specifically this is "supplementaries-registry.toml".
