### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by StarrSage** [noobanidus/Lootr#153]
It has been running fine up until today, no changes made to my mods it just...broke. I tried deleting it and redownloading it, but it didn't work.
[crash-2022-11-13_14.25.08-fml.txt](https://github.com/noobanidus/Lootr/files/9998037/crash-2022-11-13_14.25.08-fml.txt)

**Comment by noobanidus** [comment]
Looks as though your config file for Lootr has been corrupted, try deleting it.

**Comment by StarrSage** [comment]
I deleted all my mods and redownloaded updated versions, it works now. Thank you
