### ISSUE TITLE
crash when installed with optifabric

### ISSUE THREAD

**Issue by gaesyeah** [noobanidus/Lootr#154]
minecraft actually doesnt even open.
(minecraft 1.19.2, fabric 0.14.10)
[crash-2022-11-18_19.12.01-client.txt](https://github.com/noobanidus/Lootr/files/10045191/crash-2022-11-18_19.12.01-client.txt)
[crash-2022-11-18_19.12.01-server.txt](https://github.com/noobanidus/Lootr/files/10045192/crash-2022-11-18_19.12.01-server.txt)

**Comment by noobanidus** [comment]
Does this issue still occur?

**Comment by noobanidus** [comment]
Please open a new issue if this continues to occur.
