### ISSUE TITLE
1.18 Compatibility issue with ChoiceTheorem-s-overhauled-village

### ISSUE THREAD

**Issue by samos667** [noobanidus/Lootr#156]
Some chest of [ChoiceTheorem-s-overhauled-village](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village) are empty.
![image](https://user-images.githubusercontent.com/50653464/205978979-31836a8b-bbe7-4ab7-8330-3a00d0f1e256.png)

When i open chest i have this log:
[18:18:29] [Server thread/ERROR]: Unable to fill loot chest in ResourceKey[minecraft:dimension / minecraft:overworld] at class_2338{x=8950, y=73, z=6836} as the loot table 'ctov:village/mesa_fortified/generic' couldn't be resolved! Please search the loot table in `latest.log` to see if there are errors in loading.

Full log [here](https://pastebin.com/PuVeh3Ns)

**Comment by samos667** [comment]
Is not always the case sometimes loot is generated, is so weird (in the same village):
![image](https://user-images.githubusercontent.com/50653464/206001694-ae1f6460-28e7-4f31-8376-2e6691198ddb.png)

**Comment by samos667** [comment]
Mb is a [ChoiceTheorem-s-overhauled-village](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village) issue, i have test without lootr and i have some empty loot chest like before.

**Comment by noobanidus** [comment]
Yeah, this means that this loot table is invalid for whatever reason.
