### ISSUE TITLE
Config option to enable/disable refresh time message?

### ISSUE THREAD

**Issue by marianyp** [noobanidus/Lootr#159]
Could we get a config option to disable/enable the refresh time message that shows when the refresh_all config is enabled.

Im in a situation where opening chests is a constant part of gameplay. So the messages become pretty spammy everytime the player opens a chest.

**Comment by noobanidus** [comment]
Sure! That's something I can add when I port barrels supported by the `/lootr custom` command to other versions. I'm not sure how long it'll take me to get to it though!

**Comment by noobanidus** [comment]
This is available in the most recent versions of Lootr for Forge 1.18/1.19. The messages can be disabled or configured to only display when the amount of time remaining is below a certain point.
