### ISSUE TITLE
Check Here First! Known Incompatibilities/Active Pull Requests

### ISSUE THREAD

**Issue by noobanidus** [noobanidus/Lootr#16]
**Aware**
- ~~Ocean ruins are non-functional: #48~~
- ~~Chest minecarts are no longer being converted: #47~~

**Alerted**
- [Dungeons Mod](https://www.curseforge.com/minecraft/mc-mods/dungeons-mod) (ARR, will require an issue filed as I can't PR it.)
- [Ice and Fire](https://github.com/Alex-the-666/Ice_and_Fire/tree/1.16.3/src/main/java/com/github/alexthe666/iceandfire) (only some of them are relevant)
- [Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest) (see Issue https://github.com/TeamTwilight/twilightforest/issues/1417)

**Awaiting merge/discussion:**
- [Charm](https://www.curseforge.com/minecraft/mc-mods/charm-reforged) (PR: https://github.com/svenhjol/CharmForge/pull/125)
- [Autumnity](https://www.curseforge.com/minecraft/mc-mods/autumnity) (PR: https://github.com/team-abnormals/autumnity/pull/109)

**Partially merged/may require additional PR:**
- None

**Currently merged and awaiting verification of release:**
- [The Farlanders](https://gitlab.com/modding-legacy/the-farlanders/-/merge_requests/1)
- [End Remastered](https://www.curseforge.com/minecraft/mc-mods/endremastered) ([PR](https://gitlab.com/endrem/end-remastered/-/merge_requests/20))

**Merged and released:**
- ~~[Atum 2](https://www.curseforge.com/minecraft/mc-mods/atum) (PR: https://github.com/TeamMetallurgy/Atum2/pull/338)~~
- ~~[Dungeon Crawl](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl) (PR: https://github.com/xyroc/DungeonCrawl/pull/93)~~
- ~~[Apotheosis](https://github.com/Shadows-of-Fire/Placebo/pull/19) via Placebo~~
- ~~[Quark](https://github.com/Vazkii/Quark/pull/3036) (obsidian pillars)~~
- ~~[YUNG's Better Mineshafts](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/pull/38)~~
- ~~[Dungeons Plus](https://gitlab.com/modding-legacy/dungeons-plus/-/merge_requests/3)~~
- ~~[EvilCraft](https://github.com/CyclopsMC/EvilCraft/pull/833)~~
- ~~[Artifacts](https://github.com/ochotonida/artifacts/pull/55)~~
- ~~[Dimensional Dungeons](https://github.com/AllenSeitz/DimDungeons/pull/16)~~
- ~~[Astral Sorcery](https://github.com/HellFirePvP/AstralSorcery/pull/1655)~~

**Independently Resolved**
- ~~[Shrines](https://github.com/Silverminer007/Shrines/blob/master/updateJSON.json#L20)~~

**Will most likely never be compatible**
- Futurepack uses extensive custom coding to generate their loot chests with loot in them, bypassing the Vanilla system. Without a significant change to this system (which I'm not willing to try to implement, not am I even sure if they are interested in having implemented), it is **not possible** in the slightest for there to be compatibility.
- [Dungeons Gear](https://www.curseforge.com/minecraft/mc-mods/dungeons-gear) uses a complex system of mixnis that I have no desire to navigate.

If the mod you've found as being not compatible with Lootr isn't listed here, please comment on this issue. Include screenshots wherever possible.

Alternately, you can post in the #lootr-incompatible channel on my Discord.

**Comment by NillerMedDild** [comment]
The mod Eidolon is missing Lootr compat :)

**Comment by noobanidus** [comment]
So as far as I can tell, Eidolon uses NBT values in the structure, there's no reason why Lootr shouldn't be catching them. I guess it's possible something else is interfering? (Perhaps Quark?)

**Comment by NillerMedDild** [comment]
I'll do a thorough check this evening :)

**Comment by NillerMedDild** [comment]
Eidolon structures are working just fine with Lootr, my bad ^^'

**Comment by noobanidus** [comment]
That's fine! I can understand the confusion.

**Comment by krlenell** [comment]
I think Mana and Artifice actually has problems with this too, they are not converted.

**Comment by noobanidus** [comment]
I've seen screenshots of a specific Mana & Artifice building not being converted properly -- I believe it was a village one?

**Comment by krlenell** [comment]
Yes, it was an outdoor villager workstation.

**Comment by noobanidus** [comment]
I'll need to look into it further as it's the only one that isn't functioning properly, as far as I can tell.

**Comment by Zu-Sushi** [comment]
Ice and Fire Dragon Mod please

**Comment by noobanidus** [comment]
Thanks, I'll look into this!

**Comment by yftechno** [comment]
The only issue with Ice and Fire that I seen that one structure (kinda common structure) has a custom chest type. The other structures where they generate chests seemed fine for me.

**Comment by noobanidus** [comment]
Unfortunately, if it's a custom chest type I've not yet implemented an API for support those yet.

**Comment by yftechno** [comment]
Quark has chests inside of these pillars of obsidian in the nether; they are not being converted to lootr chests.


Edit: I don't know if there are other chests in quark, I am currently checking.

**Comment by noobanidus** [comment]
Oh thanks! I'll check those out.

**Comment by noobanidus** [comment]
@yftechno [I've submitted a PR for the obsidian pillars](https://github.com/Vazkii/Quark/pull/3036). You can check for other instances basically by looking for `setLootTable`.

**Comment by yftechno** [comment]
@noobanidus I was wrong about Ice and Fire; There are some non-custom chests in it that I forgot about; that generate in a non-locateable location (cyclops dens, and maybe dragon dens, forgot to look there).

**Comment by faeldray** [comment]
[Shrines Structures](https://www.curseforge.com/minecraft/mc-mods/shrines-structures) doesn't have compatibility with Lootr

![2021-03-11_15 55 04](https://user-images.githubusercontent.com/967709/110860296-361a8880-8282-11eb-88d9-9653fd00a1aa.png)

**Comment by willtarax** [comment]
[Inventory Pets](https://www.curseforge.com/minecraft/mc-mods/inventory-pets) and [Nugget's Dungeons II](https://www.curseforge.com/minecraft/mc-mods/nuggets-dungeons-ii)

**Comment by willtarax** [comment]
> [Inventory Pets](https://www.curseforge.com/minecraft/mc-mods/inventory-pets) and [Nugget's Dungeons II](https://www.curseforge.com/minecraft/mc-mods/nuggets-dungeons-ii)

ALTHOUGH Nugget's seems to have specific loot in their chests, so I don't know if they use a loot table, which might kill the integration with this mod.

**Comment by noobanidus** [comment]
With regards to Inventory Pets, they also manually inject loot. There's nothing I can do about it. Shrines, I can.

**Comment by faeldray** [comment]
I asked the Shrines dev to add compatibility and they've done it so you can cross it off the list.

https://github.com/Silverminer007/Shrines/issues/7

**Comment by mahjerion** [comment]
I PRd the fixes for Apotheosis (Placebo), YUNG's, Dim Dungeons, and Dungeons Plus for 1.15.2. Hopefully they'll all accept (got confirmation from all except Dungeons Plus so far. Could be helpful to edit the original post saying those fixes have been backported :O

**Comment by Scratchman** [comment]
Twilight Forest .. 
![image](https://user-images.githubusercontent.com/5376586/123877374-ea9fef00-d8f1-11eb-8f50-5ef4a0d6dacd.png)

**Comment by noobanidus** [comment]
Oh, one I actually can do something about!

**Comment by ModernGamingWorld** [comment]
Ice and Fire

**Comment by noobanidus** [comment]
> Ice and Fire

So this [was discussed on my Discord in late May](https://discord.com/channels/524907814603456522/800879155443925023/844320454725468181). Do you have a screenshot of the specific chests that aren't being converted?

**Comment by ModernGamingWorld** [comment]
> > Ice and Fire
> 
> So this [was discussed on my Discord in late May](https://discord.com/channels/524907814603456522/800879155443925023/844320454725468181). Do you have a screenshot of the specific chests that aren't being converted?

![2021-07-18_18 38 52](https://user-images.githubusercontent.com/75923060/126085826-f866d80c-a923-408a-a82a-ac5d68b10a86.png)
![2021-07-18_18 45 19](https://user-images.githubusercontent.com/75923060/126085828-aa592059-d6c6-4c2e-a287-4aef2967406e.png)

Just a few that have no changed over, but its the same for the other ice and fire stuff

**Comment by noobanidus** [comment]
Hm, that's interesting.

Can you enable the logging functionality that spits out a message when it encounters a chest that it can't convert? If those don't specifically show up, it means they don't actually have a loot table associated with them and are instead generated with the loot manually -- which means they're not something I can add integration for. :/

**Comment by szunakabeats** [comment]
[Dungeons Gear](https://www.curseforge.com/minecraft/mc-mods/dungeons-gear)

**Comment by szunakabeats** [comment]
[When Dungeons Arise](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)

**Comment by noobanidus** [comment]
Some recent changes may have broken NBT-based structures.

**Comment by TheSnowyChickens** [comment]
something is wrong with the buried_treasure, I can't open the chest AND the server tell me "block entity invalid"

![grafik](https://user-images.githubusercontent.com/29357962/129485398-ba340d45-bdd1-4e07-8a39-442c75825685.png)

MC: 1.16.5
Forge: 36.2.2
LR: 0.0.7.21

**Comment by ArMoReDfUrY** [comment]
> something is wrong with the buried_treasure, I can't open the chest AND the server tell me "block entity invalid"
> 
> MC: 1.16.5
> Forge: 36.2.2
> LR: 0.0.7.21

I am having the same issue but with Vanilla drowned ruins. same versions of Forge, MC & Lootr.

**Comment by TheSnowyChickens** [comment]
@ArMoReDfUrY weird is: I blacklisted "buried_treasure" and somehow it work now. xD

**Comment by ArMoReDfUrY** [comment]
> @ArMoReDfUrY weird is: I blacklisted "buried_treasure" and somehow I work now. xD

i tried the blacklist for the underwater_ruins_big/small with no change. still got a failed convert message and chests are non interactive.

**Comment by noobanidus** [comment]
> something is wrong with the buried_treasure, I can't open the chest AND the server tell me "block entity invalid"
> 
> ![grafik](https://user-images.githubusercontent.com/29357962/129485398-ba340d45-bdd1-4e07-8a39-442c75825685.png)
> 
> MC: 1.16.5
> Forge: 36.2.2
> LR: 0.0.7.21

What other mods are you running?

**Comment by noobanidus** [comment]
It appears as though the loot chest *tile entity* is being replaced but the chest block itself isn't.

**Comment by TheSnowyChickens** [comment]
![grafik](https://user-images.githubusercontent.com/29357962/129493734-cdaf954c-4156-489d-b285-a65a2d9f1ff8.png)

**Comment by willtarax** [comment]
I have found that End Remastered does not seem to lootr their chests.

**Comment by noobanidus** [comment]
I'll try to work on these issues this week, especially the Vanilla ones.

**Comment by Thombias** [comment]
Hello i've noticed that minecart chests in vanilla mineshafts as well as in YUNG's better mineshafts don't get replaced by Lootr chests in one of my test worlds. 1st pic is in vanilla mineshaft, 2nd pic in YUNG's better mineshaft and 3rd pic is my mod list.
![2021-08-23_13 24 52](https://user-images.githubusercontent.com/46842890/130440255-30c1789b-3ffa-4967-80af-491f48866cfe.png)
![2021-08-23_13 21 15](https://user-images.githubusercontent.com/46842890/130440267-56e303ac-dd87-48d3-bb56-d069546deeb0.png)
![Modlist](https://user-images.githubusercontent.com/46842890/130440282-8e0f22fb-7634-4c78-8dc4-624455b1e93f.PNG)

**Comment by noobanidus** [comment]
Is the Mineshaft replacement perhaps disabled?

**Comment by Thombias** [comment]
I just checked both lootr & bettermineshaft config files and all settings were left at default values. I have all "convert_xyz" options set to true. What could be the issue then i wonder? I could try to enable report_tables and check again.

**Comment by noobanidus** [comment]
Is this happening with just Lootr & Better Mineshafts?

**Comment by Thombias** [comment]
Hmm, that's odd. Neither the log or chat is throwing out any errors regarding minecart chests not getting replaced...
But to answer your question: So far the only chests i know of that don't get replaced by Lootr in my WIP modpack are Ice & Fire chests in dragon roosts & dragon caves, the chests in Dungeon Crawl dungeons and the minecart chests.

Edit: i just realised what you meant by just Lootr and Better Mineshafts... lmao i'm stupid. Gimme a few minutes, i'm gonna test it on a fresh install with just those 2 mods!

**Comment by Thombias** [comment]
Ok, i can confirm it's still happening on a fresh install with only YUNG's better mineshafts and Lootr installed with no config edits whatsoever. What i find weird though is that buried treasure chests now work fine. They were completely broken in my WIP modpack, couldn't be opened at all and didn't have the change in texture.

**Comment by noobanidus** [comment]
> Twilight Forest ..
> ![image](https://user-images.githubusercontent.com/5376586/123877374-ea9fef00-d8f1-11eb-8f50-5ef4a0d6dacd.png)

Twilight Forest isn't getting any updates for 1.16.5 unless it's a dupe bug or something otherwise critical. When mixins become available for 1.17.1 and Lootr is ported, I'll do a PR then.

**Comment by noobanidus** [comment]
> Ok, i can confirm it's still happening on a fresh install with only YUNG's better mineshafts and Lootr installed with no config edits whatsoever. What i find weird though is that buried treasure chests now work fine. They were completely broken in my WIP modpack, couldn't be opened at all and didn't have the change in texture.

Apologies for the delay, the most recent release, [0.0.8.22](https://www.curseforge.com/minecraft/mc-mods/lootr/files/3441661) fixes both this and the issue with ocean structures, all of which were very simple errors that I should've picked up on. My bad!

**Comment by noobanidus** [comment]
@TheSnowyChickens  Apologies for the delay. Do you have an export of this pack? I haven't been able to reproduce it locally with just Lootr.

**Comment by noobanidus** [comment]
> [Dungeons Gear](https://www.curseforge.com/minecraft/mc-mods/dungeons-gear)

There is absolutely *no* way to support this. They mixin to containers and minecarts to manually do stuff.

> [When Dungeons Arise](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)

This mod is All Rights Reserved. You'll have to open an issue with them and ask them to make sure they use the static method LockableLootTileEntity::setLootTable rather than the instance member method.

**Comment by noobanidus** [comment]
> I have found that End Remastered does not seem to lootr their chests.

I've filed a PR with them for it.

**Comment by TheSnowyChickens** [comment]
The pack is not in a good condition, we updated the pack with some recent updates.

I can give you a curse forge export later today (+13h from this post time)

**Comment by noobanidus** [comment]
> The pack is not in a good condition, we updated the pack with some recent updates.
> 
> I can give you a curse forge export later today (+13h from this post time)

No worries, just whenever. I'm not sure I'll be able to have time to look at it. I'm also curious if the buried treasure thing is still happening as of 0.0.8.22. The other commentor mentioned drowned ruins which was an actual bug (I was missing a `!` at an essential point), but as far as I can tell in my testing the buried treasure works properly.

I may re-test with quark to see if it's some odd quirk of quark.

**Comment by TheSnowyChickens** [comment]
Download link:
https://cloud.krk-gaming.de/s/fTFDa7qXwo5B35N
(163mb because stupid curse forge)

**Comment by Pockett-Dev** [comment]
Autumnity's "maple_witch_hut" is currently not working :(

https://www.curseforge.com/minecraft/mc-mods/autumnity

**Comment by noobanidus** [comment]
> Autumnity's "maple_witch_hut" is currently not working :(
> 
> https://www.curseforge.com/minecraft/mc-mods/autumnity

Please report this to Autumnity. [This line](https://github.com/team-abnormals/autumnity/blob/34aabfe0a0ddeff2cca9d5dd36cbf2c28d561408/src/main/java/com/minecraftabnormals/autumnity/common/world/gen/feature/structure/MapleWitchHutPieces.java#L90) needs to change to `LockableLootTileEntity.setLootTable`'s static method.

**Comment by noobanidus** [comment]
I've created a PR for Autumnity.

**Comment by noobanidus** [comment]
> > [When Dungeons Arise](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
> 
> This mod is All Rights Reserved. You'll have to open an issue with them and ask them to make sure they use the static method LockableLootTileEntity::setLootTable rather than the instance member method.

This appears to use NBT structure pieces and the Jigsaw system, and should be supported automatically.
