### ISSUE TITLE
Incorrectly Marked 1.19.3

### ISSUE THREAD

**Issue by AzureDoom** [noobanidus/Lootr#160]
Your mod does not work with 1.19.3 due to the creative menu tab changes and is incorrectly marked to supported 1.19.3.
![image](https://user-images.githubusercontent.com/7415711/208741624-b0a8ba10-f146-4976-8501-2965816a4ba8.png)

Crash report with just this and Fabric on 1.19.3
https://gist.github.com/AzureDoom/bc4601b1dddafa987766a18c215532c4

**Comment by ZestyBlaze** [comment]
Working on that now, that was brought up by Cattus in MMD too, I'll unmark it now and release a correct version

**Comment by AzureDoom** [comment]
Thanks! Been missing this mod!

**Comment by ZestyBlaze** [comment]
There we go, all done and updated!
