### ISSUE TITLE
Server hangs when a new lootr container opens

### ISSUE THREAD

**Issue by superhealing** [noobanidus/Lootr#161]
Info : 
lootr-1.12.2-0.5.1.jar
openj9
Enigmatica 2: Expert - Extended modpack (v0.88.0)
Running as server.

Background : People playing that server experience TPS lag when open new chests/containers for looting, as example astral chest/dungeon so on. This can last roughly 5-15 seconds. 
spark output : https://spark.lucko.me/G4hhTLUQjv

Let me know if you need a bit more information.

**Comment by embeddedt** [comment]
Thank you for the Spark profile; it's very helpful!

Does your server happen to have any particularly large `.dat` files in its `world/data` folder?

**Comment by superhealing** [comment]
> Thank you for the Spark profile; it's very helpful!
> 
> Does your server happen to have any particularly large `.dat` files in its `world/data` folder?

According with `world/data` only files large enough is: `reccomplex-structuredata.dat` - 53 megabytes `Village.dat`, roughly 4.5 megabytes, `Mineshaft.dat` - 2.9 megabytes and rest is roughly 14 kilobytes and lower.

**Comment by embeddedt** [comment]
Those first three are huge. I don't believe the world should suffer adverse effects from them being deleted, so I recommend stopping the server, deleting them, and restarting it; that should fix the problem. The rest of the files can be left untouched.

To be clear the issue is not directly related to Lootr. It happens to trigger saving of these files when a chest is opened, which takes a very long time when they are this big.

**Comment by superhealing** [comment]
Indeed, the files deleted have fixed all issues, very weird how does relate to lootr loot tables. Thanks for quick response.

**Comment by embeddedt** [comment]
It's not directly related to Lootr; it's actually a core flaw in 1.12.2 that Lootr just happens to expose. You've probably been experiencing similarly long lag spikes whenever the server saves the world.

**Comment by superhealing** [comment]
Actually... i was researching about exactly similar issue, i haven't given much thought about nbt data. Thanks for helpful informations. You can close the issue.
