### ISSUE TITLE
Monunental experience

### ISSUE THREAD

**Issue by Angelus022695** [noobanidus/Lootr#162]
I'm playing the most recent monumental experience pack and most of the lootr chests will not open.

**Comment by noobanidus** [comment]
1) Please check the config option for displaying erroring loot tables and ensure it's on; this'll tell you when you try to open a chest if there's an issue with the loot table.
2) Check the `latest.log` file for errors related to loot tables (you should be able to search "lootr" to look through it).

If neither of these answer it, please upload the log file for me to look at.

**Comment by noobanidus** [comment]
Are you able to provide any more information about this?

**Comment by noobanidus** [comment]
Unfortunately I need more information to deal with this. Please open a new issue if your problem is persisting and provide the various log files that I requested above.
