### ISSUE TITLE
Loot duplication bug

### ISSUE THREAD

**Issue by RobertasJ** [noobanidus/Lootr#163]
Whenever you have first opened a lootr chest and keep it open while a different person also opens it for the first time the person who originally had the cheat open gets 2x loot. you can keep getting more people to do this to get even more loot.

**Comment by noobanidus** [comment]
That's a bit of a strange one.

What versions and modloaders is this happening in? It sounds as though the container is being updated for everyone rather than the individuals who just opened it.

**Comment by RobertasJ** [comment]
Im sorry for bothering i mixed up the mod for loot crates we use. It was a different mod that does the same thing and i mixed it up with this :|

**Comment by noobanidus** [comment]
That's fair! I was starting to worry, because it's not implausible that something like this might happen. Good to know, and thanks for the update!
