### ISSUE TITLE
Loot Barrel's having no texture 1.19.3

### ISSUE THREAD

**Issue by Zelioth** [noobanidus/Lootr#164]
Minecraft 1.19.3
Forge 44.1.5
Lootr 0.4.23.60
![2023-01-20_18 21 24](https://user-images.githubusercontent.com/77481431/213828617-4e7fc367-42e1-47c3-96c1-0fd9ce5e0521.png)

While playing and finding generated loot barrels it seems none have texture.

**Comment by noobanidus** [comment]
Thanks for this report! I'll take a loot into it.

**Comment by embeddedt** [comment]
I'm not too surprised this happened; I probably made some mistake when porting the barrel baked model to 1.19.3 (model handling changed a decent amount).

**Comment by noobanidus** [comment]
Yeah, that's my assumption as well; there's also a 1.18 report on the CurseForge comments regarding chest textures that I haven't been able to figure out.

**Comment by ColdTearsYY** [comment]
Hoping to see it fixed soon!

**Comment by noobanidus** [comment]
Sorry for the delay, I believe this issue should be resolved in the most recently released version on CurseForge (marked as a beta).
