### ISSUE TITLE
Roses are red, violets are blue, I Found an Issue Just for You.

### ISSUE THREAD

**Issue by Zelioth** [noobanidus/Lootr#165]
Minecraft 1.19.3
Forge 44.1.5
Lootr 0.4.23.60

Dedicated server environment testing and the server seems to be starting almost fully then crashing right after this 
https://gist.github.com/Zelioth/660c86344b3ad3843128dd01e281034d

Log 
https://gist.github.com/Zelioth/c4efefd6728c5af99ef11926b2935343

**Comment by noobanidus** [comment]
The "Address already in use: bind" message generally refers to the fact that a Minecraft server (or some other application) is already running on that port.

**Comment by Zelioth** [comment]
I see, I may have made a mistake when testing. I have a major mod pack built and I am going through now finding what mods give issues or crash and it's working now but I don't know what it pushed that error. My apologies, I'll close this issue as complete :D
