### ISSUE TITLE
Chunks Broken

### ISSUE THREAD

**Issue by alexrsmith16** [noobanidus/Lootr#167]
I installed this mod on my server running only phosphor and lithium. Completely broke a bunch of my chunks. Had to unload mod and like a dumbass I hadn't created a backup and I lost a lot of loot chests. Yes it was the correct version. I'm sorry that I don't have better troubleshooting steps, but I don't want to try and figure out what the problem is and just break things further.

**Comment by noobanidus** [comment]
You'll unfortunately need to provide a little more information:

- Which version of Minecraft?
- Which mod-loader?
- Which version of Lootr?

Can you also describe further how the chunks were broken? Logs, etc, will help, if you have them. Without more information there really isn't anything that can be done.

**Comment by alexrsmith16** [comment]
1.19.3
Fabric
lootr-1.19.3-0.4.25.65

This is the log for when I started the server up right after installing the mod. Let me know what other info I can provide for you. I had been watching the logs and didn't see any indication of issues.

[2023-02-02-3.log.gz](https://github.com/noobanidus/Lootr/files/10565213/2023-02-02-3.log.gz)

**Comment by noobanidus** [comment]
There don't appear to be any issues listed in the log that even imply chunks are failing to load for a specific reason.

Had anything significantly changed about the chunks that wouldn't load when you removed the mod and restarted the server? 

edit: I'd definitely recommend making a back-up of your server now at the very least, if you haven't already; likewise I would be curious to see if the chunks return to their non-loading status when reinstalled, though I can understand if you're unwilling to try it.

It's a matter of trying to find out a way to replicate the issue.

**Comment by alexrsmith16** [comment]
I'd be willing to try this again when nobody is going to be on the server. The chunks were just invisible. I seemed to be to interact with the chunks fine. It would be random chunks in the middle of the world, surrounded by chunks that were loading fine. Let me give you a better recap.

1. I installed lootr it's dependency, as well as LuckPerms and EssentailCommands.
2. Booted up the game and everything seemed fine. I started with testing out luckPerms. The I tried spectating another player who was a couple thousand blocks away. When I teleported to them the chunks around him didn't load. He was at a guardian farm next to an ocean monument. When I flew away chunks seemed to load in fine as I got further. I tried loading in with multiple different clients (vanilla, optifine, fabric, lunar). Didn't fix it.
3. So I stopped the server and removed all 4 mods I had added. Loaded the server back up, things looked back to normal.
4. So I re-added Lootr, hoping it was the other 2 mods that caused the issue. All my chunks around me were fine. But then I tried going somewhere that hadn't been loaded while lootr was added the first time. Chunk issue was back.
5. Removed lootr again and gave up, wrote the bug report.

So now that I'm writing this out I'm realizing that the chunks that were missing might have only been chunks with loot chests in them. I hadn't realized that at the time.

I also noticed that when I tried load into the world or into a different dimension. It would say loading terrain for much longer than normal.

It also seemed to matter how you loaded the chunks. Other people on the server weren't seeing the same issue, then when the re-logged they'd see the issue. Like if you teleported directly into the area it was more likely to break or something.

Let me know if I can help troubleshoot this further. I'm also a software developer so I get it. I'm not super invested in getting the mod working on my server, mostly interested in helping you find a bug, although this may be pretty edge case and have something to do with my configuration.

**Comment by noobanidus** [comment]
Do you happen to have access to the debug log for the server? That might contribute more information.

> I tried loading in with multiple different clients (vanilla, optifine, fabric, lunar). Didn't fix it.

Just to clarify, all of the people playing on this server also had the Lootr mod installed on their clients? Lootr creates new registry entries and requires that it be loaded on the clients as well.

**Comment by alexrsmith16** [comment]
If everyone needs the mod on the client side, then that's the issue. I got the impression from [curseforge](https://www.curseforge.com/minecraft/mc-mods/lootr-fabric) that it was only needed on the server-side. My mistake. But I'd suggest updating that page to make that more obvious. I'd also mention on there that the mod has a dependency.

**Comment by noobanidus** [comment]
Honestly, I thought that it was mentioned on the page; that said, there must be some issue with the Fabric version which isn't causing it to reject clients that don't have it installed. I'll need to look into this further.

**Comment by ZestyBlaze** [comment]
Hm that is an odd one, might be something with the Fabric loader that is out of our control that is broken then if its not rejecting clients without the mod
