### ISSUE TITLE
Lootr and Ferritecore

### ISSUE THREAD

**Issue by gusm143** [noobanidus/Lootr#168]
Ferrite uses an optimized block state system that Lootr doesn't quite like. It did not like the change I made and wouldn't start, so I reverted it.

Lootr is overall causing massive tick problems on my modpack server, bolstered by ferritecore block optimization.

Is this a known issue?

**Comment by noobanidus** [comment]
I'll need more information:

- Do you have a Spark profile?
- What version of Minecraft?
- What modloader?
- What version of Lootr?

And what exactly was the error with Ferritecore?

**Comment by noobanidus** [comment]
Are you able to provide any more information about this?

**Comment by noobanidus** [comment]
This may be addressed in the most recent versions of Lootr for Forge 1.18/1.19. Please open a new issue if you still have problems.
