### ISSUE TITLE
[1.16.5 FORGE] Lootr chests incompat with philips ruins

### ISSUE THREAD

**Issue by quentin452** [noobanidus/Lootr#169]
mods lists :

* Philips ruins 1.16.5-2.8 [here](https://www.curseforge.com/minecraft/mc-mods/ruins)
* lootr-1.16.5-0.1.15.46

description : 

In philips ruins structure the vanilla chests are not replaced by the lootr chest.

seed : 6619531350504736332
location : 142 149 -39

screenshot : 

![image](https://user-images.githubusercontent.com/42176772/216819281-eaa3e04c-f900-4194-a3e6-c0b5e0f06468.png)

**Comment by noobanidus** [comment]
I'm having a quick look through the mod itself; do the chests actually contain loot, and does that loot vary? It's possible that they are manually filled with loot or have no actual loot table associated with them, which means that Lootr can't convert them.

**Comment by noobanidus** [comment]
If you're still having issues with this, please open a new issue.
