### ISSUE TITLE
Forge 1.19.2 / Lootr 0.3.22.59 - Crash When Opening Chest

### ISSUE THREAD

**Issue by MAXimized490** [noobanidus/Lootr#170]
Having an issue with Lootr causing lag and eventually crashing the server via watchdog. It has so far only occurred with underwater chests.
I believe the actual issue has something to do with an item because a chest that one player has already opened can be opened by another player and then cause the lag/crash. I've read #100 and #152 and believe my issue may be similar, but I can't read the log well enough to be able to tell. I do not have Terralith but I have quite a few mods that generate structures, so maybe one of them is the culprit?
Hoping this isn't a duplicate but if it is then I apologize!

Also curious about [this issue posted on a FTB project](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2357) where a dev says that the issue is fixed in the upcoming update to Lootr, but this was posted five days after the latest release for 1.19.2. Is there a new version somewhere that fixes this?
Here's the [crash log](https://github.com/noobanidus/Lootr/files/10737662/crash-2023-02-14_14.40.46-server.txt), [latest](https://github.com/noobanidus/Lootr/files/10737705/latest.log), and [debug](https://github.com/noobanidus/Lootr/files/10737718/debug.log).

**Comment by MAXimized490** [comment]
[Issue is vanilla Minecraft.](https://bugs.mojang.com/browse/MC-249136) For anyone else finding this, the fix is to [use a datapack that replaces buried treasure maps.](https://github.com/PaperMC/Paper/issues/2312#issuecomment-516988198)

**Comment by noobanidus** [comment]
I'd also suggest checking out [Async Locater](https://www.curseforge.com/minecraft/mc-mods/async-locator) as another solution to this bug.
