### ISSUE TITLE
Fake players cannot destroy Lootr chests

### ISSUE THREAD

**Issue by SlyCedix** [noobanidus/Lootr#176]
CC: Restitched turtles get stuck when attempting to mine lootr chests, writing handling to go around them is possible, but not ideal when I don't actually care if the chests survive. I'd love a config option to disable any warnings about breaking lootr chests fake player or otherwise.

**Comment by noobanidus** [comment]
That is definitely non-ideal; is there no way to specify that the turtles are sneaking while breaking? I can definitely add an option to disable those checks, or just specifically disable them for fake players.

**Comment by SlyCedix** [comment]
Unfortunately, turtles don't have any way of sneaking while breaking

**Comment by noobanidus** [comment]
I forgot to ask, which version of Minecraft and which mod loader were you having issues with? I've got a potential custom build for 1.19.3 forge, but back-merging the changes is a bit of a pain if that doesn't work, so I'd like to give you the option of testing it out first.

**Comment by SlyCedix** [comment]
I'm using Fabric 0.14.17 on Minecraft 1.19.2

**Comment by noobanidus** [comment]
Unfortunately, at least from the code for CC Restitched, it seems as though either it isn't using it, or Fabric doesn't have an equivalent to Forge's FakePlayer, so it's impossible to tell. About the best I can do is a mode that just enables breaking regardless, for Fabric.

**Comment by noobanidus** [comment]
There's now an option in the latest 1.18.2 version of Lootr for Fabric to disable all break limitations, including by non-players. I'll be porting this to 1.19.0 soon.
