### ISSUE TITLE
ERROR creating loot 1.19.2

### ISSUE THREAD

**Issue by egori477** [noobanidus/Lootr#177]
[crash-2023-03-22_23.18.12-server.txt](https://github.com/noobanidus/Lootr/files/11044806/crash-2023-03-22_23.18.12-server.txt)
[2023-03-22-1.log](https://github.com/noobanidus/Lootr/files/11044809/2023-03-22-1.log)

When loot creating, server crash

**Comment by noobanidus** [comment]
This is #172. Please check the options and suggestions listed there.
