### ISSUE TITLE
Support double chests

### ISSUE THREAD

**Issue by Jack-McKalling** [noobanidus/Lootr#178]
When a regular double chest has a loot table and gets converted into a lootr-chest, only the half that has the loot will get converted.
But there should really be a double chest variant of the lootr-chest.

**Comment by noobanidus** [comment]
As far as I'm aware, when it comes to Vanilla, unless you specify both halves of a double chest as loot, it will only generate loot for the first half.

I realize this is non-ideal but the frequency of double-loot chests wasn't particularly common when I started the mod, so I've not implemented them.

**Comment by Jack-McKalling** [comment]
I don't think there are double loot chests either, but I mean, when there is a chest that has loot in it, and another chest connects to it, eventhough it isn't both halves with loot, they do connect. If a loot chest forms a double chest, then regardless of the fact that the other half is "empty", it should still be converted to a double lootr-chest for the purpose of maintaining the double chest.

When this mod is used in modpacks, and there is a double chest occurrence (e.g. a vanilla spawner dungeon that happened to generate one), it just looks better if both halves are converted, or there would be two separate chests one of which has the fancy colours and the other one would just remain the normal vanilla one and be empty. It just doesn't look too good.

**Comment by noobanidus** [comment]
I understand the aesthetic appeal, but code-wise double chests are a *nightmare* which involve a large amount of special-casing, as, in practice, it is two separate chests which are just given a single visual. I don't plan to support them any time soon, but it's a possibility for the future.

**Comment by Jack-McKalling** [comment]
Understandable. We can leave this open as long as you need/want.

**Comment by jnollen13** [comment]
In mods you can make double chests with loot tables for both halves but lootr keeps splitting these double chests apart. My mod atheria has one structure with a double chest where each half of the chest has a different loot table and in vanilla when I open it it just sticks the different loot in different sides of the chest. But lootr keeps splitting into two chests.
