### ISSUE TITLE
Lootr chests can be opened when there is a block above it

### ISSUE THREAD

**Issue by ochotonida** [noobanidus/Lootr#18]
Unlike vanilla chests, Lootr chests can be opened when there is a full block above it. Some mods (iirc Apotheosis does this) place blocks such as spawners above chests, which should prevent the chest from being opened until the block is destroyed.

**Comment by noobanidus** [comment]
I swear I've fixed this, but it's possible that I just haven't pushed it yet. ... Yes, it took me *this* long to realise.

**Comment by noobanidus** [comment]
Yeah, this is fixed.
