### ISSUE TITLE
Compatibility between Lootr and Balloon Box request

### ISSUE THREAD

**Issue by katubug** [noobanidus/Lootr#181]
Hi! So I'm using this mod called [Balloon Box](https://www.curseforge.com/minecraft/mc-mods/balloon-box), which drops special chests which, when placed, turn into Lootr chests (because they use vanilla loot tables). In 1.19.2 (forge, if that matters), I can't set it to use custom loot tables. This can be a problem because it makes server loot super easy all of a sudden, and it also means that there will likely be random chests scattered around everywhere.

I know this is a very edge case, so if you're not able to help, that's totally fine! But is it possible to add a compatibility layer to prevent these chests from becoming Lootr chests? Help would be greatly appreciated! Thank you!

**Comment by noobanidus** [comment]
So looking at the data pack, the loot tables are formatted in a way that should make it easy to blacklist:

![](https://i.imgur.com/ffgUYOS.png)

You can add `balloonbox` to the list of blacklisted mod IDs in the configuration using [`loot_modid_blacklist`](https://github.com/noobanidus/Lootr/wiki/Lootr-Configuration). Changing the line to as follows should do it:

`loot_modid_blacklist = ["balloonbox"]`

**Comment by katubug** [comment]
Thanks, this worked!

**Comment by katubug** [comment]
Hi, sorry to bother, actually this didn't work for some reason. I didn't test it until just now >.>

**Comment by katubug** [comment]
https://i.imgur.com/NoJUUs8.png

Here's my config.

**Comment by katubug** [comment]
Scratch this, it is working. I don't know what I changed, but it's working.
