### ISSUE TITLE
[1.12] `LOOTABLE_TE_BLACKLIST` not working

### ISSUE THREAD

**Issue by Krutoy242** [noobanidus/Lootr#183]
I have this config:
```css
# list of blocks not to convert when the above option is enabled [default: bank, meaning convert all, format e.g. minecraft:chest]
S:LOOTABLE_TE_BLACKLIST <
  minecraft:dropper
  minecraft:dispenser
  iceandfire:desert_myrmex_cocoon
  iceandfire:jungle_myrmex_cocoon
  randomthings:specialchest
>
```

But `Pirate Ships` from `Quark` mod still spawning with Lootr chests instead of Dispensers:

![image](https://user-images.githubusercontent.com/936618/230571801-c0e031c5-35aa-4917-9f62-4661a5ad0808.png)

Same behavior with all other blocks in this list in different structures, from Mineshafts to Myrmex dens.

[debug.log](https://github.com/noobanidus/Lootr/files/11177320/debug.log)

**Comment by embeddedt** [comment]
These options were left in the port by accident and don't do anything on 1.12; sorry about that confusion. You should put the blocks in `ADDITIONAL_CHESTS` and enable `CONVERT_ALL_LOOTABLES_EXCEPT_BELOW` instead.

I will remove the options in the next release.
