### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by KostromDan** [noobanidus/Lootr#186]
[crash-2023-04-23_07.06.57-server.txt](https://github.com/noobanidus/Lootr/files/11304265/crash-2023-04-23_07.06.57-server.txt)

**Comment by KostromDan** [comment]
[debug-3.log.gz](https://github.com/noobanidus/Lootr/files/11304269/debug-3.log.gz)
[2023-04-23-4.log.gz](https://github.com/noobanidus/Lootr/files/11304270/2023-04-23-4.log.gz)

**Comment by KostromDan** [comment]
![image](https://user-images.githubusercontent.com/90044015/233853385-9aca9cb8-6820-4396-878f-cd18c4e2a96f.png)

**Comment by noobanidus** [comment]
I'm confused by these messages; are you saying that this issue only occurs when you have chunk pregenerator installed and you start the server?

If that is the case, Speiger is correct in saying that Lootr can be installed after; if there is some sort of conflict, disable Lootr, start your server with chunk pregenerator, pre-generate your chunks, then stop it, remove the pre-generator, and then enable Lootr.

The implication seems to be that there are so many block entities being added from the copy of entries that it's crashing at this point -- but the watchdog doesn't say how long it's spent on this task unfortunately.

If the suggested option doesn't fix it (disable lootr, enable chunk pregenerator, run chunk pregenerator, disable pregenerator, enable lootr), please get back to me.

**Comment by Diskman20** [comment]
I have the same issue on my server, attempting to open a lootr chest for the first time causes so much lag while generating the loot that the server crashes. I did use the chunky pregenerator to pregenerate the chunks.

**Comment by noobanidus** [comment]
@Diskman20 That's #172 and unrelated to Chunk Pregenerator.

**Comment by Diskman20** [comment]
ah, thank you
