### ISSUE TITLE
1.7.10 Support?

### ISSUE THREAD

**Issue by nishokurengecho** [noobanidus/Lootr#187]
It would be nice for there to be support for 1.7.10 considering there is support for 1.12.2.

**Comment by embeddedt** [comment]
This is unlikely to happen as 1.7 has no loot tables built-in. It would likely only be possible to backport the fallback mechanism used for 1.12 mods where a new copy of the same inventory is provided to each player.

**Comment by noobanidus** [comment]
Sorry, not happening.
