### ISSUE TITLE
Lootr + Mine Treasure - Visual Bug

### ISSUE THREAD

**Issue by muhammedesadcomert** [noobanidus/Lootr#188]
Mine Treasure barrels do not disappear visually when they are broken. This bug disappears only if I place a barrel in the broken barrel's position. I tested without Lootr, and there is no visual bug.

Also, if I save and exit the world without fixing the bug by doing the barrel thing (check the video), the game crashes with this [crash log](https://mclo.gs/mszdxUj).

_Although the problem seems to be only related to Mine Treasure, I opened an issue for both repositories thinking the problem might be related to Lootr as well._

Minecraft: `1.19.4`
Lootr: `0.5.26.66`
Mine Treasure: `1.2.7`

Logs: https://mclo.gs/QmczLKQ

A short video of the bug: https://youtu.be/SrwJDUVlk1U

**Comment by noobanidus** [comment]
This looks to be an issue with the client-side block entity not being deleted, I don't know if it has anything to do with Mine Treasure, although the associated crash report appears to be linked with Architectury, which Lootr doesn't use.

**Comment by muhammedesadcomert** [comment]
Ok, crash may not be related to Lootr or Mine Treasure, idk. So, how can I prevent Mine Treasure barrels from being converted by Lootr?

**Comment by finnglink** [comment]
I'm having the same issue. In my case, after death, quitting and reloading the game, ALL of the treasure loot chests simply reverted to Lootr barrels. So no crash for me so far, but pretty annoying visual bug.

**Comment by noobanidus** [comment]
At this point in time, Mine Treasures is just not compatible with Lootr. I'd recommend adding its mod id to the loot table blacklist.

**Comment by finnglink** [comment]
![Bildschirmfoto 2023-08-25 um 15 49 59](https://github.com/noobanidus/Lootr/assets/52720442/5b485c27-31fd-47b8-bb8d-2d5b71c3671f)

I've tried it like this, but the treasure chests still register as lootr barrels. Can the be cause by the fact, that MT acts as a resource pack, rather than a "regular" mod? I'm still a bit lost on how it all works in these newer versions.

**Comment by finnglink** [comment]
I've pulled the ID from the fabric.mod.json
""id":"mine_treasure_mr","

**Comment by noobanidus** [comment]
I'd recommend opening up the actual `.jar` file and determining what namespace the loot tables are contained in -- that namespace is what should be added to the `loot_modid_blacklist`.

**Comment by finnglink** [comment]
The file structure for the loot_tables folder is data/mt/loot_tables

Is that ID / namespace just "mt" then? Sorry, this goes a bit beyond what I usually do :D

**Comment by finnglink** [comment]
That did the trick!
