### ISSUE TITLE
Lootr chests not converting in 1.12.2 within the Rougelike Dungeons.  

### ISSUE THREAD

**Issue by Salamixx** [noobanidus/Lootr#190]
I have used lootr for a long time and we decided for our MINECRAFT SERVER to move down versions from 1.16.5 (Which gave u no issues) to 1.12.2, Which now gives us many problems. Going into the Cyclopse and medusa places you're able to find lootr chests but now when we go into the dungeons that actually have the major loot you cannot find them at all, you'll find regular vanilla chests. Is this a config error and if so how can we fix it?

**Comment by embeddedt** [comment]
https://github.com/noobanidus/Lootr/issues/132#issuecomment-1189042014

**Comment by Salamixx** [comment]
Where can I find out how to change that? I've looked in the server configs or am I blind LOL

**Comment by embeddedt** [comment]
Should be an option in `config/lootr.cfg`.

**Comment by Salamixx** [comment]
it didnt work :(

**Comment by embeddedt** [comment]
It will not work in already generated chunks; have you teleported to a brand new area to check?

**Comment by Salamixx** [comment]
We just did, we found some! it worked thank you!
