### ISSUE TITLE
[Suggestion] - Option to disable Lootr on world creation

### ISSUE THREAD

**Issue by Cadock** [noobanidus/Lootr#193]
As per title, it would be nice on world creation if an option was available to turn off/on Lootr, this would be really useful for single player worlds in mod packs that get updates. If the mod is deleted then if a modpack is updated then it gets downloaded again, but if there was an option to disable to mod per world/save then this would eliminate the need to constantly re-delete the mod.

**Comment by noobanidus** [comment]
A configuration value would potentially be overridden any time that a modpack updates, meaning that you would need to edit the configuration file each time you update the mod pack, which seems about on par with having to delete the mod.

Do you have a specific reason for not wanting to run Lootr in a single player world? There's an option to use Vanilla textures if the visual is the main driving factor.

**Comment by Cadock** [comment]
I appreciate the response, thank you!

I actually really like the texture of the Lootr chests, I mainly disable it though when I'm playing single player for things like dungeon runs, if I have a sophisticated backpack with a magnet upgrade then all I have to do is run around breaking chests and suck up all the loot. Whilst with Lootr even if you break the chest you lose the loot, so you have to manually open, loot and then open backpack and transfer items. 

Is it be possible to make the setting a save specific thing so it's not lost when the pack updates?
