### ISSUE TITLE
[Suggestion] "Uninstall" config option

### ISSUE THREAD

**Issue by chimericdream** [noobanidus/Lootr#196]
I saw in the FAQ that removing the mod will remove all Lootr chests from the world and had a suggestion. It wouldn't be perfect, but it might be better than nothing. What if you had a config that essentially reversed what Lootr does during world gen? What I mean is that it disables the function which replaces vanilla loot chests. Then as a second part, when the game loads a chunk into memory and that chunk contains an existing Lootr chest, it converts it back to a vanilla loot chest. Obviously it wouldn't be able to replace 100% of the chests (unless a server owner and/or player deliberately visited every chunk in their world), but even a small percentage is a nice bonus.

**Motivation / Rationale**
I have used Lootr in previous versions for awhile now, and _love_ it. However, my friends and I are starting a new server that we want to keep as close to vanilla as possible so that we can continue a single world for several years. I want to be able to plan for a future version (whether it's 1.21 or 1.30 or whatever) where Lootr may not be supported anymore. I'd like to be able to safely remove the mod at that point before moving to the next MC version.

**Comment by noobanidus** [comment]
I understand where you're coming from but an "uninstall" option isn't theoretically possible. The main issue is that Lootr, theoretically, doesn't keep track of all of the converted containers. While it would be possible to disable conversion, as well as to unconvert chests as they load, you would need to ensure that you load the entire world somehow...

I believe your best option would be to use something that interacts with the NBT to convert Lootr chests back into Vanilla chests: you could discard most of the information, convert the `special Loot Table` and `special Loot Seed` fields back into `LootTable` and `LootSeed`.
