### ISSUE TITLE
Lootr has failed to load up correctly.

### ISSUE THREAD

**Issue by samito782** [noobanidus/Lootr#199]
[crash-2023-06-20_17.55.42-fml.txt](https://github.com/noobanidus/Lootr/files/11804642/crash-2023-06-20_17.55.42-fml.txt)
[latest.log](https://github.com/noobanidus/Lootr/files/11804645/latest.log)
[lootr-common.toml.txt](https://github.com/noobanidus/Lootr/files/11804648/lootr-common.toml.txt)

Hello there,
I have been trying to play CurseForge Java 1.19.2 - 43.2.14 but Lootr doesn't load correctly and I don't know why.

I tried installing Lootr from here: [**https://www.curseforge.com/minecraft/mc-mods/lootr/files**] but it still doesn't load well and it displays this message in Minecraft: 'Lootr (lootr) has failed to load correctly java.lang.reflect.InvocationTargetException: null'

The one I installed was (lootr-1.19.2-0.4.23.60) from [**https://www.curseforge.com/minecraft/mc-mods/lootr/files/4465109**]
Above is the crash report, latest.log and I converted the lootr.common.toml into a .txt file. What should I do to overcome this issue?

Thanks for the attention.

**Comment by embeddedt** [comment]
Delete the Lootr config file entirely and relaunch.

**Comment by samito782** [comment]
> 

That worked, thank you.

**Comment by Haris2k7** [comment]
how to delete lootr config file entirely

**Comment by noobanidus** [comment]
Go into the config folder and delete the `lootr-client.toml` and `lootr-common.toml` files for Forge, or any other `lootr` file for Fabric.

**Comment by Haris2k7** [comment]
thanks
