### ISSUE TITLE
Texture issue with open chests

### ISSUE THREAD

**Issue by chimericdream** [noobanidus/Lootr#203]
The underside of an open chest's lid appears to be several of the Lootr textures stitched together. At first I thought it might be due to a resource pack I'm using (New Default+), but I see it without the pack enabled as well. Screenshots below.

![2023-07-09_00 39 51](https://github.com/noobanidus/Lootr/assets/198075/6f208c6f-0412-4a16-85c5-f48d4f33a3e8)
![2023-07-09_00 40 16](https://github.com/noobanidus/Lootr/assets/198075/105c377a-95b6-496c-897f-5a6305d8f3e6)

**Comment by noobanidus** [comment]
What version of Minecraft is this, and what version of Lootr?

EDIT: Additionally, what mod loader are you running?

**Comment by noobanidus** [comment]
![](https://i.imgur.com/hUZJrjC.png)

This doesn't appear to be happening in my development environment with Forge for 1.20.0. Are you running any other mods?

**Comment by chimericdream** [comment]
Whoops, sorry. This is Fabric, 1.20.1, and version 0.7.29.75 of Lootr. This is in a modpack, so there are other mods involved, yes. Off the top of my head, I don't know of any that would (in theory, anyway) affect the texture atlas like this, but if it is not happening with _just_ Lootr, I can do some digging to see where the incompatibility is.

**Comment by noobanidus** [comment]
If you have this problem still, please open a new issue.
