### ISSUE TITLE
I got 9 emeralds at just the start

### ISSUE THREAD

**Issue by yunus-cakir** [noobanidus/Lootr#204]
How can I reduce that?
![image](https://github.com/noobanidus/Lootr/assets/83448525/9fce3fbd-ff44-486c-a7a1-bb2f045e4e2a)
![image](https://github.com/noobanidus/Lootr/assets/83448525/a6da52c4-c7ff-4360-8285-1a180d479f32)

**Comment by noobanidus** [comment]
Please check the [Lootr](https://www.curseforge.com/minecraft/mc-mods/lootr) description on CurseForge. Specifically, this is answered by the following sections: *Q. How does Lootr generate loot?* and *Q. How do I change what loot is generated with Lootr? How do I include loot from other mods in Lootr containers?*.
