### ISSUE TITLE
Lootr stopped Minecraft from starting up

### ISSUE THREAD

**Issue by invizbleRope** [noobanidus/Lootr#206]
Everything was working fine until yesterday.  The server just won't start up not until this mod is removed. 

[latest.log.zip](https://github.com/noobanidus/Lootr/files/12058971/latest.log.zip)

**Comment by noobanidus** [comment]
Can you try deleting the Lootr config file? Otherwise I've never seen this bug before.

**Comment by invizbleRope** [comment]
Okay, removing the config file did not help, but removing the lootr mod and reinstall it back with my backup world did.  It is really strange!

Anyway, thank you for your help and thank you for creating this awesome mod.

**Comment by WilliamBlaze** [comment]
ah! good to know this now. I also recently ran into this issue, so I tried the suggestion of delete the configs and much to my surprise, it fixed my crash issues without needing to remove anything!
