### ISSUE TITLE
Can't /lootr custom trapped chests

### ISSUE THREAD

**Issue by theDerxu** [noobanidus/Lootr#209]
Doesn't exist on fabric 1.20.1, not sure about other versions.

**Comment by noobanidus** [comment]
There's no custom alternative for a trapped chest; I've added barrels in recent versions for conversion, but the idea is more to allow players to create their own chest. It's not really designed to be used as a tool.

Unless you want a custom trapped chest? I'm not sure of the use case here.

**Comment by theDerxu** [comment]
I would like one, as I am trying to get it to play a sfx when you use the chest but it needs to be trapped, either that or I mess with scoreboards which works too but I asume most arn't great with that so I thought it'd be nice for some.

**Comment by noobanidus** [comment]
Is it possible to just use a standard trapped Lootr chest with your own custom loot table, or do you need the functionality of "exactly the same items" that the custom chest provides?

**Comment by theDerxu** [comment]
I needed the exact, however I managed to set up a scoreboard to detect when loote chest opened then run commands off that but it'd be handy for extra things as that means every loote chest now runs these commands

**Comment by WilliamBlaze** [comment]
while slightly off subject here, i noticed that with lootR installed, mimics from the the Grimoire of Gaia 3 mod actually appear as unopened lootR chests prior to attacking the player, and then they still look like an unopened LootR chest, but with Teeth! - not sure how that works but i found it amazing. xD - honestly would have thought they stayed the same texture as standard chests or trapped chests even.  And on that note, I've never seen a LootR trap chest appear in my world generations before.

**Comment by noobanidus** [comment]
I believe Grimoire of Gaia 3 is currently being maintained by my friend @MrBysco, so that might be the case.

Likewise, Lootr trapped chests only generate in specific areas, like desert temples, etc. They have no visual difference from normal Lootr chests, however.

**Comment by noobanidus** [comment]
@TheDerpu0ne This is something I'll consider adding when I rewrite it.

**Comment by noobanidus** [comment]
Okay, so I've come up with a solution, it's a bit belated but there will be a config option in the next release for 1.20 (which will be backported to previous versions) that causes custom inventories to act like trapped chests when opened.
