### ISSUE TITLE
Duplication bug with Lootr chest in minecart

### ISSUE THREAD

**Issue by Andr0oS** [noobanidus/Lootr#21]
So far every Lootr chest minecart I've come across in Enigmatica 6 has reset its inventory to its initial state after closing the inventory, leading to infinite duplication of its dungeon loot.
1. 
![2021-02-21_17 36 27](https://user-images.githubusercontent.com/38390808/108647671-1e639780-746e-11eb-91e4-a952c7b231b3.png)
2. 
![2021-02-21_17 36 29](https://user-images.githubusercontent.com/38390808/108647680-258aa580-746e-11eb-8d8a-11e7c3979cfe.png)
3.
![2021-02-21_17 36 32](https://user-images.githubusercontent.com/38390808/108647692-2ae7f000-746e-11eb-9f6c-3c2931d6097c.png)

**Comment by noobanidus** [comment]
If you aren't using version 0.0.4.15, please report this to the Enigmatica 6 developers as they should update the version available in the pack. A fix for this was released over three weeks ago.
