### ISSUE TITLE
[1.12.2] Embers Rekindled Incompatability

### ISSUE THREAD

**Issue by terrarian10** [noobanidus/Lootr#215]
[debug.log](https://github.com/noobanidus/Lootr/files/12641817/debug.log)
[crash-2023-09-17_00.42.33-server.txt](https://github.com/noobanidus/Lootr/files/12641818/crash-2023-09-17_00.42.33-server.txt)
[latest (1).log](https://github.com/noobanidus/Lootr/files/12641819/latest.1.log)

This is a duplicate of #171 which was marked as resolved but I am still having this issue while playing.

**Comment by embeddedt** [comment]
Thanks, I think it should be fixed in 0.6.2.
