### ISSUE TITLE
issue when opening a chest

### ISSUE THREAD

**Issue by ZerausDG** [noobanidus/Lootr#216]
[crash-2023-09-04_18.00.47-server.txt](https://github.com/noobanidus/Lootr/files/12641936/crash-2023-09-04_18.00.47-server.txt)

**Comment by noobanidus** [comment]
This issue appears to be caused by another mod, I can't see Lootr anywhere in this code. 

```
	at baguchan.hunters_return.entity.Hunter.m_6518_(Hunter.java:400) ~[hunters_return-1.20.1-10.5.0.jar%23283!/:1.20.1-10.5.0] {re:classloading}
```

**Comment by ZerausDG** [comment]
thank you I will report it

**Comment by ZerausDG** [comment]
sorry wrong file 
[Uploading crash-2023-09-16_22.38.42-server.txt…]()
