### ISSUE TITLE
Missing textures with Faithless and entity_model/texture_features

### ISSUE THREAD

**Issue by JaxX27** [noobanidus/Lootr#219]
I think Faithless is one of the best Resourcepacks that I found, and so is FreshAnimations. To run FreshAnimations correctly I need to install entity_texture_features_forge and entity_model_features mod. The problem is that when i use them with the Faithless resourcepack, the Lootr chest loses their skin, and they look like a normal chest, making it impossible to notice a difference when im playing with my partner in a server.

Is there any way to look at it and try to find a solution?

Thanks in advance!

This is a Lootr chest with Faithless and the mods entity_model/texture_features installed:

![Screenshot_54](https://github.com/noobanidus/Lootr/assets/77545629/3f726676-44cb-4288-a577-45f5208cd43e)

**Comment by noobanidus** [comment]
This is a bit strange. Is this happening with the vanilla textures enabled in the client configuration, or without it being enabled?

It looks as though `entity_texture_features` is mixing in to the chest renderer and replacing the rendering code. I'm not entirely sure what it's doing or how best to prevent it.

**Comment by noobanidus** [comment]
If you're still having this problem, please respond or open a new issue.
