### ISSUE TITLE
Apotheosis Lootr incompatibility

### ISSUE THREAD

**Issue by krlenell** [noobanidus/Lootr#22]
Apotheosis adds chests beneath spawners throughout the underground.  These chests aren't being transformed into Lootr instanced loot chests.

**Comment by noobanidus** [comment]
Please see [issue #16](https://github.com/noobanidus/Lootr/issues/16) which lists compatibility requests that I've made, including one to Apotheosis (via Placebo). There's unfortunately nothing else that I can do from my side.
