### ISSUE TITLE
Server will Crash when opening specific chests in world

### ISSUE THREAD

**Issue by HPaoletti** [noobanidus/Lootr#220]
Hi! my friend is hosting a server and when we open a Lootr chest on a pirate ship the server will crash due to extended tick time. I will grab the logs when I can get them but certain chests will overload the tick (trying to generate the loot for the chest) and cause the server to shut down. Is there a way to resolve this on our end or would something need to be done to the modpack

**Comment by noobanidus** [comment]
Please see the pinned issue #172 as this is likely your issue.

**Comment by HPaoletti** [comment]
I will be sure to check it out! I appreciate the lighting response time. You are a beast and we love the mod. We have some chest hoggers on our server.

**Comment by HPaoletti** [comment]
I will attempt the Terralith FIX and will reopen if the maps are the problem. 

Again. **Thanks**

**Comment by noobanidus** [comment]
Definitely check out Async Locator, as well.
