### ISSUE TITLE
[1.20.1] Server crashes when opening Lootr chests 

### ISSUE THREAD

**Issue by fireIordazula** [noobanidus/Lootr#221]
My server stops whenever I open/break a Lootr chest and whenever I move the crosshair on the chest, it says "Inventory isn't generated". I've tried all compatible files for version 1.20.1 but still the same results :/ 

After I removed Lootr, some chests in the world opened fine. However, some chests also cause the server to crash now, specifically in generated structures like ruined portals, sunken ships, as well as in dungeons which is included in the Dungeon Crawl mod. 

Is there any solution for this? me and my friends would really like to have this mod on our server 

Here's the crash log if it helps:
https://mclo.gs/JDWqRYx

![2023-10-06_16 15 18](https://github.com/noobanidus/Lootr/assets/147140475/bd74fba4-da7f-4dbb-8d7d-2345cd0c71f5)

**Comment by noobanidus** [comment]
Please check #172

**Comment by fireIordazula** [comment]
Thank you for the quick response!

I just installed Async Locator and the old chests that caused the crash seem to have the same problem still, but I tried adding new Lootr chests and all of them opened with no problems. Hopefully newly generated chests we come across in the future won't have any issues. I'll let you know if I encounter any. 

Again thank you so much!

**Comment by noobanidus** [comment]
My bad, I didn't fully read through that. That looks to be another mod (Farmer's Delight) that is actually the issue here: it's adding the contents of another loot table to the original loot table, but gets stuck in an endless loop.

I'd recommend checking to see if you're running the latest version of Farmer's Delight and the correct version of Forge.

**Comment by fireIordazula** [comment]
Ahhh it is Farmer's Delight! I just installed the newest version and the chests opened. Thank you so much!
