### ISSUE TITLE
Barrels Play Closing Sound Immediately and Only Once

### ISSUE THREAD

**Issue by Toastr125** [noobanidus/Lootr#228]
Forge, version 1.19-0.3.20.57

When opening a lootr barrel for the first time, it plays the barrel opening sound as expected. However, it also plays the barrel closing sound immediately. The barrel's inventory remains open and it does not play the barrel closing sound when it is actually closed. After the first time, opening and closing both make no sound. Sculk sensors react accordingly - they only activate when the barrel is opened for the first time and don't activate when it is closed or re-opened. This doesn't happen with chests or shulker boxes, only barrels.

**Comment by noobanidus** [comment]
I'll look into this, thanks!

**Comment by noobanidus** [comment]
This will be addressed in the next 1.20 release and backported for other versions.
