### ISSUE TITLE
Shulker Boxes Have No Break Sound

### ISSUE THREAD

**Issue by Toastr125** [noobanidus/Lootr#229]
Forge, version 1.19-0.3.20.57

When broken (regardless of whether or not the player was sneaking), lootr shulker boxes do not play a sound. They still play a sound when the player is in the process of mining them, but finishing breaking them does not play the usual stone break/place sound. Unlike the barrel issue (#228), this is **not** reflected by sculk sensors - they activate when a lootr shulker box is broken nearby despite the lack of a sound. The barrels, chests, and minecart chests all play their proper sound when broken, the shulker box is the only one missing it.

**Comment by noobanidus** [comment]
This is because event `2001` which calls the `soundtype.getBreakSound()` isn't fired for some reason. Looking into it further.

**Comment by noobanidus** [comment]
This has been released for everything except Fabric 1.19.0.
