### ISSUE TITLE
Graveyard Mod Coffins

### ISSUE THREAD

**Issue by SafeOfArsenal** [noobanidus/Lootr#231]
they generate with loot but do not get effected by lootr

**Comment by Ricenami** [comment]
I also have the same thing happening, is there a way I could fix this on my end via datapack or config?

**Comment by marc-cwm** [comment]
Mine don't either, but how would that even work?
They're double chests and different, I think you'd need new art with like a 'lootr coffin'?  Something like a double chest?

The actual chests in Graveyard stopped working at some point too though, and I'd love to see those be fixed.

**Comment by noobanidus** [comment]
> The actual chests in Graveyard stopped working at some point too though, and I'd love to see those be fixed.

Which version of Minecraft and which launcher? That's something I can look into; do you know which specific structures are problematic? It looks like they're all encoded as part of the structure NBT.

**Comment by marc-cwm** [comment]
Sorry to the two commenters above for the hijack.

For the actual chests in Graveyard though:
We're using 1.20.1 with Prism Launcher / Forge 47.2.6
Graveyard is: "The_Graveyard_3.0_(FORGE)_for_1.20.1"
Lootr is: "lootr-1.20-0.7.30.73"

I don't know how to get you structure names/etc, but it seems to affect the actual buildings, Mausoleums/etc.  I assume it affects everything in Graveyard, i've never seen a working lootr chest in a graveyard structure.  What's the best way to get you the info you need?

**Comment by noobanidus** [comment]
After having played with this mod, I don't believe the coffins are designed to be converted. Any compatibility would need to be implemented as an add-on to Lootr (or as part of the Graveyard itself).
