### ISSUE TITLE
1.20.2 compatibility

### ISSUE THREAD

**Issue by MeeniMc** [noobanidus/Lootr#233]
Version for 1.20.1 is not compatible with 1.20.2 (fabric)

**Comment by noobanidus** [comment]
1.20.2 contains significant changes to the Minecraft code base.

Hence why the 1.20.0 version is only flagged with 1.20.1, not 1.20.2.

EDIT: If you're looking for a 1.20.2 port for Lootr, I haven't ported it yet.
