### ISSUE TITLE
[Feature Request] Unique Trapped Chest Texture

### ISSUE THREAD

**Issue by RyanSalad** [noobanidus/Lootr#235]
As far as I'm aware, there isn't a way to tell if a loot chest is trapped or not without using F3. I'm of the opinion that it'd be very helpful to be able to visually tell the difference between trapped and normal chests especially for non-vanilla dungeons/structures that utilize trapped chests more often and may be rigged to TNT.

**Comment by noobanidus** [comment]
I honestly had no idea there was a difference between the chest textures. I'm surprised nobody else has raised this issue. I'll see what I can do.

**Comment by noobanidus** [comment]
So, I've commissioned new textures; this will be available in Fabric for 1.20 shortly, and I'll be porting it to others.
