### ISSUE TITLE
idk the people in curseforge said its trying to get a file that doesnt exist in minecraft

### ISSUE THREAD

**Issue by uq6c** [noobanidus/Lootr#236]
<img width="773" alt="Screenshot 2023-11-04 at 9 15 11 PM" src="https://github.com/noobanidus/Lootr/assets/98590532/59a2aa5e-8c10-4aef-a021-c5480869e5f8">

[82QaGYQ.log](https://github.com/noobanidus/Lootr/files/13257426/82QaGYQ.log)

**Comment by embeddedt** [comment]
You're using the 1.18.2 version of Lootr on Minecraft 1.18.1.

**Comment by uq6c** [comment]
ok
