### ISSUE TITLE
Ancient city some chests convert to lootr and some remain vanilla on 1.20.1 heavily modded

### ISSUE THREAD

**Issue by amyfromearth** [noobanidus/Lootr#237]
All chests have loot table minecraft:chests/ancient_city and have different seeds. I can't find a rhyme or reason to why some are lootr and some are vanilla.

**Comment by noobanidus** [comment]
Can you check #226 to see if any of the suggestions there fix the issue? This problem sounds similar.

**Comment by amyfromearth** [comment]
That was my issue. I updated the config on my server and chests are converting to lootr as expected now. Thanks!
