### ISSUE TITLE
[Feature Request 1.19.2] Whitelist or Wildcard dimension matching

### ISSUE THREAD

**Issue by Saereth** [noobanidus/Lootr#238]
It would be useful if there was a way to set the dimension allow list to be a whitelist so all dimensions dont replace chests except the ones specified, OR allowing a wildcard in the dimension specification for blacklisting. This is particularly problematic for something like FTB Skies where the team dimensions have randomly generated names or RFTools dimensions which can have a random name but all are prefixed by ftbteamdimension: or rftoolsdimension: respectively. In this scenario the rftools dims and ftb sky dims wouldnt have lootr chests since they are already team specific, but the communal dimensions like the end/nether etc would.

**Comment by noobanidus** [comment]
Would a dimension modid blacklist work for you?

**Comment by noobanidus** [comment]
I've implemented modid whitelisting and blacklisting for dimensions and they're in the latest 1.19 release.

**Comment by Saereth** [comment]
awesome, ty so much!

**Comment by noobanidus** [comment]
Hopefully it makes sense! I don't know if the logic actually works at this stage; the whitelist is basically configured to be a "only allow these dimensions", whereas the blacklist just prevents specific dimensions. I've probably made it too complicated.
