### ISSUE TITLE
there is an imcompatibilty with this mod and immersiveMC 

### ISSUE THREAD

**Issue by jojofenin99** [noobanidus/Lootr#239]
here is an image 
![image](https://github.com/noobanidus/Lootr/assets/103892815/0d0af32a-5a14-4b01-bf8b-652a5f299f2c)

**Comment by jojofenin99** [comment]
the items are supposed to appear in a 3x3 grid and switch as you punch the chest

**Comment by jojofenin99** [comment]
but for some reason it's just empty

**Comment by jojofenin99** [comment]
also when you open the gui the items are there

**Comment by noobanidus** [comment]
If I understand what you're saying correctly, that would be a compatibility issue with the other mod, not something that I can fix or adjust with Lootr.
