### ISSUE TITLE
[1.12.2] Compat with Betweenlands shared loot tables

### ISSUE THREAD

**Issue by SeriousCreeper** [noobanidus/Lootr#241]
Heya,

in the Betweenlands, dungeons use a shared loot table, to ensure that certain loot is guaranteed inside a dungeon, by generating the loot and then spreading it across the available chests inside the structure. 

https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12-fixes/src/main/java/thebetweenlands/common/world/storage/SharedLootPoolStorage.java 

With Lootr installed, opening such a chest would re-roll the entire loot table for that chest. 

I know this is a very special case, but i was wondering if there could be some sort of compat for this. 

Potentially have a setting for the Lootr chest to copy what loot is currently in the chest it's replacing (even better if it's filtered by loot table ids, so it doesn't apply to every chest, but even that'd be fine), and then giving that same loot to any player opening the Lootr chest? It wouldn't randomize between players, but i think that's fine. 

Was going to attempt that with an addon, but have not quite gotten that to work, so figured i'll ask here as well. 

Cheers,
SC

**Comment by noobanidus** [comment]
I don't really know how the 1.12 works, but I assume that it's very similar to 1.16 and later. Lootr does have a similar capacity but I'm not sure how it would work in this case, as, with the chests already being converted, it has no access to the original tile entity in order to use that `fillWithLoot` variant.

Honestly, compatibility would be quite difficult...

**Comment by SeriousCreeper** [comment]
Yeah i think you are right, i've looked into this quite a bit now, and i don't think it's gonna way too big of a task. 

I'll close the ticket for now :)

**Comment by noobanidus** [comment]
The simplest option I can think of would be to use the most recent Lootr API -- but I'm not sure how that would work in 1.12.2. Then you could provide your own loot table fill method.
