### ISSUE TITLE
crashes once opening

### ISSUE THREAD

**Issue by KrysisUchiha** [noobanidus/Lootr#242]
[latest (1).log](https://github.com/noobanidus/Lootr/files/13689941/latest.1.log)

**Comment by KrysisUchiha** [comment]
when ever i try to loot a lootr chest it crashes

**Comment by noobanidus** [comment]
This is an issue with Bukkit; once again they have injected a method into `Container`. For something similar please check out #225 

There's not really anything I can do about this apart from recommending that you try something other than CraftBukkit.
