### ISSUE TITLE
[1.12.2 Forge] Crashing on startup due to "Found FMLCorePluginContainsFMLMod marker"

### ISSUE THREAD

**Issue by Tw1ZZLER** [noobanidus/Lootr#243]
Minecraft 1.12.2
Forge 14.23.5.2859
Lootr 0.6.2

I am creating a [modpack](https://www.curseforge.com/minecraft/modpacks/the-brilliant-expanse) with the following mods:
[modlist.txt](https://github.com/noobanidus/Lootr/files/13749636/modlist.txt)

Recently, when I enable Lootr, the modpack fails to start. It works perfectly fine without Lootr. 
Here's the `latest.log`:
Client:
[latest.log](https://github.com/noobanidus/Lootr/files/13749650/latest.log)

Server:
[latest.log](https://github.com/noobanidus/Lootr/files/13749647/latest.log)

It seems like the error is caused by the following:
```
[02:44:15] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in lootr-1.12.2-0.6.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:44:15] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at /home/tw1zzler/.local/share/PrismLauncher/instances/The Brilliant Expanse/minecraft for Forge Mod Loader
```

Let me know how else I can help solve this issue.

**Comment by noobanidus** [comment]
Please install MixinBooter as outlined on the CurseForge page multiple times.

EDIT: To clarify, if you read further through that crash report you'll see what the issue is: 

```
Caused by: java.lang.NoClassDefFoundError: zone/rong/mixinbooter/IEarlyMixinLoader
```

**Comment by Tw1ZZLER** [comment]
That was incredibly stupid of me, I'm really sorry for wasting your time. Thank you.
