### ISSUE TITLE
Possible to reset all advancements on a server?

### ISSUE THREAD

**Issue by AnyankaT** [noobanidus/Lootr#244]
I'd like to clear all the advancement information for my server, and remove all the past information about which players have opened particular chests, so that they are all "new" again.

Can I do this by simply deleting the Lootr-AdvancementData.dat file? Or to I have to go in-world to each chest and reset it?

**Comment by FullMetalMaster** [comment]
having this issue but I want to know how to reset, per player data for loot chest as well

**Comment by noobanidus** [comment]
To reset the per-player data for a single chest, you can delete the relevant data file for it. This data file is contained in the `world/data/lootr` folder, in the subfolder consisting of the first character of the chest's ID, and a subfolder of that consisting of the first two characters of the chest ID, etc.

You can find the specific chest ID by standing on it in game and executing the operator command `/lootr id`.

Alternately, if you want to clear all of the chests, you can just delete all of the subfolders.

With regards to the advancements: the advancements grants are tracked through the aforementioned `AdvancementData` file; deleting this, however, will not remove the advancement entirely, as you will still need to use the Minecraft `/advancement` command to revoke the relevant advancements.
