### ISSUE TITLE
Chest loot dont appear

### ISSUE THREAD

**Issue by cavaloimortal** [noobanidus/Lootr#245]
cant see the chest loot but other ppl can see it.

i already tried clean up my data and more things and remains the same

https://github.com/noobanidus/Lootr/assets/109184177/8bbf4628-76da-437a-87c2-57c693fd0f5a

**Comment by noobanidus** [comment]
Unfortunately I need some more information and perhaps some logs.

It is possible that, for some reason, these loot tables are corrupted and are producing no output. 

Can you include the `latest.log` or `debug.log` from your server when you open these chests? Is it only chests in the ancient city?

Likewise, what version of Minecraft specifically, what mod loader and what version of Lootr are you using?

**Comment by noobanidus** [comment]
If this is in the All of Fabric 7 modpack, please be aware that it is a known issue: https://github.com/TeamAOF/All-of-Fabric-7/issues/9 (see #249).

If this is from a different modpack, please reply with some more information including the log files mentioned in my previous comment, and I will re-open the issue.
