### ISSUE TITLE
[1.20.1] Crash on world generation

### ISSUE THREAD

**Issue by MokahTGS** [noobanidus/Lootr#246]
Getting a crash when trying to generate a new world:

https://pastebin.com/knYfeSHs

and also

https://pastebin.com/ngMfzgie

**Comment by noobanidus** [comment]
I've never seen this issue and it confuses me slightly, as it appears to indicate that the server is not accessible at this stage. Are you experiencing this with just Lootr installed, or only when combined with other mods?

**Comment by MokahTGS** [comment]
This is part of a modpack.  This is the first time I've ever seen this as well and have been running this modpack for months.

https://legacy.curseforge.com/minecraft/modpacks/cosmic-magitech

**Comment by noobanidus** [comment]
Can you post the full `latest.log` for world initialization? I've dug a little deeper into the second report and it appears as though `getDataStorage` is returning null, in addition to the `getCurrentServer` hook also returning null. This seems to indicate that there are significant problems with the server state, implying there might be other issues causing the server to be in an error state before it reaches this point.

**Comment by noobanidus** [comment]
This will be addresses in the upcoming release for 1.20.0, which adds a vast amount of null checks to ensure that `doDecay`, etc, never attempt to operate when `MinecraftServer` or `MinecraftServer::overworld` are null.
