### ISSUE TITLE
[Crash]: Invalid Player Data - Aged Modpack 2.1.2

### ISSUE THREAD

**Issue by xR4YM0ND** [noobanidus/Lootr#247]
https://github.com/xR4YM0ND/Aged/issues/33

**Comment by noobanidus** [comment]
There is something more at issue here; it's been reported before and in all instances I haven't been able to determine the actual cause, but basically the Minecraft `server` instance's `overworld` method is returning null. 

If it weren't for this being on Fabric, I'd say that it's the same issue as whatever is causing #246 

Unless there is some sort of race condition where the event handler is being fired before the overworld is constructed, I'm not sure what else could be the issue -- from my understanding of things, the overworld is constructed at the same time as the server and should never be null at any point -- unless the event is somehow triggering before the server is fully constructed...

**Comment by noobanidus** [comment]
This will be addressed with the new series of null checks added in 1.20.0.

**Comment by noobanidus** [comment]
The most recent version of Lootr for Fabric 1.20.0 has just been released; the back port to 1.19.0 will happen in the next few days. I'll be uploading the new versions to Modrinth in bulk after that has happened, but it's available on CurseForge now for testing/debugging purposes.
