### ISSUE TITLE
[suggestion]Redstone activation when opening lootr chests

### ISSUE THREAD

**Issue by jinkhya** [noobanidus/Lootr#25]
Hello, in some dungeons, chests have tnt under them, lootr chests do not currently trigger tnt when opened. I thought it'd be cool if it reproduced the vanilla behavior.
Thanks !
Jin

**Comment by noobanidus** [comment]
This was fixed in the latest released version. Please try updating to that and if there's still an issue, comment here and I'll re-open the issue.
