### ISSUE TITLE
[1.20.1] quark chest variants of the lootr chests have missing textures

### ISSUE THREAD

**Issue by auriclion** [noobanidus/Lootr#250]
quark chest variants of the lootr chests have missing textures, including both the locked and regular variants. shows up black and magenta on rei.
<img width="377" alt="Screen Shot 2024-01-17 at 3 51 39 PM" src="https://github.com/noobanidus/Lootr/assets/131563906/c0c08fc6-d3ae-4ecf-8568-2f377d1631d4">

this is with the new quark beta, i can just disable lootr for now, it's not a mandatory mod for my pack but this is the issue i've run into. the regular lootr chests work just fine, so i know this is with quark.

unsure what other info you might need, but here's the changelog as well.

https://mclo.gs/HedwxdC

**Comment by auriclion** [comment]
quark has fixed this now, thank you!

**Comment by noobanidus** [comment]
As you noted, Quark does its own compatibility with Lootr, which means there's unfortunately nothing I can do to assist.

**Comment by auriclion** [comment]
> As you noted, Quark does its own compatibility with Lootr, which means there's unfortunately nothing I can do to assist.

that's okay, thank you!
Have a good night
