### ISSUE TITLE
Treasure maps never appear

### ISSUE THREAD

**Issue by EthanDangerous** [noobanidus/Lootr#251]
For some reason, I have never been able to find a buried treasure map after looting dozens of shipwrecks. There are some other mods but I'm 90% sure it is this mod that causes it.

**Comment by noobanidus** [comment]
Lootr does not alter loot tables in any way, as noted on the CurseForge description page which outlines the most frequently asked questions, so it is most likely not responsible for this.

You can test this by creating a single-player creative world of your pack *with Lootr disabled*, and then open containers in shipwrecks to see if you can find maps.
