### ISSUE TITLE
1.20.2 support

### ISSUE THREAD

**Issue by Cuteistfox** [noobanidus/Lootr#252]
jsut reminding you that 1.20.2 exists and you should update it (when realseing the fabic version remmber to mark it as compatible with quilt on modrinth so it auto updates on thesus(modrinth launcher) (the qfapi has updated to 1.20.2 !))

**Comment by noobanidus** [comment]
As 1.20.4 is available, there are no plans to release for 1.20.2 for either Forge, NeoForge or Fabric.

**Comment by Cuteistfox** [comment]
i guess i will wait for qfapi to update to 1.20.4
