### ISSUE TITLE
/lootr custom

### ISSUE THREAD

**Issue by willtarax** [noobanidus/Lootr#26]
When creating a lootr chest with supplies, I find that if anyone removes inventory from the chest, the next person to open it finds an empty chest, even if they have never opened it before. Tested this in multiplayer with two other players and myself. 
Recreate as follows
1) Place standard MC chest (doesnt seem to work with modded chests, not a big deal, but something else I noticed)
2) Fill that chest with loot
3) Use command /lootr custom
4) Have player two and three look in chest
5) Have player two take all inventory from chest
6) Have player three check chest to see it is empty
7) Open chest yourself (changing it from gold to silver) to see there is nothing in the chest

**Comment by noobanidus** [comment]
Thanks for the detailed description! I'll have to look into why this isn't working.

Re: point 1, this *is* true and specifically the case as there's no certain way to handle another chest easily, plus the sizing issues.

**Comment by noobanidus** [comment]
This was fixed in the most recent release, apologies for the delay.
