### ISSUE TITLE
Looted Chest looks Gold When Picked Up

### ISSUE THREAD

**Issue by Yourname942** [noobanidus/Lootr#28]
Minecraft 1.16.5
Forge 36.0.46
Lootr 1.16.4-0.0.4.16
Carryon 1.16.5-1.15.3.13

If you open a chest (turning the chest blueish) if you then pick up the chest using the mod Carryon it looks unopened. I have not tested this with barrels, but I am assuming it would do the same thing.

![2021-03-25_18 22 45](https://user-images.githubusercontent.com/58750222/112551355-43159c80-8d97-11eb-81e5-d5282f9dc8e3.png)

![2021-03-25_18 22 39](https://user-images.githubusercontent.com/58750222/112551363-4577f680-8d97-11eb-86d8-e388ba77f3c7.png)

**Comment by noobanidus** [comment]
There's absolutely nothing I can do about the chest renderer in this instance, sorry.

And honestly, anything involving Carry On or chest movers is super-edge case. That I've fixed the dupe bug and added some mild support is about the extent of how far I'm willing to bend over backwards for it.
