### ISSUE TITLE
More Notification Configuration

### ISSUE THREAD

**Issue by ChloeDawn** [noobanidus/Lootr#284]
I would like to be able to change the formatting and color of refresh and decay notifications, optionally also having them be action bar messages or titles instead of chat messages. Additionally (but lower priority) it would be great to have KubeJS events for these interactions so I could, for example, have a custom GUI appear as the notification.

**Comment by noobanidus** [comment]
Can you expand more on what you want with regards to formatting? The colour can most likely be configured, but I'm not sure what you mean by formatting.

If you mean the actual test, these are outsourced to translation keys, so you can adjust the text to have it read whatever you'd like.

**Comment by ChloeDawn** [comment]
I forgot you could use formatting codes in translation strings. It's just the color that I would like migrated then, it would be great if that could be moved to the translation string instead of hardcoded so that it can be changed.

**Comment by noobanidus** [comment]
I'm not too keen on including colour or formatting codes directly in the translation strings as it may cause confusion when translating, especially since we've moved to the automated CrowdIn system.

That said, I'm happy to include a configuration option that disables all formatting and thus allows you to create a resource pack that adds the formatting yourself.

**Comment by noobanidus** [comment]
This is implemented in 1.20.0/1.20.1 for Minecraft Forge. I'm in the process of back-porting to 1.19 and I'll update. I'll go as far back as 1.18.2 for Forge. For Fabric, I will most likely only do 1.19, 1.20 and 1.20.4.

**Comment by noobanidus** [comment]
Now available for Forge for 1.18.2.

**Comment by noobanidus** [comment]
This is done for Fabric, although I haven't forward-ported for NeoForge yet.
