### ISSUE TITLE
Minecarts Always Show Sneaking Message

### ISSUE THREAD

**Issue by ChloeDawn** [noobanidus/Lootr#292]
**Loader version:** NeoForge 47.1.99
**Mod version:** [0.7.31.76](https://modrinth.com/mod/lootr/version/0.7.31.76)

When `disable_break` is enabled in the configuration, minecarts with loot chests still show the `lootr.message.cart_should_sneak` and `lootr.message.should_sneak2` messages instead of the `lootr.message.cannot_break` message.

**Comment by noobanidus** [comment]
This has been released for Forge for 1.20 and will shortly be released for 1.19. I'll update this when released for other versions and mod loaders.

**Comment by noobanidus** [comment]
This is in the latest version for 1.19.

**Comment by noobanidus** [comment]
Now available for Forge for 1.18.2.

**Comment by noobanidus** [comment]
This is done for Fabric, although I haven't forward-ported for NeoForge yet.
