### ISSUE TITLE
Issue with Barrels

### ISSUE THREAD

**Issue by mahjerion** [noobanidus/Lootr#3]
Hey liking the mod so far! Just an issue with barrels - players on my server have been reporting that closing and opening the barrel "refreshes" the loot and thus generates infinite loot. It doesn't happen with regular chests.

We're on 1.15.2. No logs that I can really send, nothing shows up regarding Lootr :S

A list of the mods: https://www.curseforge.com/minecraft/modpacks/crafttoexiledissonance/files/3043646

There is riddle chests installed but would it affect barrels?

**Comment by noobanidus** [comment]
Hm, I'll triple-check the code, it's possible that there's something preventing the containers from saving properly when they close, thus meaning that the loot isn't actually "saved" and resulting in it refreshing the next time things are opened.

It's more likely that I'm conflicting with Riddle Chests than the other way around, to put it lightly. I need to look into it further.

**Comment by mahjerion** [comment]
Thanks for getting back to me. Sounds good, I'm hopeful you can fix it!

**Comment by noobanidus** [comment]
@mahjerion Okay, it looks like it has *nothing* to do with Riddle Chest or something preventing containers from saving properly and me forgetting the the "open" and "close" states of the barrel are *technically* different blocks and thus are considered a replacement... so it wipes the inventory.

Should have a release out that fixes this sometime soon.

**Comment by mahjerion** [comment]
Haha great to hear that you solved the issue!
