### ISSUE TITLE
[1.16.5] Quarries cannot mine Lootr Chests

### ISSUE THREAD

**Issue by NielsPilgaard** [noobanidus/Lootr#30]
Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/1927#issuecomment-814724672

When the RFTools Builder Quarry tries to mine a Lootr chest it fails, and halts on that chest. Perhaps allow fake players to break Lootr chests without holding shift would be an option? :)

### Versions
- lootr-1.16.4-0.0.4.16
- rftoolsbuilder-1.16-3.0.16

**Comment by noobanidus** [comment]
I believe this was resolved with the "skip unmineable blocks" option.
