### ISSUE TITLE
COMPAT: Using Looter with the Aether makes mimics obvious

### ISSUE THREAD

**Issue by Bigjango13** [noobanidus/Lootr#302]
The Aether has a few dungeon type structures, and in them are normal chests and mimics. The mimics are supposed to look like normal chests and surprise the user when they come to life, but because lootr changes the texture of normal chests they are easy to tell a part.

**Comment by noobanidus** [comment]
Unfortunately that's something that Aether would have to change on their end, although a separate mod that mixes in to their entity could also do it. 

The Artifacts mod features compatibility for Lootr in this fashion.

**Comment by noobanidus** [comment]
It looks like Aether are already on the case with this: https://github.com/The-Aether-Team/The-Aether/pull/1909

I'd suggest checking out their discord for more support.
