### ISSUE TITLE
[FEATURE REQUEST] Support for item frames

### ISSUE THREAD

**Issue by dhouck** [noobanidus/Lootr#303]
I know this is ordinarily outside the scope of what lootr would support, because they don’t have loot tables. 
 But it seems like it should work in custom inventory mode, and they are one of the biggest sources of contention in vanilla structure looting.

In vanilla the only naturally generating item frames are the Elytra ones that inspired the issue but in mods they can be for loot or decoration.   Not sure what the default should be but having it configurable based on the the item seems like the best option.

**Comment by noobanidus** [comment]
I have been considering this for a while and I've yet to decide what the best alternative would be.

As it stands, the item frame itself is handled in code, and it would be possible to mixin to that and replace the item frame with simply a Lootr chest. I'll loook into it further to see what solutions there are.

**Comment by noobanidus** [comment]
So this is now implemented in all the versions released for Forge.

**Comment by dhouck** [comment]
Cool!

Iʼm on Fabric so that wonʼt help me yet, but glad itʼs there for the Forge people, and if it becomes an issue thereʼs already the option to make your own chest somewhere.

**Comment by noobanidus** [comment]
Oh, to clarify: I'm removing the item frame and placing a chest which is guaranteed to contain an elytra.

**Comment by noobanidus** [comment]
This is available for 1.18.2, 1.19.0/1.19.1/1.19.2 and 1.20.0/1.20.1 for Forge and 1.20.4 for NeoForge.

**Comment by noobanidus** [comment]
This is now available for 1.20 on Fabric. I won't be back-porting to 1.19 Fabric.
