### ISSUE TITLE
[FEATURE REQUEST] Lootr Barrel to be able to turn Villagers into Fishermen

### ISSUE THREAD

**Issue by AdikaraAdnan** [noobanidus/Lootr#306]
Since Lootr Barrels replace World generated Vanilla Barrels, Villagers couldn't turn into Fishermen without the player interfering. I think this mod could be much improved if both Lootr Barrels and Vanilla Barrels could give Villagers the Fisherman profession.

**Comment by noobanidus** [comment]
This is now live for Forge for 1.18.2 and 1.19.0/1.19.1/1.19.2.

**Comment by noobanidus** [comment]
Now live for Forge for 1.20.0 and 1.20.1, and live for NeoForge for 1.20.4.

**Comment by noobanidus** [comment]
This is also live for Fabric for 1.20.0. I will not be back-porting these changes to Fabric 1.19.
