### ISSUE TITLE
Protection rules against breaking Lootr chests don't affect mob griefing

### ISSUE THREAD

**Issue by GoldenFurredFox** [noobanidus/Lootr#308]
In 1.20.1 running version 1.20-0.7.30.77 if you have lootr chests in the world and your config prevents players from breaking chests by accident by telling them to crouch first, lootr chests/barrels/shulkers can still be blown up by creepers and lootr barrels can still be picked up/moved by endermen, which ends up breaking their NBT data tags and empties them for all subsequent users who open the barrel after the enderman sets it down.

This should not be the case. Please fix this.

**Comment by noobanidus** [comment]
You can enable two different types of blast resistance (or immunity) in the configuration, which should protected them from being destroyed by creepers and TNT.

I'll look into how endermen are handled; I was unaware that they moved chests.

**Comment by noobanidus** [comment]
From what I can gather, this is an issue with either a datapack or a mod that is changing Vanilla tags (specifically the block tag `minecraft:enderman_holdable`). 

By default these are the only blocks that an enderman is supposed to pick up: 

```java
      this.tag(BlockTags.ENDERMAN_HOLDABLE).addTag(BlockTags.SMALL_FLOWERS).addTag(BlockTags.DIRT).add(Blocks.SAND, Blocks.RED_SAND, Blocks.GRAVEL, Blocks.BROWN_MUSHROOM, Blocks.RED_MUSHROOM, Blocks.TNT, Blocks.CACTUS, Blocks.CLAY, Blocks.PUMPKIN, Blocks.CARVED_PUMPKIN, Blocks.MELON, Blocks.CRIMSON_FUNGUS, Blocks.CRIMSON_NYLIUM, Blocks.CRIMSON_ROOTS, Blocks.WARPED_FUNGUS, Blocks.WARPED_NYLIUM, Blocks.WARPED_ROOTS);
```

I'd suggest looking through other mods which may change how endermen carry blocks, as this is not something that Lootr changes. Indeed, that they are picking up chests at all is extremely problematic, as endermen do not persist any of the block entity NBT.

EDIT: Accidentally hit "close and reply" rather than just "reply".

**Comment by GoldenFurredFox** [comment]
It was actually a script from kubejs that added the barrel automatically to the tag as it attempts to add compatibility for modded variants of already pickable blocks and since the vanilla barrel is pickable it caught the lootr one. The staff team on the server apparently already fixed it a few days ago by adding the lootr barrel to the blacklist. I'll inform the staff of the config option too though.

**Comment by noobanidus** [comment]
Vanilla barrels aren't pickable by default, as mentioned above; endermen picking them up would destroy them and cause their contents to either spill out or be lost. It sounds like a bit of a dangerous option -- unless you have a mod that specifically handles containers like this.

**Comment by GoldenFurredFox** [comment]
Yeah, we have another kubejs script that essentially disables the recipe for shulker boxes and makes barrels keep their NBT when broken, which also makes them safely pickable by endermen and makes them act like cheap shulkers.
