### ISSUE TITLE
[Compat Request] Trails and Tales +

### ISSUE THREAD

**Issue by DanteTooMayCry** [noobanidus/Lootr#309]
"Trails and Tales +" introduces a new type of spawner (Chamber Sprawner) that allows to obtain keys (Chamber Keys) for new type of chests (Chamber Chest). This is a very good mod, introducing a huge amount of content that true deserves for compatibility.

https://www.curseforge.com/minecraft/mc-mods/trails-and-tales

**Comment by noobanidus** [comment]
Compatibility would have to be implemented in this mod; you would be best to file a request on their issue tracker.
