### ISSUE TITLE
Can see chests through the wall

### ISSUE THREAD

**Issue by agentwolf88** [noobanidus/Lootr#31]
If I come closer to a chest i suddenly can see it through the wall. Is this a bug?

![2021-04-11_21 47 07](https://user-images.githubusercontent.com/9948479/114319161-8babb480-9b10-11eb-8171-ee192e3f7976.png)
![2021-04-11_21 47 19](https://user-images.githubusercontent.com/9948479/114319167-8f3f3b80-9b10-11eb-80dd-4b9af79f58c6.png)
![2021-04-11_21 47 42](https://user-images.githubusercontent.com/9948479/114319173-9108ff00-9b10-11eb-8fd9-0892c19983f7.png)

**Comment by noobanidus** [comment]
Which version of Minecraft is this, and do you happen to be running any other mods that alter chests?

From what I can see it looks as though the chest is being rendered inverted... and I'm not sure of anything in Lootr that would cause this.

**Comment by agentwolf88** [comment]
The problem is the mod "ModernUI" + "Optifine".

Fix: Change in client.toml of the ModernUI Mod "globalRenderer" to false.

**Comment by noobanidus** [comment]
Ah, thanks.
