### ISSUE TITLE
Forge 1.20.1 Minecraft Crash Java 17

### ISSUE THREAD

**Issue by vnsmnn** [noobanidus/Lootr#313]
Hi, it seems like my server is crashing because of this mod. Previously, I didn't really have this issue, but all of a sudden my server is crashing. When deleting the mod, this fixes the issue, but when putting it back, the issue persist.
[crash-2024-03-18_17.15.56-server.txt](https://github.com/LootrMinecraft/Lootr/files/14642915/crash-2024-03-18_17.15.56-server.txt)

**Comment by noobanidus** [comment]
I've never seen this crash before and I'm not sure how it's come about for you; potentially there's been some sort of data corruption in your world.

What's happening is that, while trying to save the `ChestData` for the level, the `uuid` of one of these data files is `null`. The `uuid` comes from the chest itself, and is always generated when one isn't present. But for some reason, when the chest's data file was created, the `uuid` that was passed into it was null.

I'm going to add some additional protection for this (when new data files are created), as well as some logging for when it tries to save with a null ID (preventing the crash), but unfortunately none of this will necessarily fix your world, as the actual chest data is corrupt.

Do you happen to have the `latest.log` file from when this crash occurred? I'd like to see if there's some more information before it got to this point.

**Comment by noobanidus** [comment]
Actually, here's a custom build: [lootr-1.20-0.7.32.79.jar.zip](https://github.com/LootrMinecraft/Lootr/files/14645755/lootr-1.20-0.7.32.79.jar.zip)

Please rename it from `.jar.zip` to `.jar` and replace the version of Lootr on your server in the mods folder with this file. It will likely still cause an error, but it will give you exact information as to which dimension and at what block position the "broken" container exists.

From that information it should be possible to determine the chunk location and dimension region file, which can then, theoretically, be edited to remove the broken tile.

**Comment by vnsmnn** [comment]
Hi thank you for looking into this. I'll follow the instructions you outlined and see if this fix the issue. Thank you so much!

**Comment by noobanidus** [comment]
Did this build resolve the issue for you?

**Comment by noobanidus** [comment]
I've made a release for Minecraft Forge for 1.20 containing this fix and I'm in the process of back-porting to 1.19. I'll update this when it's released for other versions.

**Comment by vnsmnn** [comment]
Hi thank you for keeping me updated. I'm sorry I wasn't able to update this post as I was very bust these past few days. Seems like the custom build work since my server didnt crash anymore. I also see that theres a new update ill go ahead and try this new build also. Appreciate your work thank you so much!

**Comment by noobanidus** [comment]
Now available for Forge for 1.18.2. The release for 1.19.2 is already done.
