### ISSUE TITLE
Twilight Forest compat

### ISSUE THREAD

**Issue by leyxcx** [noobanidus/Lootr#32]
I don't know if it's too early in the TF mod development for you to do this, but chests in structures don't seem to be replaced with lootr chests. Might not even be on your side, thought i'd report it anyway
![2021-04-26_17 48 37](https://user-images.githubusercontent.com/67163463/116034594-a6a52980-a6b7-11eb-930f-3475c125abdb.png)

**Comment by noobanidus** [comment]
As there are no longer going to be releases for 1.16.5, this will have to be delayed until the 1.17.1 release of Lootr, which is still waiting on mixins.
