### ISSUE TITLE
Lootr Failed To Load Correctly

### ISSUE THREAD

**Issue by BlueAxolotl1** [noobanidus/Lootr#325]
I was playing a modpack and randomly whenever i open my game it gives me this error and crashes other players using the modpack can still launch correctly i have tried reinstalling multiple times as well

![image](https://github.com/LootrMinecraft/Lootr/assets/146803183/0b9f4844-39c6-46bb-ae13-bee40ea7fb25)

https://mclo.gs/XbR7f3a

**Comment by noobanidus** [comment]
Please delete the `lootr-common.toml` and `lootr-client.toml` files from the `config` folder; for some reason they've become corrupted.
