### ISSUE TITLE
Possibly conflicts with Mimic type entities from other Mods

### ISSUE THREAD

**Issue by Lerrycapetime** [noobanidus/Lootr#327]
Greetings! I think this mod might conflict with Mimic Chests from twilightforest-1.20.1-4.3.2145-universal and artifacts-forge-9.3.0
If you can't reproduce this glitch, I'll do some more looking into it and report back on it.

Lootr version. lootr-forge-1.20-0.7.33.83.jar

**Comment by noobanidus** [comment]
This is purely an issue with Artifacts, although it is caused by the fact that I changed the texture locations for where the chest materials.

However, you can update to Artifacts 9.3.1 (released yesterday) for a fix.

**Comment by Lerrycapetime** [comment]
Ah I see, Thanks a ton for the quick response and cool mod!
