### ISSUE TITLE
lootr crashes world pre-gen with canary/chunky

### ISSUE THREAD

**Issue by Jadan1213** [noobanidus/Lootr#329]
Forge: 47.2.17
MC: 1.20.1
Lootr: 0.7.31.78

[Crash log](https://gist.github.com/Jadan1213/ea3196e20b824315409517608a82332c)
[latest.log](https://gist.github.com/Jadan1213/f02e2cb5e0fa81ad1010652ed26fd9f2)

This issue did not occur prior to adding lootr. Prior to adding lootr, i had pregenerated a 10,000 block radius with no errors. After adding lootr, I reset the world (same seed, same mods) and tried to pre-gen the first 1,000 blocks radius. The server hung around 82%.

**Comment by Jadan1213** [comment]
I also tried to pre-generate without canary, and i still get the tick hanging crash

**Comment by RyanSalad** [comment]
Now don't quote me on this but I believe I heard @noobanidus mention in the past that there's often issues with pre-generating chunks with Chunky, and if I recall correctly has advised others to disable Lootr during pre-gen and reenable it after you're done

**Comment by noobanidus** [comment]
Yep! However, I'm currently in the process of trying to get CurseForge publishing to work with my Fabric environment; it seems to be uploading the wrong jars at the minute however...

**Comment by noobanidus** [comment]
This should be resolved with the latest release for Fabric for 1.20. I will not be backporting the code changes to 1.19 and recommend people use the "disable" configuration option when using Chunky or another chunk pregenerator on 1.19 with Fabric.

**Comment by Jadan1213** [comment]
> Now don't quote me on this but I believe I heard @noobanidus mention in the past that there's often issues with pre-generating chunks with Chunky, and if I recall correctly has advised others to disable Lootr during pre-gen and reenable it after you're done

Yeah noobanidus and i spoke about this in the discord. I left the logs up here in case they'd be helpful =)
