### ISSUE TITLE
removed lootr, broke loot, will putting it back fix it?

### ISSUE THREAD

**Issue by MistyPower** [noobanidus/Lootr#33]
Had Lootr on a private server for bit before realizing it was a bit much OP when it interacted with other mods we had installed. I decided to remove it, not realizing it might break loot chest in structures in loaded chunks that hadn't been well, looted yet. Could re-installing lootr possibly fix it? As using something like MCEdit to regenerate chunks is not the most appealing option.

**Comment by noobanidus** [comment]
I'm sorry, but it's made pretty clear in the Lootr page on CurseForge:

> What will happen if I remove this mod? As with any mod that you remove from an instance, blocks, entities, items, etc, are removed. This means that every Lootr converted chest will be removed. There is no easy way to avoid this. 

Simply put, while the block data remains in the registry, the tile entity itself and thus the information it contained is also removed. 

This means that reinstalling Lootr will not restore any missing chests.

It *is* theoretically possible to recreate missing chests as Vanilla loot chests with a separate mod installed after Lootr is removed, but that relies on a lot of behind-the-scenes work and isn't something I've had the time to put into action yet.
