### ISSUE TITLE
Server Crash on Lootr Chest Interact

### ISSUE THREAD

**Issue by lanwoodall423** [noobanidus/Lootr#331]
1.20.1 Forge 

Server crashes when interacting with any lootr chest
[crash-2024-04-15_15.49.50-server.txt](https://github.com/LootrMinecraft/Lootr/files/14983832/crash-2024-04-15_15.49.50-server.txt)
[crash-2024-04-15_16.07.37-server.txt](https://github.com/LootrMinecraft/Lootr/files/14983834/crash-2024-04-15_16.07.37-server.txt)
[latest.log](https://github.com/LootrMinecraft/Lootr/files/14983838/latest.log)

Log is for the latest crash

**Comment by noobanidus** [comment]
Please check #172 for solutions to this error; this is actually an issue with Vanilla minecraft, where treasure and exploration maps are struggling to locate targets and end up causing chunk generation on the main thread.

This can be solved with the mod "Async Locator".
