### ISSUE TITLE
Publish on Modrinth newer versions

### ISSUE THREAD

**Issue by SettingDust** [noobanidus/Lootr#340]
The modrinth project need to update.

The CurseMaven only holding id on files instead of version number that isn't readable.

**Comment by noobanidus** [comment]
The uptake of Lootr on Modrinth is extremely minimal compared with CurseForge and, until I get uploads working alongside CurseForge, manual updates will take a while.

That said, you can simply view the available files on CurseForge, select the one you want and then copy the file ID from that page for CurseMaven.

**Comment by SettingDust** [comment]
There are 388K on Modrinth. Hmm

**Comment by SettingDust** [comment]
> and, until I get uploads working alongside CurseForge, manual updates will take a while.

Make sense

**Comment by noobanidus** [comment]
> There are 388K on Modrinth. Hmm

For comparison, the previous single version for Fabric for 1.20 available on CurseForge had almost 300k downloads from mid-February until now, versus 388k *total* on Modrinth for all versions.

**Comment by noobanidus** [comment]
As of 1.21's Architectury-based multiproject, builds are now being published on both CurseForge and Modrinth.
