### ISSUE TITLE
lootr:chests/elytra not found

### ISSUE THREAD

**Issue by flarefluffsune** [noobanidus/Lootr#349]
I got to my first End City Ship and I got this opening a chest. I can likely resolve this myself if given the correct file and where to place it.

[13:35:19] [Server thread/ERROR]: Unable to fill loot chest in ResourceKey[minecraft:dimension / minecraft:the_end] at class_2338{x=-877, y=141, z=-829} as the loot table 'lootr:chests/elytra' couldn't be resolved! Please search the loot table in latest.log to see if there are errors in loading.
[13:35:19] [Render thread/INFO]: [CHAT] The loot table for this container [lootr:chests/elytra] resolved to empty and loot could not be generated. Check your latest.log for errors.

I'm playing on the All of Fabric 7 modpack. Initially reported it on their GitHub: https://github.com/TeamAOF/All-of-Fabric-7/issues/238

**Comment by noobanidus** [comment]
That sounds like a big whoops on my part! Somehow, when porting over the new code, it never copied the actual loot table. I can't fix it right now but I should have a release out for it today -- also including the new texture update!

**Comment by flarefluffsune** [comment]
Okay thanks, so it should just be resolved with a manual update of the mod's jar file?

**Comment by noobanidus** [comment]
I haven't released it yet as I'm still working on the new textures, but once it's released then I'll comment on this issue.

**Comment by ghost** [comment]
I've got quite a few users running into this issue and I'd really appreciate if you could prioritize getting the fix for this out before new textures if possible. Thanks for your time and work on lootr.

**Comment by noobanidus** [comment]
To clarify, the new textures had already been implemented, but I had some real-life family issues with medical things that were driving a lot of stress.

I've now made the new release and it's available on CurseForge.

**Comment by ghost** [comment]
All good, hope that your family situation gets better and I appreciate the quick release. Take care.

**Comment by flarefluffsune** [comment]
Thank you for the update, I hope things get better for your family and yourself.
