### ISSUE TITLE
Lootr Chests Empty, Some Invisible

### ISSUE THREAD

**Issue by digimel** [noobanidus/Lootr#350]
I'm running a modded multiplayer server with my friends. Lootr chests are showing up empty and some of them are invisible until you interact with them. It's the strangest thing, because Lootr seems to work fine when I play singleplayer. The issue is only with multiplayer. What could be causing this?

For reference, I'm running minecraft 1.19.2, forge 43.3.0, and the latest version of Lootr. 

Edit: It seems that chests in new chunks actually have loot, but only chests in new chunks.

**Comment by noobanidus** [comment]
That sounds as though the chests have been corrupted; did you use some type of chunk generation? Lootr isn't compatible with all chunk generators, so this may be the issue -- especially as chests in new chunks are functioning properly.

**Comment by digimel** [comment]
Yes, that was the problem. I reset my chunks and it's fixed. Thanks!
