### ISSUE TITLE
Missing Texture on 0.7.32.79

### ISSUE THREAD

**Issue by flarefluffsune** [noobanidus/Lootr#352]
I updated to the latest version and there appears to be a missing texture.

![2024-05-01_09 23 21](https://github.com/LootrMinecraft/Lootr/assets/20187367/9895387c-4f93-48ed-8cf4-d98dcd636eb8)
![2024-05-01_09 23 40](https://github.com/LootrMinecraft/Lootr/assets/20187367/fc7029da-cde3-408f-a101-3cab937f7e18)

**Comment by noobanidus** [comment]
Whoops, wrong file name. I've just uploaded a new build to CurseForge, hopefully it's approved soon.

**Comment by flarefluffsune** [comment]
I just want to say I absolutely love the new textures.

**Comment by noobanidus** [comment]
Thanks! They weren't quite finalized when I did the previous release, but they'll be out for Forge soon. 1.20.6 will take a while though, I'm afraid.

Textures are by [Vouniern](https://www.curseforge.com/members/theu1t1mateguy/projects).
