### ISSUE TITLE
Repeatedly open on the chest makes the NBT "LootrOpeners" grow

### ISSUE THREAD

**Issue by LTCatt** [noobanidus/Lootr#36]
It looks like it will add your UUID to the list "LootrOpeners" every time you open the chest.
So every time I open the chest, the list gets longer...
Maybe adding a de duplication can solve this problem?

`/setblock 1473 33 -2380 lootr:lootr_chest[facing=south,type=single,waterlogged=false]{LootTable:"minecraft:chests/abandoned_mineshaft",specialLootChest_table:"minecraft:chests/abandoned_mineshaft",specialLootChest_seed:1800893817246977764L,tileId:[I;-1422398219,1047154338,-1799860804,1174282369],LootrOpeners:[[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401],[I;-1567232144,-1009365403,-1596012019,-1684333401]],LootTableSeed:1800893817246977764L}`

**Comment by noobanidus** [comment]
That's odd, it should be a set rather than a list and this no duplication. I'll look into it.

**Comment by noobanidus** [comment]
This should be fixed in the next release. CurseForge is down so there'll be delay.
