### ISSUE TITLE
[Feature Request] Variable Textures for Chest

### ISSUE THREAD

**Issue by VVVHY** [noobanidus/Lootr#367]
It may be nice to create a feature to be able to set variable textures for different chests depends on the loot tables or something, which could point to some jewel chests or weapon chests, something luxurious or primitive. 

Might be useful for modpacker. Just an idea when I noticed that Lootr compat with Quark's chest, which also created variable loot chest.

**Comment by noobanidus** [comment]
This isn't something that I'm likely to do in Lootr itself as it's beyond its scope. Perhaps it could be added with an add-on mod; the Quark variant chests are also implemented by Quark and aren't in Lootr.
