### ISSUE TITLE
Lootr ignores removed/disabled items from loottables from other mods.

### ISSUE THREAD

**Issue by zEpiixz** [noobanidus/Lootr#38]
Hello!

So today i had it occured that i disabled an enchantment from the loottable from uniqueEnchantments from their config.

But it was still possible to find them in lootr chests.

I opened an issue on their github aswell because im not sure which mod causes this flaw.

**Comment by noobanidus** [comment]
My code doesn't do anything different than vanilla. I'm going to assume that they're missing a check in the "can appear on books" to check the config as to whether or not it's enabled. I am going to close this and refer it back to them.

**Comment by Speiger** [comment]
Found the problem the issue was that mc added new functions we didn't see. Patched in the upcomming patch thats is being right now submitted
