### ISSUE TITLE
Lootr 1.16.4-0.0.5.17, custom chests not working properly.

### ISSUE THREAD

**Issue by Wesabii** [noobanidus/Lootr#39]
When making a custom lootr chest ("/lootr custom" while standing on a chest), whenever a player takes an item out of the chest, the item disappears for all players. If they put an item in the chest, it doesn't appear for any players.

**Comment by noobanidus** [comment]
Bugger, I swear I fixed this, let me look into it.

**Comment by noobanidus** [comment]
Okay, it took me a while, but I finally tracked down the issue. This should be fixed in the latest release on CurseForge (0.0.6+).
