### ISSUE TITLE
Issue with Dimensional Dungeons

### ISSUE THREAD

**Issue by WindFox** [noobanidus/Lootr#4]
In my modpack, I've noticed an issue with Lootr and DimDungeons.
It does not convert the chests in the dungeons (in fact, they are now empty)
Also, when in the dungeon, TheOneProbe just shows "Error: Chunk not loaded" on everything.

Removing Lootr fixes both. Well, for new dungeons anyways.

**Comment by noobanidus** [comment]
What version of Minecraft and Lootr are you running?

**Comment by WindFox** [comment]
Ah, right. Forgot to put that.

Minecraft: 1.15.2
Forge: 31.2.36
Lootr: 0.0.3.7

**Comment by noobanidus** [comment]
Awesome!

To be honest the "Chunk not loaded" error kind of concerns me. The fact that they're empty means that the fall-back that prevents things from being destroyed/discarded is obviously failing to work... It's also possible that this is the dimension that had some strange chunk-related behaviours.

It might be possible that I just need to include tile entities from that dimension on a blacklist.

**Comment by WindFox** [comment]
Might be a good idea since they are one and done places.
It's like switching to adventure mode on the fly and the mobs are only spawned in during generation.

....It's a weird place.

**Comment by noobanidus** [comment]
The 1.15 version is no longer supported, please lelt me know if this still happens with 1.16.
