### ISSUE TITLE
Update mods.toml to correct version ranges

### ISSUE THREAD

**Issue by MelanX** [noobanidus/Lootr#404]
Just wanted to ask if it's correct that this version is for 1.18.2-1.20.6: https://modrinth.com/mod/lootr/version/W1iHprsE
The file name indicates that it's 1.18.2 only. It's suspicious that it's for so many versions.

**Comment by noobanidus** [comment]
Thanks for that! I've manually updated the version on Modrinth.

I'm keeping this issue open (and renaming the title) as a reminder to myself to a) go through and fix up all of the current mods.toml files to make sure the version ranges are expressed properly, and b) to write the Python script that generates an up-to-date mods.toml in a future version.
