### ISSUE TITLE
Server crash when opening specific chests in dawncraft (Watchdog suspected mod:Lootr)

### ISSUE THREAD

**Issue by miyoshikai** [noobanidus/Lootr#406]
[crash-2024-06-13_14.45.02-server.txt](https://github.com/user-attachments/files/15814645/crash-2024-06-13_14.45.02-server.txt)

**Comment by noobanidus** [comment]
This looks like the pinned issue #172 

Please check that out for advice etc.

**Comment by miyoshikai** [comment]
> This looks like the pinned issue #172
> 
> Please check that out for advice etc.

Sorry for late reply.
This fixed the issue!!!
Thank you!
