### ISSUE TITLE
Inventory not Generated

### ISSUE THREAD

**Issue by Panda4Win** [noobanidus/Lootr#407]
Hello i using this mod on server
and it only saying on all chests
(Inventory not Generated) how to fix?
(MC: 1.20.1)
(Lootr: 0.7.34.86)

**Comment by noobanidus** [comment]
If it's showing this in a HUD mod like Jade, that simply means that that mod doesn't have integration with Lootr. If you are still able to open chests and get loot, there is no issue.

**Comment by Panda4Win** [comment]
> If it's showing this in a HUD mod like Jade, that simply means that that mod doesn't have integration with Lootr. If you are still able to open chests and get loot, there is no issue.

oh okey but i had zero problem with jade on version 1.19.2 and worked fine with lootr

**Comment by noobanidus** [comment]
There is a Jade integrations mod that you may have also had installed as well.

**Comment by Panda4Win** [comment]
yea i got it to work it was jade thank you :)
