### ISSUE TITLE
Dungeons Plus

### ISSUE THREAD

**Issue by GoblinOfDice** [noobanidus/Lootr#41]
There is something going on with the latest update of Lootr that is making all but the last floor of the battle towers empty

**Comment by noobanidus** [comment]
That's a bit strange! I'll have a look into it. Can you specify which versions of Lootr and Dungeons Plus you're using? i don't believe anything I changed in the recent version of Lootr should've had an impact on Dungeons Plus -- as none of the world generation-related code has changed.

**Comment by noobanidus** [comment]
Do you have any more information about this?

**Comment by noobanidus** [comment]
I haven't had any other reports about this or any further information, so I'm closing this issue. If it's still an issue or is otherwise noticed, please start a new issue for it.
