### ISSUE TITLE
Suggestion: Lootr Compat

### ISSUE THREAD

**Issue by SafeOfArsenal** [noobanidus/Lootr#411]
the mimic mod still shows the old texture on lootr

**Comment by noobanidus** [comment]
Hi there! Lootr doesn't add any mimic mods. You'll have to identify which mod adds it and inform them that there are different textures available.

**Comment by SafeOfArsenal** [comment]
sorry for not saying the mod 😅. It was the Artifacts mod

**Comment by noobanidus** [comment]
Right. I can't control their textures; you'll have to report this to them.
