### ISSUE TITLE
Aether Mimic Compatability Broken for 1.20.1 since 0.7.33.82

### ISSUE THREAD

**Issue by oitsjustjose** [noobanidus/Lootr#413]
## Description

When running a minimal instance with just The Aether and Lootr, Mimic Chests appear to have a broken texture:

![2024-06-29_08 29 29](https://github.com/LootrMinecraft/Lootr/assets/3887324/8c877dd8-3479-4b8a-98bc-11ef7218eab4)

This issue has been present since Lootr 0.7.33.82 -- running Lootr 0.7.31.77 things work perfectly as expected:

![image](https://github.com/LootrMinecraft/Lootr/assets/3887324/ce594787-c468-4f86-b82d-6e92dfe70ad9)

## Version Info:

- Minecraft: 1.20.1
- Forge: 47.3.3
- Lootr: 0.7.34.85
- The Aether: 1.20.1-1.4.2-neoforge

-----

Let me know if you need any additional info!

**Comment by noobanidus** [comment]
This is an issue with Aether that I have notified them about. I do not control what they do with textures, unfortunately, so I can't offer any assistance except to go to their issue tracker and comment there.

**Comment by oitsjustjose** [comment]
Oh good to know -- I looked through both repositories' issues and didn't see any further mention but I'll bring it up. Thanks!!!

**Comment by oitsjustjose** [comment]
Ugh, it was [right there](https://github.com/The-Aether-Team/The-Aether/issues/2185) and I somehow missed it >_>
