### ISSUE TITLE
1.20.2 

### ISSUE THREAD

**Issue by FoxofGoodVibes** [noobanidus/Lootr#414]
![image](https://github.com/LootrMinecraft/Lootr/assets/174390281/ba3b0b76-a79f-4f8f-b4aa-baeb880aff33)

**Comment by noobanidus** [comment]
Lootr is only available for Forge 1.20.0, 1.20.1 and for NeoForge 1.20.4. No releases were ever made for 1.20.2 which had significant code changes.
