### ISSUE TITLE
Loot Chest read-only configuration

### ISSUE THREAD

**Issue by Dr-WeiAL** [noobanidus/Lootr#423]
Is it possible to add a config so that Loot Chest can only take things from it and not put things in it?
Some players will put things inside Loot Chest so that admins have no way to see what's been put in.

**Comment by noobanidus** [comment]
Unfortunately this isn't currently possible as Lootr uses the Vanilla menus and interface code.

**Comment by Dr-WeiAL** [comment]
Okay, I get it.
