### ISSUE TITLE
[Suggestion] Atum ruins crates support

### ISSUE THREAD

**Issue by Darkmega18** [noobanidus/Lootr#43]
Basically, Atum has structures all over the place full of dead wood crates with relatively junky stuff which doesn't get touched by lootr. could be neat if it did for groups etc.

I don't think you'd be able to do much for the sarcophagus's though, especially cause of pharaohs being in them in the pyramids, but would be interesting if you could.

**Comment by noobanidus** [comment]
If you can run Lootr with the table debugging on and provide a log, I'll see what I'm able to do.

Sometimes chests are just generated with loot in them rather than using a loot table.

Alternately, the next release is going to automatically include anything in the wooden chests tag that is a LockableLootTileEntity (i.e., standard chest), in addition to allowing for expanding the list by adding chests manually.

It still might be needed for the mod to switch to a static method instead of a setLootTable, but I need more info.

**Comment by Darkmega18** [comment]
Alright, I'll look into it. Might not be tonight cause got some stuff to finish up with configuring some things I want to get over with and then some other life tid-bits to do, but I'll see what comes up.

**Comment by noobanidus** [comment]
Did you get a chance to try it out?

**Comment by Darkmega18** [comment]
oh shoot! I completely spaced out on it from doing other things in my pack. I'll go take a look nowish while I'm fiddling with stuff.

**Comment by Darkmega18** [comment]
Oh no: https://www.youtube.com/watch?v=GlzkjieJuoQ

Lootr just froze the game at 78%ish and this came up in the logs.

https://pastebin.com/dhfsY9Cc

don't think I can take a look through until that stops happening. D:
something about the atum crates not being waterloggable. (since I guess theres no point cause they're full blocks)

**Comment by noobanidus** [comment]
Thanks for that, it's a pretty bad issue. I'll fix that now and make an urgent new release.

**Comment by Darkmega18** [comment]
roger-roger. lemme know when it's good. and I'll give it another go, with feelings.

**Comment by noobanidus** [comment]
Give it a go with the latest release (0.0.7.21) and let me know if it automatically supports Atum now!

**Comment by Darkmega18** [comment]
here we go.
https://pastebin.com/LLp7s1km
Loots for lootr. I loaded it first without debug to check if it would pick up. no dice, on the ruins or the mineshaft chests, they were all defaulted. so I turned on the debug, and left it for a little bit, and here i just cherry picked out the lootr logs from my latest log. hope this is good to use. :)

**Comment by noobanidus** [comment]
Okay, I'll add that to the known incompatibilities list. I'll try to get around to making PRs soon.

**Comment by noobanidus** [comment]
I've created a PR for this: https://github.com/TeamMetallurgy/Atum2/pull/338

**Comment by Darkmega18** [comment]
Ho, nice!
