### ISSUE TITLE
question about item quantity

### ISSUE THREAD

**Issue by pocinhas** [noobanidus/Lootr#431]
hey, does lootr also allow to control how many items spawn in a chest? like a cap of x items, or a minimum of y items? (if not, i'd like to suggest this :) )

**Comment by noobanidus** [comment]
No, it doesn't; Lootr will most likely never actually modify the contents of chests, as all it does is replace the containers.

I did have plans for a "Lootr Filters" add-on but it's been on the back-burner for a while.
