### ISSUE TITLE
Is there a way to force clients on server to use old texture? 

### ISSUE THREAD

**Issue by MythCracker** [noobanidus/Lootr#439]
Hi, I'm running an All the Mods 9 server with lootr version 0.7.34.86
I was wondering if there was a way to force clients that connect to use the older gold texture for lootr instead of the new one? I changed the client config in the server to old textures = true but this doesn't seem to actually force the clients to use it. The main reason being that the mimic still picks up the gold texture, so it's obvious from a larger distance. 

![2024-07-31_01 07 44](https://github.com/user-attachments/assets/20870a1d-47ac-48a7-9d31-f21d38f7b762)
![2024-07-31_01 07 37](https://github.com/user-attachments/assets/18eb7924-9061-46f4-95ff-05480c5dc856)

**Comment by noobanidus** [comment]
The only way I imagine being able to do this would be to force a server resource pack and override the current default textures, unfortunately.

**Comment by MythCracker** [comment]
Ah, tragic. Well, thanks anyways!
