### ISSUE TITLE
Dungeon Crawl incompatible as of 1.6.15-2.3.2

### ISSUE THREAD

**Issue by jackyboy1992** [noobanidus/Lootr#44]
so ive got a pack that's got dungeon crawl in it but none of the chests that spawn are being changed to the lootr ones
![image_2021-08-12_144319](https://user-images.githubusercontent.com/1923334/129207441-340300c9-d9ad-4743-b9dc-06ec9fdc37ec.png)

**Comment by noobanidus** [comment]
What version of Minecraft, Lootr, Dungeon Crawl, etc?

Can you turn the debug option on in Lootr and upload a copy of your latest log after exploring a new Dungeon Crawl structure?

**Comment by jackyboy1992** [comment]
ok so im on 
minecraft 1.16.5 
lootr 1.16.5-0.0.6.18
dungeon crawl 1.16.5-2.3.2
but im unsure how to turn on the debug option so cant give you the results just yet

**Comment by noobanidus** [comment]
Like I said, it's possible something's changed recently with Dungeon Crawl to make these not function properly.

1. If you open the lootr-common.toml config on the server (in the config folder) or your client if you're running in single-player, look for the following section:

```toml
#catches loot chest creation that this mod cannot convert, reporting the loot table, location and mod
report_tables = false
```

2. Change `false` to `true` and then relaunch.

3. Once you've done that, start a new world in creative mode, then use `/locate dungeoncrawl` (it should allow you to autocomplete with the `tab` key) to find one of the structures, explore it in spectator mode.

4. Post the `latest.log` file from your `logs` folder (same directory as the `config` folder) on https://gist.github.com and link it here.

**Comment by jackyboy1992** [comment]
[latest.log](https://github.com/noobanidus/Lootr/files/6979037/latest.log)

**Comment by noobanidus** [comment]
Yep, looks like the loot-table setting method changed in 2.3. I'll try to work on a PR for it today.

Issue on their github: https://github.com/xyroc/DungeonCrawl/issues/81

**Comment by noobanidus** [comment]
Referenced the wrong issue number, whoops.

**Comment by noobanidus** [comment]
I've created a PR (https://github.com/xyroc/DungeonCrawl/pull/93) to address this.
