### ISSUE TITLE
Forge 1.19.2 Lootr - Create mechanism destroy lootr barrel/chests/shulkers.

### ISSUE THREAD

**Issue by kitovoi111** [noobanidus/Lootr#445]
Forge 1.19.2 Lootr - Create mod mechanism destroy lootr barrel/chests/shulkers.

**Comment by kitovoi111** [comment]
Previously, lootr didn't break, but now they do. You broke something in the mod update.

**Comment by noobanidus** [comment]
As far as I'm aware, and the last time this was brought up last year (on my Discord), this was controlled through Create's tags system, likely [https://github.com/Creators-of-Create/Create/blob/mc1.19/0.5.1/src/generated/resources/data/create/tags/blocks/non_movable.json](this tag).

With regards to the drill, I'm not entirely sure what part of Create controls it.

As I said at that time, unfortunately I can't control what other mods do with Lootr blocks. You'll need to investigate how Create handles these blocks, etc.
