### ISSUE TITLE
Locked Chests not locked on 1.21

### ISSUE THREAD

**Issue by WenXin20** [noobanidus/Lootr#461]
`Minecraft v1.21.1`
`Neoforge v21.1.31`
`Lootr v0.9.32.76`
[`Warp Pipes v2.2.3`](https://modrinth.com/mod/wenxins-warp-pipes/version/AmY0Gfov)

Hello, I just updated my Warp Pipes mod to 1.21, but Lootr does not seem to be keeping the chest locked. 
The locked chest can be found in the `warp_pipes:world_1-2_town` structure in one of the small brick castles. The key to unlock it is found underground in a loot chest in the structure `warp_pipes:world_1-2`

**Comment by noobanidus** [comment]
Ah, sorry! Part of the issue with moving to a the new, multi-project system is that, while the code is easier to read, it's possible that regressions would slip in. I'll try to update this shortly.

**Comment by WenXin20** [comment]
No worries, thanks!

**Comment by noobanidus** [comment]
I believe I have this working, but I realize now that, compatibility-wise, there could be issues with lock-codes when it comes to other mods (like ImmersiveMC) opening containers by fetching the data. I'm not quite sure what to do about that.

**Comment by noobanidus** [comment]
This is available in the most recent 2 releases. Please let me know if you have any issues with it!

**Comment by WenXin20** [comment]
Thanks!
