### ISSUE TITLE
Holding dispatch command event is leaking Spark Server

### ISSUE THREAD

**Issue by pietro-lopes** [noobanidus/Lootr#464]
Do you really need to hold this variable? I didn't find any reference that uses this.
https://github.com/LootrMinecraft/Lootr/blob/acf9c39d58d80c2ae5ee68d0e7aa16a2351aee5c/neoforge/src/main/java/noobanidus/mods/lootr/neoforge/Lootr.java#L35

It is causing Spark server to leak to main menu.

**Comment by noobanidus** [comment]
Ah, interesting. This is a bit of a hold over from older versions where the command registration was different. I'll adjust how it handles the dispatcher.

**Comment by noobanidus** [comment]
Resolved this by unfinalizing the dispatcher within the `CommandLootr` class and setting `dispatcher` to null after the registration is complete. I believe this should solve the issue. I'll include it in the next release (which will likely come after adjustments made to the API for integration with other mods).
