### ISSUE TITLE
Lootr using significant memory allocation

### ISSUE THREAD

**Issue by ChiefArug** [noobanidus/Lootr#469]
https://spark.lucko.me/JVPgvcVKdu?hl=22216,22320
![image](https://github.com/user-attachments/assets/0a0e02af-a265-44a1-b51e-6158334ba7f3)
Seems to be the string concatting here: 
https://github.com/LootrMinecraft/Lootr/blob/l10n_1.21/src/main/java/noobanidus/mods/lootr/api/data/ILootrInfo.java#L43
which is kinda weird as i dont expect concatting to normally take that much memory :shrug: 

Side note, can the default branch be changed to something more recent than 1.16?

**Comment by noobanidus** [comment]
That's bizarre! I'll make a note to cache that value.

**Comment by noobanidus** [comment]
I believe this has been resolved in recent versions. Please re-open this issue, or open a new issue, if you experience it further.
