### ISSUE TITLE
Texture on Singleplayer is different to the multiplayer texture

### ISSUE THREAD

**Issue by payphone101** [noobanidus/Lootr#475]
Title pretty much describes the issue, Lootr version is v.0.7.33.81 (1.20.1)
![image](https://github.com/user-attachments/assets/35741814-ed8d-47ae-acfc-525017ffe582)

**Comment by noobanidus** [comment]
What multiplayer texture are you seeing? This looks like the standard texture included in 1.20.

**Comment by payphone101** [comment]
the multiplayer texture I've seen is the gold (unopened) > blue (opened) texture

**Comment by noobanidus** [comment]
You can change to the old textures through the configuration on the client. "old_textures" is the option you're looking for.
