### ISSUE TITLE
I cannot see chests after changing client vanilla textures to yes

### ISSUE THREAD

**Issue by chopper355** [noobanidus/Lootr#487]
I dont know what to do. My chests are invisible anymore. I can only see top of chest and thats the moving part of it i only see that while opening animation.
![2024-10-26_18 31 52](https://github.com/user-attachments/assets/d1a69c7f-8b16-4234-8db2-6d696ebe6c24)

**Comment by chopper355** [comment]
i cannot see my chests anymore even after changing that to no. Im gonna remove the mod and see if its related

**Comment by chopper355** [comment]
i can see chests when i remove the mod

**Comment by noobanidus** [comment]
What version of Minecraft are you running, what mod loader, and what version of Lootr? I also need a copy of your `latest.log` file.

**Comment by chopper355** [comment]
i currently use 1.21 fabric and loader version is 0.16.7 . The lootr version is 1.10.33.85.
I currently get crashes i dont really know if that is problem on finding the issue but let me send the log. If you want me to send it when my game doesnt crash. Im gonna send the other log whenever i fix the crashing issue.
https://mclo.gs/wO3WNSH thats the current crash log.

**Comment by noobanidus** [comment]
Are you using a mod "Fast Chest" or "FastChest" at all? I've had reports that this causes Lootr chests to disappear.

EDIT: It appears from the log file that you posted a link to that "SparseStructure's config file is malformed". Have you tried deleting the configuration file for that mod?

**Comment by chopper355** [comment]
yeah you were right. I accidently fixed the issue because sparsestructure config crashed the game tons of times. i just tried to create a new profile and copy mods into it and the issue was gone. thanks for your help.

**Comment by chopper355** [comment]
thanks for the mod too. Its really cool mod. Thanks for your hardwork.
