### ISSUE TITLE
Issue with Moving and Opening Loot Chests in Minecraft 1.21 with Lootr and Carry On Mods

### ISSUE THREAD

**Issue by JebsApple** [noobanidus/Lootr#492]
### Expected Behavior
In previous versions (Minecraft 1.20.1), we could use the "Lootr" mod along with "Carry On" to pick up loot chests from structures and bring them back to our base. There, other players who didn’t join the expedition could open these chests and get the loot.

### Actual Behavior
In the current version (Minecraft 1.21, Fabric 0.16.0), when attempting to replicate this behavior, two issues occurred:

1. After bringing loot chests back to base, my teammate tried to open them, but they would instantly close. When I tried opening them myself, the same issue occurred. This problem only affects loot chests naturally generated in structures, while minecart chests in mineshafts can still be opened without issue.

### Steps to Reproduce
1. In Minecraft 1.21, Fabric 0.16.0, load the "Lootr" and "Carry On" mods.
2. Use "Carry On" to try picking up and moving loot chests from naturally generated structures.
3. Attempt to open these chests in a new location after moving them.

### Version of Minecraft, Carry On, Forge/Fabric
- Minecraft: 1.21
- Fabric: 0.16.0
- Lootr: lootr-fabric-1.21.1-10.1.3
- Carry On: carryon-fabric-1.21-2.2.1

**Comment by noobanidus** [comment]
Are you able to include a copy of the server's log?

**Comment by JebsApple** [comment]
> Are you able to include a copy of the server's log?

I dont really know how to do it

**Comment by noobanidus** [comment]
There should be a `logs` folder on your server which has a `latest.log` file. Ensure your server is running, attempt to open the chests and then close them again. I'd also run the `/data get block` while looking at the chests, and use the tab-completion functionality to fill in the coordinates of the block you are looking at.

Once this is done, you can copy the `latest.log` over to https://gist.github.com or pastebin or equivalent.

**Comment by noobanidus** [comment]
I've managed to identify the issue and resolved it in the most recent release for 1.21.

**Comment by JebsApple** [comment]
> I've managed to identify the issue and resolved it in the most recent release for 1.21.

Thank you very much, and I am sorry for not sending the info on time, I was going to do it today but I found out that it had already been fixed.
