### ISSUE TITLE
All chests generating empty

### ISSUE THREAD

**Issue by feathersstreet** [noobanidus/Lootr#5]
I made a family server and thought this mod would be a nice addition. Well everytime we try to loot a village, maybe one chest has loot, if that. It also deletes the loot from the ruins mod we have so any structures made by it are missing their cool loot.

**Comment by noobanidus** [comment]
Which version of Minecraft and Lootr are you using, and could you give me a list of all of the mods that you have running? I need a bit more information to go off, I'm afraid.

**Comment by noobanidus** [comment]
The 1.15 version is no longer supported. Please let me know if you still have issues in 1.16.
