### ISSUE TITLE
Chests get double locked by a possible Lootr interaction?

### ISSUE THREAD

**Issue by Darkmega18** [noobanidus/Lootr#51]
I'm using a mod called locks by melonslise. It makes loot chests spawn with locks on them that you have to pick with lock picks. This usually works just fine and the locks stick fine on the new chest and work as intended.

However I've started noticing that chests are being locked twice lately in my modpack, I'm not sure if this is a world gen lag thing, an entirely locks issue or potentially a compatibility issue with how lootr converts the chests and how locks detects generated loot chests to lock them.

I have half a thought that it could be some weirdness with how the chests are converted after the fact and then locks is checking the chests a second time after it thinks it detects a new chest which is actually the same chest and then reapplying locks to them... I can't be too sure about it though, unless you have thoughts on the cause of the issue?

I have reported it to locks also as seen here. It's a non-crashing issue otherwise.
https://github.com/Melonslise/Locks/issues/109

**Comment by noobanidus** [comment]
I'm really not sure, sorry. It depends on how their mod detects chests... it is entirely possible that due to it replacing the chest, it's being locked twice, but without diving into their code there isn't really much I can suggest might be the issue.

Please let me know if there's anything I need to do on my end.

**Comment by noobanidus** [comment]
Did you hear anything more about this?

**Comment by Darkmega18** [comment]
unfortunately not. melonslise hasn't replied or made an update in quite some time. :<

**Comment by Darkmega18** [comment]
rip in pieces. :V

**Comment by noobanidus** [comment]
There's nothing I can do about it form my end, I'm so sorry.

**Comment by Darkmega18** [comment]
is there any interest in potentially convincing you to just fork the locks mod and making it an addon or feature of lootr with some balance improvements? or is that a hard "not interested/"not the way I want to take this"? cause seems 6 months of inactivity with still outstanding bugs seems to be a loss of interest on melon's side. :<

**Comment by noobanidus** [comment]
Sorry, I have no interest in forking the project or merging it with Lootr, it's widely out of scope and I already have enough on my plate with this, Arcane Archives & Roots.

**Comment by Darkmega18** [comment]
yeah, I figured. It's k. I'll just have to bonk the chance of locks appearing and just let people rage when they roll a one and get double locks or something. :V 

oh arcane archives? I had that in 1.12.2 for a pack, is that coming out for later versions? I really liked the magically inclined visuals for it.

**Comment by noobanidus** [comment]
A little off-topic, but yes, I am slowly working my way through the 1.16.5 ports of both mods!
