### ISSUE TITLE
mismatched mod channel list [1.16.5] 

### ISSUE THREAD

**Issue by Sonnebahn** [noobanidus/Lootr#52]
In v 0.0.8.23 released 9/26/21, I receive a mismatched mod channel list between my server and my client after updating them both. It is an exact copy of the file in both locations. I noticed that the file released 8/29/21 also is labeled as v 0.0.8.23, which may be related.  When I revert both server and client back to the previous release the error is resolved.

**Comment by noobanidus** [comment]
That's my bad, I must've forgotten to bump the version number.

**Comment by noobanidus** [comment]
This should be fixed with 0.0.8.24.
