### ISSUE TITLE
lootr loot table errored out and had nothing in it

### ISSUE THREAD

**Issue by EdHunter91-mod** [noobanidus/Lootr#526]
The error code i got in my server

loot table 'dungeons_arise:chests/mines_treasure_medium' couldn't be resolved! Please search the loot table in `latest.log` to see if there are errors in loading.
[29Nov.2024 19:56:19.435] [Server thread/ERROR] [noobanidus.mods.lootr.api.LootrAPI/]: Unable to fill loot barrel in minecraft:overworld at BlockPos{x=151, y=98, z=2} as the 

i was on a multiplayer server alone.

**Comment by noobanidus** [comment]
This is an issue with `dungeons_arise`: their structure refers to a loot table that no longer exists in the mod (or the mod itself has been removed). While Lootr can report this, it's not an issue with Lootr, but rather the mod mentioned. I'd suggest updating the mod, or checking out its issue tracker to see if it's a known problem.
