### ISSUE TITLE
lootr crashing the server somehow?

### ISSUE THREAD

**Issue by VaporeonScripts** [noobanidus/Lootr#527]
https://mclo.gs/iUu518l

**Comment by VaporeonScripts** [comment]
neoforge 1.21.1 .83

**Comment by noobanidus** [comment]
This is a Vanilla issue, please see #172

**Comment by VaporeonScripts** [comment]
That mod isn't for 1.21.1 neoforge

**Comment by noobanidus** [comment]
It's still a Vanilla issue that Lootr can't help fix, sorry.

**Comment by VaporeonScripts** [comment]
Well,another mc issue that Mc can't fix without forcing people to switch versions,anyways ,ty for making such fantastic mod
