### ISSUE TITLE
Issue with mod interactions and not all chests being lootr

### ISSUE THREAD

**Issue by davidromrell** [noobanidus/Lootr#54]
[WIP-1.0.zip](https://github.com/noobanidus/Lootr/files/7501060/WIP-1.0.zip)

**Comment by noobanidus** [comment]
I'm sorry, but this isn't an adequate report.

You need to write a list of specific mods that aren't working and the specific structures associated with them. Screenshots would be great.

There's no way I'm going to randomly download a zip file from an issue report.

**Comment by davidromrell** [comment]
it wouldn't let me use html file...

**Comment by noobanidus** [comment]
A list of mods in your pack isn't going to suffice either. 

I need a list of the specific mods whose structures do not have Lootr chests.
