### ISSUE TITLE
Missing Textures on New Fabric 1.19.2 Version

### ISSUE THREAD

**Issue by RyanSalad** [noobanidus/Lootr#544]
Minecraft 1.19.2
Fabric 0.16.9
Lootr 0.4.29.71

The unopened trapped chest and centennial trophy show the magenta and black missing texture thing. I did check the assets in the jar, and the unopened trapped chest texture is in there and spelled correctly, so whatever the deal is, it's beyond me. Oh and I have no resource packs installed.

![2024-12-12_00 09 30](https://github.com/user-attachments/assets/3281bb7d-1da9-48fa-860a-e8ff0ad857dc)

Also worth noting that the opened trapped chest is completely fine and renders correctly as soon as I open it.

**Comment by noobanidus** [comment]
Whoops!

**Comment by noobanidus** [comment]
Okay, I've made a release that should fix this.
