### ISSUE TITLE
与拔刀剑重锋的冲突

### ISSUE THREAD

**Issue by biantwin** [noobanidus/Lootr#558]
拔刀剑se在部分时候无法共存，敲se时概率把原本se顶掉，最开始我们是通过删除一个配置文件解决的
![image](https://github.com/user-attachments/assets/89e12fb6-a1bb-49f9-b5a4-4db9bbfc9475)
但是还是很容易复现
然后我们尝试删除lootr，结果解决了...（经过多次测试，可以稳定修复）
想问一下这个冲突是什么原因，可以修复一下吗

**Comment by noobanidus** [comment]
I am unable to read Chinese so I may have misunderstood your issue.

Your error is with Lootr and Slash Blade being installed together, but I do not understand what the error is. Can you please show the error message or the crash report that you receive when these two mods are installed together?

**Comment by biantwin** [comment]
> 我看不懂中文，所以我可能误解了您的问题。
> 
> 您的错误是 Lootr 和 Slash Blade 一起安装，但我不明白错误是什么。您能否出示这两个 mod 一起安装时收到的错误消息或崩溃报告？

这两个

**Comment by biantwin** [comment]
> 我看不懂中文，所以我可能误解了您的问题。
> 
> 您的错误是 Lootr 和 Slash Blade 一起安装，但我不明白错误是什么。您能否出示这两个 mod 一起安装时收到的错误消息或崩溃报告？
这两个mod同时安装时并不会报错，只是[拔刀剑重锋](https://www.mcmod.cn/class/14899.html)这个mod在进行替换[Special Effect](https://www.mcmod.cn/item/215647.html)这个操作时原本是会共存的，但是装载了lootr之后概率出现新的se把旧的顶替的问题，而删除lootr之后就可以解决这个问题，所以我怀疑这两个mod之间有一些冲突
