### ISSUE TITLE
All The Magic: Spellbound Minecart Chests

### ISSUE THREAD

**Issue by FuzzyFoxe** [noobanidus/Lootr#56]
I'm fairly sure this issue should be posted here...
I've been playing All The Magic: Spellbound lately, and for some reason, a most of the time minecart chests seem to be empty when checked. Occasionally they have stuff, but most of the time it's empty. When using the Spectator from Botania, it will show that there's an item you're holding in the chest, (if it's supposed to be there), but the chest will still be empty. It's not even a server desync, I click the spots in the inventory, and nothing is there.

Minecraft: 1.16.5
Modpack: All The Magic: Spellbound (Version 2.1.6)

~~Hmm.. Could it be because I'm using the Twilight Cloak from Reliquary?~~
No, that's not it..

**Comment by noobanidus** [comment]
Could you try creating a single-player world and use the config to disable the Minecart alteration to see if they function as expected with Vanilla?

**Comment by FuzzyFoxe** [comment]
Weird.. Just tried both settings, both worked just fine. Something on their server must be changed..
