### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Simme0n** [noobanidus/Lootr#560]
Hello and merry christmas to all the people celebrating X-mas 

I opened a server recently and played a bunch of hours on this but ended up starting fresh and deleting my playerdata to play with a friend who just started. 

So basically i wonder how can i make the loot chests i have already looted to be refreshed for me, as if i just arrived on the server, see what i mean ? Because deleting the playerdata didn't erase everything so i wonder if there's anything i can do to start really start fresh...

Thanks a lot in advance and happy holidays ! 

Well guys everything is fine don't worry it works

**Comment by noobanidus** [comment]
If it's a brand new server, the simplest step would be to shut it down and delete the `data/lootr` folder. That will reset every chest for everyone.

Depending on the version of Minecraft & Lootr, there's also a command, `/lootr clear` that will allow you to tab-complete your name. However, this command doesn't function *properly* on versions before 1.20.
