### ISSUE TITLE
Lootr Causing Crashes?

### ISSUE THREAD

**Issue by CupcaketheWord** [noobanidus/Lootr#562]
I was launching a minecraft instance through modrinth and when the game finished loading an error saying "com.electronwill.nightconfig.core.io.ParsingException: Not enough data available Stacktrace" Appeared
Logs Provided Below
[---- Minecraft Crash Report ----.txt](https://github.com/user-attachments/files/18271371/----.Minecraft.Crash.Report.----.txt)
(Yes I have tried launching again and reinstalling the mod)

**Comment by noobanidus** [comment]
This sounds like the Lootr configuration file has become corrupted. If you go into the `config` folder (in the same directory as the `logs`, `crash-reports` and `mods` folders) and delete the `lootr-common.toml` and `lootr-client.toml` files, they should regenerate and the issue should resolve itself.
