### ISSUE TITLE
[1.16.5] Crash when scrolling through the Mod Configs page - [ (w/ Catalogue & Configured) ]

### ISSUE THREAD

**Issue by Gbergz** [noobanidus/Lootr#59]
**Title ^**

Scrolling down in the Mod Configs page crashes the game to desktop.

**Versions:**
Minecraft: **1.16.5**
Forge: **36.2.19**
Lootr: **0.0.9.27**

**GIF of Crash**:
https://i.gyazo.com/bf6d2a6123e2f85efc7ccc84b47bc517.mp4

**Crash-Report**:
https://gist.github.com/Gbergz/b9c292a4a36b32f52561b25b6ada20a1

**Comment by noobanidus** [comment]
Ah. Good old "player is null"... I constantly forget about that.
