### ISSUE TITLE
[Bug] Breaking Lootr Shulker Boxes drops 2 Shulker Boxes

### ISSUE THREAD

**Issue by Quarris** [noobanidus/Lootr#61]
Game Version: 1.16.5
Mod Version: lootr-1.16.5-0.0.9.29
Forge Version: 36.2.19

Breaking the lootr shulker box givex you 2 shulker boxes, upon further testing, breaking it in creative also drops 1 box.
https://user-images.githubusercontent.com/6171764/145576289-6017d837-89b8-4c48-a656-d3d05848c81c.mp4

Unrelated bug: Lootr Shulker Box tooltype and possibly block hardness is incorrect

**Comment by noobanidus** [comment]
Thanks! I didn't realise precisely what the code was doing with this and, as you might've guessed, only tested it in creative. I'll work backwards from 1.18.

**Comment by noobanidus** [comment]
Re: hardness, that is deliberately set higher than a regular shulker box in order to give people more warning about the value of it. I'm not sure why it's not displaying a required tool with Jade, however.

**Comment by noobanidus** [comment]
This is fixed in the latest 1.18 release (0.0.11.32). I'll look at backporting it shortly.
