### ISSUE TITLE
Lootr Creative tab is missing a language key

### ISSUE THREAD

**Issue by wilyank** [noobanidus/Lootr#62]
the unlocalized name is shown instead of an (english) localized name
Minecraft version:  1.16.5
Lootr version: lootr-1.16.5-0.0.9.29

**Comment by noobanidus** [comment]
Goddamn. Which version is this?

**Comment by wilyank** [comment]
sorry i forgot to add the version. i edited the description now

**Comment by noobanidus** [comment]
My bad, this is the one mod I use that doesn't use data gen much so I keep forgetting about things like this. I'll try to include it in the next release.
