### ISSUE TITLE
[1.18] Generated UUIDs for chests (at least) do not save to chunk

### ISSUE THREAD

**Issue by muetzeeio** [noobanidus/Lootr#63]
I don't know if its a issue but Lootr chests always have new loot when you walk a bit away.
maybe an option would be good to set whether a chest can be looted several times by the same player or not.

Forge version: 38.0.17
Lootr: 0.0.11.30 (newest one)

**Comment by noobanidus** [comment]
~~Are the chests changing colour as well?~~

**Comment by noobanidus** [comment]
~~More questions: ~~

- ~~Does this happen on a server or in single-player?~~
- ~~Do the colours of chests also revert?~~
- ~~Does this happen with 0.0.11.31?~~

**Comment by mekrod** [comment]
The same happens to me when going to the nether, the chests reset, they return to their yellow version. with 0.0.11.31 on a server.

**Comment by noobanidus** [comment]
Thanks for the confirmation and the replication steps. It looks like some data isn't being saved properly somewhere.

**Comment by noobanidus** [comment]
Can confirm this happens simply when relogging in single-player.
