### ISSUE TITLE
Updated compatibility - Please check here first!

### ISSUE THREAD

**Issue by noobanidus** [noobanidus/Lootr#64]
***As of the 0.1 series of Lootr, compatibility should now be automatic.***

***Please file individual issues for incompatible mods.***

---

(Please see #16 for previous discussions. New issue created to unclutter comments.)

**Aware**
- ~~Ocean ruins are non-functional: #48~~
- ~~Chest minecarts are no longer being converted: #47~~

**Alerted**
- [Dungeons Mod](https://www.curseforge.com/minecraft/mc-mods/dungeons-mod) (ARR, will require an issue filed as I can't PR it.)
- [Ice and Fire](https://github.com/Alex-the-666/Ice_and_Fire/tree/1.16.3/src/main/java/com/github/alexthe666/iceandfire) (only some of them are relevant)
- [Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest) (see Issue https://github.com/TeamTwilight/twilightforest/issues/1417)

**Awaiting merge/discussion:**
- [Charm](https://www.curseforge.com/minecraft/mc-mods/charm-reforged) (PR: https://github.com/svenhjol/CharmForge/pull/125)
- [Autumnity](https://www.curseforge.com/minecraft/mc-mods/autumnity) (PR: https://github.com/team-abnormals/autumnity/pull/109)

**Partially merged/may require additional PR:**
- None

**Currently merged and awaiting verification of release:**
- [The Farlanders](https://gitlab.com/modding-legacy/the-farlanders/-/merge_requests/1)
- [End Remastered](https://www.curseforge.com/minecraft/mc-mods/endremastered) ([PR](https://gitlab.com/endrem/end-remastered/-/merge_requests/20))

**Merged and released:**
- ~~[Atum 2](https://www.curseforge.com/minecraft/mc-mods/atum) (PR: https://github.com/TeamMetallurgy/Atum2/pull/338)~~
- ~~[Dungeon Crawl](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl) (PR: https://github.com/xyroc/DungeonCrawl/pull/93)~~
- ~~[Apotheosis](https://github.com/Shadows-of-Fire/Placebo/pull/19) via Placebo~~
- ~~[Quark](https://github.com/Vazkii/Quark/pull/3036) (obsidian pillars)~~
- ~~[YUNG's Better Mineshafts](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/pull/38)~~
- ~~[Dungeons Plus](https://gitlab.com/modding-legacy/dungeons-plus/-/merge_requests/3)~~
- ~~[EvilCraft](https://github.com/CyclopsMC/EvilCraft/pull/833)~~
- ~~[Artifacts](https://github.com/ochotonida/artifacts/pull/55)~~
- ~~[Dimensional Dungeons](https://github.com/AllenSeitz/DimDungeons/pull/16)~~
- ~~[Astral Sorcery](https://github.com/HellFirePvP/AstralSorcery/pull/1655)~~

**Independently Resolved**
- ~~[Shrines](https://github.com/Silverminer007/Shrines/blob/master/updateJSON.json#L20)~~

**Will most likely never be compatible**
- Futurepack uses extensive custom coding to generate their loot chests with loot in them, bypassing the Vanilla system. Without a significant change to this system (which I'm not willing to try to implement, not am I even sure if they are interested in having implemented), it is **not possible** in the slightest for there to be compatibility.
- [Dungeons Gear](https://www.curseforge.com/minecraft/mc-mods/dungeons-gear) uses a complex system of mixins that I have no desire to navigate.

If the mod you've found as being not compatible with Lootr isn't listed here, please comment on this issue. Include screenshots wherever possible.

Alternately, you can post in the #lootr-incompatible channel on my Discord.

**Comment by AngellusMortis** [comment]
[Confluence: Otherworld](https://www.curseforge.com/minecraft/mc-mods/confluence). A new big mod that adds Terraria content to Minecraft.

There are a bunch of themed chests for specific loot tables that do not get replaced. No screenshots right now, but [related issue](
https://github.com/Magic-team-jvav/confluence/issues/142) I made on their repo. Easiest way to find one is to use `/locate` for a Sky Island.
