### ISSUE TITLE
[1.16.5] Bad performance

### ISSUE THREAD

**Issue by bigenergy** [noobanidus/Lootr#68]
https://spark.lucko.me/D2yDG9sG7N

![image](https://user-images.githubusercontent.com/17977139/147384528-e552db36-7a18-43ee-af10-e1f5802a4dab.png)

lootr-1.16.5-0.0.10.32

**Comment by noobanidus** [comment]
I think you'll find that this is an outlier. That function is basically identical to the Vanilla version.

Are you able to replicate it? Or did someone just happen to open a container while you were profiling?

**Comment by noobanidus** [comment]
Digging into this further, the issue has nothing to do with Lootr:

![](https://i.imgur.com/gnNyqWl.png)

This is just what happens when opening chests with maps in them.
