### ISSUE TITLE
[1.16.5]Quark chest support

### ISSUE THREAD

**Issue by EnterFor** [noobanidus/Lootr#69]
I don't know how to explain it. Can you see what I have here?
They don't convert.
![JY )~G%MNS)B56WPZ_Y6X_J](https://user-images.githubusercontent.com/10114685/147547398-e3e40b38-003f-4e04-9f92-6971e2fc2035.png)

**Comment by noobanidus** [comment]
Can you upload your configuration file for me?

**Comment by EnterFor** [comment]
Are you asking for my Lootr config?or quark？

**Comment by noobanidus** [comment]
Lootr.

**Comment by EnterFor** [comment]
`#determine whether or not loot generated is the same for all players using the provided seed, or randomised per player
randomise_seed = true
#whether or not mineshaft chest minecarts should be converted to standard loot chests
convert_mineshafts = true
#whether or not quark chests used in world generation for loot purposes should be replaced with Lootr chests
convert_quark = true
#whether or not the entire forge:chests/wooden tag should be added to the conversion list for structures (if they are backed by LockableLootTileEntity)
convert_wooden_chests = true
#whether or not the entire forge:chests/trapped tag should be added to the conversion list for structures (if they are backed by LockableLootTileEntity
convert_trapped_chests = true
#catches loot chest creation that this mod cannot convert, reporting the loot table, location and mod
report_tables = false
#a list of additional chests that should be converted [in the format of modid:name, must be a tile entity instance of LockableLootTileEntity]
additional_chests = []
#a list of additional trapped chests that should be converted [in the format of modid:name, must be a tile entity instanceof LockableLootTileEntity]
additional_trapped_chests = []
#list of dimensions (to the exclusion of all others) that loot chest should be replaced in [default: blank, allowing all dimensions, e.g., minecraft:overworld]
dimension_whitelist = []
#list of dimensions that loot chests should not be replaced in [default: blank, allowing all dimensions, format e.g., minecraft:overworld]
dimension_blacklist = []
#list of loot tables which shouldn't be converted [in the format of modid:loot_table]
loot_table_blacklist = []

`

**Comment by noobanidus** [comment]
You can fix these chests by opening them first, then standing on them and typing `/lootr custom`.

I will look into releasing a fix.

**Comment by noobanidus** [comment]
Please update to 1.16.5-0.0.10.34 before exploring the end any further.

You can also fix this by changing the following configuration:

```
additional_chests = ["quark:purpur_chest", "quark:nether_brick_chest"]
```
