### ISSUE TITLE
[1.18.1] [When Dungeons Arrives] Null pointer crash

### ISSUE THREAD

**Issue by Firehead94** [noobanidus/Lootr#70]
https://pastebin.com/n1vdLJ4F
https://pastebin.com/h8Wfq8QV

Server crashes on login. Had to remove the mod from the modpack (ATM7 7.0.2.15) in order to boot the server and clear the chests in the area. There was a huge set of structures from "When Dungeons Arise" right near there so I am assuming it was something in there or in the mineshaft right next to it.

**Comment by noobanidus** [comment]
I'm not entirely sure why this is happening, especially as I'm not used to the obfuscated m names. I'll have a look through, although I do suspect that the experimental transition will solve the issue.

It does definitely appear to be a When Dungeons Arise structure, though.

**Comment by Firehead94** [comment]
I do know that the WDA dungeons also spawn double chests on the map on their structures and iirc, there aren't really any other structures that spawn double chests in them that i am aware of.

**Comment by noobanidus** [comment]
So, from decoding, it appears that my structure processor calls "clear" on a "Clearable", but for some reason the `getItems` method is returning null. I should be checking for that null value before calling `clear`, I think. I'll be doing a release to fix it before I begin porting.

**Comment by noobanidus** [comment]
Do you have the `report_tables` option enabled by any chance? I need to narrow it down to determine exactly what the issue is.

**Comment by Firehead94** [comment]
I do not but I do now, Ill see if I can force a crash and find a structure

**Comment by noobanidus** [comment]
Ah, got it:

Both the barrel and shulker box forcefully return "null" for `getItems` instead of an empty list. This is entirely my fault. I'll release a fix presently.

**Comment by noobanidus** [comment]
Please update to [0.0.12.38](https://www.curseforge.com/minecraft/mc-mods/lootr/files/3590423) when you can, it should fix this issue immediately.
