### ISSUE TITLE
[1.18.1] Structure Options / Control Chance

### ISSUE THREAD

**Issue by itsdinkd** [noobanidus/Lootr#71]
Hello, I am the developer of Another Quality Modpack 3. I currently am using your lovely mod in my pack, but I was curious... is there any way to disable lootr conversion based on structures? Some of the structure mods I use add so many chests, like Graveyard for example, where there's literally 100-200 chests. As you can see, this is quite a lot, especially with lootr converting them into re-lootable chests for new players.  (reason why is players can easily say go here to get all this loot, which has been done on the official servers). 

Could you possibly implement a feature that allows you to put a 'spawn chance' for a vanilla chest to convert into a lootr chest? like %20 chance of this happening, and also, is it possible to implement a feature to allow blacklisting lootr from working in given structures? 

thanks!

**Comment by noobanidus** [comment]
You can blacklist based on loot table, dimension and (soon-ish) modid. 

Unfortunately, it's not possible to do it per-structure.

I can add an option to instead *whitelist* per mod/loot table/dimension?

**Comment by noobanidus** [comment]
Additionally, there's also the decaying option that was recently added in 1.18.1.

**Comment by itsdinkd** [comment]
I mean the loot table blacklisting is great, however, if that structure does not use their own loot table and instead does what Lootr does, using vanilla loot tables, that unfortunately isn't an option. 

Decaying would be pointless as if i use decaying i might as well just remove lootr.

**Comment by itsdinkd** [comment]
What about the Vanilla chest to Lootr conversion chance request? this would be the most helpful for bigger structures with tons of chests using vanilla loot tables that still have injections from other mods.

**Comment by noobanidus** [comment]
That's a possibility but I feel like it would be a bit more frustrating experience overall. I'm going to look into how expensive it would be to access structure information at the point of blocks being added...

**Comment by noobanidus** [comment]
I'm currently experimenting with structure-based blacklisting in the 1.18 branch. It should in theory be working but currently isn't; hopefully I'll be able to get it sorted out.

re: Conversion chance... Honestly, I feel like modifying the structures via data packs to have unique loot tables would be a more effectual if slightly more time-consuming thing, if the structure-based blacklisting doesn't end up working out.

**Comment by noobanidus** [comment]
The 0.1 series of Lootr for 1.18.1 now has structure-based control. Please let me know how that goes for you!

**Comment by itsdinkd** [comment]
Awesome, thank you!

**Comment by noobanidus** [comment]
Let me know if there are any problems with it. I'm going to close this issue, but feel free to comment and I'll reopen it if necessary.
