### ISSUE TITLE
Restructure the data 

### ISSUE THREAD

**Issue by itsdinkd** [noobanidus/Lootr#73]
the data folder is spammed with lootr.dat files (over 2600 files from 3 weeks)
My suggestion would be creating a parent folder for this
/world/data/lootr

[image](https://user-images.githubusercontent.com/35115304/148496589-46cc67df-a283-4ef9-adf3-4053865db905.png)

**Comment by noobanidus** [comment]
Hey!

Unfortunately, this isn't something that I actually have any control over. It will generate 1 file for each chest/container that spawns on the server. This is primarily to prevent corruption which might occur if all of the data was stored in the same file.

As I rely on Minecraft's `SavedData`, I can only control the name of the file, I can't actually control the directory that it's in.

**Comment by itsdinkd** [comment]
Oh hm... there is a mod called "FLAN" that adds a "claimdata" folder into the data folder. any chance I can send you the repo to see how they did it?

**Comment by noobanidus** [comment]
Sure, but it would still be a breaking change that would require something in place to copy everything into the new directory... I'm not sure if I want to go that step just yet.

Is organization of this directory very important for you? It's ... basically doing what it's designed for.

**Comment by noobanidus** [comment]
Okay, looking further into the `FLAN` mod, it looks like they use a custom data system to save information.
