### ISSUE TITLE
[1.16.5] Lootr v1.11.35 replaces atum pharoah chests breaking boss summon

### ISSUE THREAD

**Issue by theboo** [noobanidus/Lootr#74]
Hello! Recently lootr updated and it now replaces the atum sarcophagus (loot ID: atum:chests/pharaoh) with two lootr chests. This breaks the summoning of the pharoah bosses in these pyramids as you must right click the sarcophagus to summon which no longer exists. 

This only occurs in the latest version of lootr v 1.11.35, does not occur in previous versions.

For now i have blacklisted the loot table in config but i feel this should probably be blacklisted by default in lootr as it breaks one of the core functions of atum  :)

reproduced with just latest versions of lootr and atum for 1.16.5

screenshot using lootr-1.16.5-1.11.35:
![image](https://user-images.githubusercontent.com/3585761/148886457-590f89d8-2e98-4fc9-babc-e086103e9fe7.png)

screenshot in lootr-1.16.5-0.0.10.34:
![image](https://user-images.githubusercontent.com/3585761/148887316-fe5f2e06-8114-4020-8ec1-1a66d5234565.png)

**Comment by noobanidus** [comment]
I had a note about this but forgot to look into it. Do you happen to have the loot tables in question so I can add them to the defaults?

**Comment by theboo** [comment]
`atum:chests/pharaoh` just blacklisting that loot table ID fixed it for us

**Comment by noobanidus** [comment]
This should hopefully be fixed as of .36 (being built and uploaded now.)

**Comment by theboo** [comment]
Awesome, thanks a bunch!
