### ISSUE TITLE
[1.16.5] Crash on load world

### ISSUE THREAD

**Issue by viminio** [noobanidus/Lootr#81]
[crash-2022-02-13_17.50.18-server.txt](https://github.com/noobanidus/Lootr/files/8056892/crash-2022-02-13_17.50.18-server.txt)
[latest.log](https://github.com/noobanidus/Lootr/files/8056893/latest.log)

Minecraft crash

**Comment by noobanidus** [comment]
Ah. I fixed this in 1.18 but not 1.16. I'll try to get a release out later today.
