### ISSUE TITLE
Feature Request - Add a setting to disable Lootr textures

### ISSUE THREAD

**Issue by lunapanshiel** [noobanidus/Lootr#83]
Exactly as the title says, for immersion purposes in a server I would like an option to make Lootr only use the default/resource pack textures for chests and barrels, the gold and silver bordered chests stand out far too much in many structures, especially ones with the intent to have them hidden. and barrels don't look like barrels in many structures (pirate ship cargo holds, wine cellars, castle pantries, village kitchens and shops, ect.)

While I understand that it's simple to patch a resource pack to do this, I'd much prefer the option to have the Lootr visuals disabled(by making them look like normal chests) so they can use any pack they want without disrupting how the chests are supposed to be seen

**Comment by noobanidus** [comment]
Thinking about it now, this might be something possible. Ideally I'd still like to have a distinct texture for *opened* containers, but I can again make that optional.

**Comment by noobanidus** [comment]
Just a quick update on the progress with this: everything but barrels is working.

![](https://i.imgur.com/bhyMwAT.png)

**Comment by noobanidus** [comment]
So this is released for 1.18.2, just going to test for 1.18 and 1.18.1. I'm afraid that the 1.16.5 version will be a little delayed as I need to synchronize the migration code with the final 1.18 release before.

EDIT: Done for 1.18.0 and 1.18.1.

**Comment by lunapanshiel** [comment]
thanks so much on getting this done so quickly

**Comment by noobanidus** [comment]
This is now available for 1.16.5.
