### ISSUE TITLE
Server crashes and I don't know why

### ISSUE THREAD

**Issue by Krusse53** [noobanidus/Lootr#84]
I have problems with the server thread being held up for up to 60 seconds and then just crashing my server. After I restart the server it runs for a couple of minutes and then just repeats this process. I have a server on pebblehost where I have All the Mods 7 installed. I have contacted support there and they told me that RFTools was the issue however after contacting McJity they told me that the problem laid within the Lootr mod. As of now I have contacted the creator of both Lootr and RFTools and I myself have no clue what is causing this. I was told by the noobanidus to create a post here. Any help received is appreciated.

Versions:
Minecraft: 1.18.1
Forge: 0.192.1.5
McJtyLib: 6.0.9
RFTools: 4.0.5

Lootr: 0.1.14.48

I use the latest version of Optifine if that information is of any use.

Crash log:
[crash-2022-02-20_20.50.49-server.txt](https://github.com/McJtyMods/RFTools/files/8127951/crash-2022-02-20_20.50.49-server.txt)

**Comment by noobanidus** [comment]
Hi there,

I have bounced this back onto McJty, as nothing in the logs really indicate an issue with Lootr. Yes, Lootr does have a mixin that targets the mentioned file, but it doesn't target any of those methods.

My suggestion would be to disable the RFTools builder cards, as those seem to be the ones that are problematic.

**Comment by Krusse53** [comment]
Thanks for the help. I will attempt this as soon as i get home.
