### ISSUE TITLE
[Bug] locks, lootr and mo structures generation weirdness

### ISSUE THREAD

**Issue by Darkmega18** [noobanidus/Lootr#87]
There appears to be an issue with a this and a couple mods. In this case structures from mo structures are generating with the locks being immediately popped off of some chests which generate and get converted to lootr.

![image](https://user-images.githubusercontent.com/8104689/156341910-f93a0f01-c12f-4a7c-bf0b-dac6019c8b0f.png)

![image](https://user-images.githubusercontent.com/8104689/156342025-df4516d5-74a2-4c72-b74a-c1c4e2aa4bdd.png)

Forge: 1.16.5 36.2.28
Lootr: 1.16.5-0.1.11.38.jar
Locks: 1.16.5-3.0.3.jar
Mo structures: forge-1.2.0-1.16.5.jar

and seemingly villages and better dungeons seems to be just fine. and so do dungeons arise from a glance at a couple locations.

**Comment by noobanidus** [comment]
I'm afraid Locks and Lootr aren't compatible as of recent updates.

**Comment by Darkmega18** [comment]
o-oh.... well... thats a top frick. D: and I guess it's not something you can/be willing to work on cause locks is old and kinda semi-abandoned? 
although it's strange that the bug only happened with this specific structures I mentioned and not others?

**Comment by noobanidus** [comment]
I'm assuming it's some sort of race condition. And apologies, I'm not able to take on the Locks mod at this time.
