### ISSUE TITLE
Data Migration - 1.16 and later

### ISSUE THREAD

**Issue by noobanidus** [noobanidus/Lootr#88]
Please be aware that, as of version 0.1.15.49 for Lootr for **1.18 and later**, there has been a significant change in how data is stored. You can read more about this change **and find instructions on reverting in the case of issues** in the [Data Migration - 1.18 and later](https://github.com/noobanidus/Lootr/wiki/Data-Migration---1.18-and-later) page on our GitHub wiki.

If you suffer any issues, such as chests disappearing, or the contents of chests suddenly being reset, please either comment on this issue or file a separate bug report.

--

If you have an issue with updated Lootr for 1.16.5, please update to [`12.42`](https://www.curseforge.com/minecraft/mc-mods/lootr/files/3735664) or later. Specifically, this issue resolves the `FileNotFoundException`: `The process cannot access the file because it is being used by another process`.

**Comment by Darkere** [comment]
No issues for most people who've updated, but we now have a user crashing with this on launch. Even after a PC restart, and after removing the file. 

https://gist.github.com/Darkere/f519d25b2feb416ff4d59f95bf98bc78

**Comment by noobanidus** [comment]
@Darkere I'm honestly not sure what that could be. Do you happen to know what `(Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird)` means?

**Comment by mcarreon** [comment]
@noobanidus Ran into the same crash, the translation should correspond to the message in my crash report 

```
The process cannot access the file because it is being used by another process
```

**Comment by noobanidus** [comment]
@mcarreon Would you be willing to try a few experimental builds to see if I can figure out what's going on here?
