### ISSUE TITLE
Lootr has failed to load correctly

### ISSUE THREAD

**Issue by filipe-silva-27** [noobanidus/Lootr#89]
[crash-2022-03-06_12.14.46-fml.txt](https://github.com/noobanidus/Lootr/files/8192527/crash-2022-03-06_12.14.46-fml.txt)

Hello there,
I have been trying to play curseforge modpack TECC Tinkers Engineer Create Colonies but lootr doesnt load correctly i dont know why.
I tried installing the latest lootr from here: [https://www.curseforge.com/minecraft/mc-mods/lootr](url) but it still doesnt load well. the one I installed was [lootr-1.18-0.1.15.50](https://www.curseforge.com/minecraft/mc-mods/lootr/files/3672675) https://www.curseforge.com/minecraft/mc-mods/lootr/files/3672675
Above is the crash report. What should I do to overcome this issue?

Thanks for the attention

**Comment by noobanidus** [comment]
Without the full `latest.log` I'm not entirely sure what the issue is.

I would hazard a guess that the `lootr-common.toml` file is corrupted in some way.

If you could upload the `latest.log` file and the `lootr-common.toml` file I might be able to tell you more.

**Comment by filipe-silva-27** [comment]
I will attached it now, 1 min.

**Comment by filipe-silva-27** [comment]
[lootrGitHub.zip](https://github.com/noobanidus/Lootr/files/8193609/lootrGitHub.zip)

**Comment by filipe-silva-27** [comment]
Thank you for the quick response, I uploaded a zip file because gitHub said it doesn't support .toml files

**Comment by noobanidus** [comment]
As I suspected, it's actually another mod that's at fault:

```
Caused by: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file tconstruct-client.toml of type CLIENT for modid tconstruct
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:61) ~[fmlcore-1.18.1-39.0.66.jar%2394!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:74) ~[fmlcore-1.18.1-39.0.66.jar%2394!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:64) ~[fmlcore-1.18.1-39.0.66.jar%2394!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
```

There's an issue with the `tconstruct-client.toml` file in the pack, by the look of it.

Due to the way that Forge loads mods, unfortunately the reported error ends up taking place while Lootr is also being loaded.

**Comment by filipe-silva-27** [comment]
Ok, thank you. Should I upload it too? or is it something to do with its creators?

**Comment by noobanidus** [comment]
I would suggest reporting this to the mod-pack author as it's an issue with the configuration file.

In the mean time, you could delete that `client` config file and see if that fixes it.

**Comment by filipe-silva-27** [comment]
Thank you very much again. I read the other issues and in this repository and I have to tell you get well. Get some rest, practice to say no to some work, health is more important.

**Comment by noobanidus** [comment]
> I have to tell you get well. Get some rest, practice to say no to some work, health is more important.

Aw, thank you so much! Thankfully this is an easy thing to work through and I'm having a pretty decent day.

**Comment by filipe-silva-27** [comment]
Great! try not to forget the good moments too :)
