### ISSUE TITLE
No Lootr Chests generating in Dungeons Plus

### ISSUE THREAD

**Issue by froehlichA** [noobanidus/Lootr#9]
Only Vanilla chests, no Lootr chests, generate in structures added by Dungeons Plus.

To reproduce:
- Create a new instance with Minecraft 1.16.4, Forge, [Lootr](https://www.curseforge.com/minecraft/mc-mods/lootr/files/3176706), [Structure Gel API](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api/files/3171697) and [Dungeons Plus](https://www.curseforge.com/minecraft/mc-mods/dungeons-plus/files/3171706)
- Start the game and generate a new minecraft world.
- Locate a structure and & teleport to it, like the tower: `/locate dungeons_plus:tower`
- Confirm that chests inside the structure are vanilla chests instead of Lootr chests.

![2021-01-23_12 29 29](https://user-images.githubusercontent.com/25703146/105577241-990a9b80-5d78-11eb-977b-cdad09e93d22.png)
![2021-01-23_12 37 05](https://user-images.githubusercontent.com/25703146/105577242-9a3bc880-5d78-11eb-970a-5a0f4bd0a13f.png)

Btw, thanks for creating a mod like this :D Have been searching everywhere for a multiplayer-friendly loot mod.

**Comment by noobanidus** [comment]
Thanks, looks like another mod directly accessing the tile. I'll PR compatibility into it.

**Comment by noobanidus** [comment]
Thanks! I've submitted a PR for this: https://gitlab.com/modding-legacy/dungeons-plus/-/merge_requests/3

**Comment by noobanidus** [comment]
I'm going to close this in favor of an issue which lists all the active PRs.
