### ISSUE TITLE
Just a question about "latest" 1.16.5 version

### ISSUE THREAD

**Issue by KarinMiku** [noobanidus/Lootr#91]
is there an issue with lootr-1.16.5-0.1.12.39? i just downloaded the mod a few hours ago and at this time seems like it was removed from curseforge, should i go back to a previous version? im just about to start a new server so i dont mind but was kinda curious about this

**Comment by noobanidus** [comment]
Yes, there was an issue with `12.39` so I had to archive it. I am about to release `12.40` instead.
