### ISSUE TITLE
[1.16.5]Barrels have no texture

### ISSUE THREAD

**Issue by SkullDiamond** [noobanidus/Lootr#92]
Whit the last update (lootr-1.16.5-0.1.12.40.jar) the barrels have missing textures. Whit lootr-1.16.5-0.1.12.39.jar all works fine

![2022-03-27_10 07 28](https://user-images.githubusercontent.com/79324102/160272926-a682816a-2c77-492f-8cbb-87e20e694e55.png)

**Comment by noobanidus** [comment]
Could you upload your `latest.log` to gist for me? It looks like a model isn't loading for some reason, but there's no change between them that I'm aware of.

Are any other blocks failing to load like this?

**Comment by SkullDiamond** [comment]
Didnt saw any other blocks whit missing textures from other mods it only happends whit barrels. Chest and shulkers works fine

[latest (2).zip](https://github.com/noobanidus/Lootr/files/8357433/latest.2.zip)

**Comment by noobanidus** [comment]
```java
[12:58:00] [main/INFO]: Reloading ResourceManager: Blur dummy resource pack, Default, Mod Resources, Better-Leaves-6.0-1.13+§6.zip, Elemental's+Custom+Armor.zip, EmbellishedStone.zip, Infernal Resources.zip, LootrChestRetexture_v1.zip, ...
```

I'm guessing it's this LootrChestRetexture that's responsible. Can you try it without that?

I'm unable to replicate in 1.16.5-0.1.12.40: ![](https://i.imgur.com/dlZKW60.png)

**Please note that if you're wanting to use Vanilla textures, there is now a client-side option configuration for that.**

**Comment by SkullDiamond** [comment]
yeah, I tried without the texture and works fine. Sorry for wasting your time 😥
