### ISSUE TITLE
Server crash when two players open the same container

### ISSUE THREAD

**Issue by Porcy** [noobanidus/Lootr#93]
As title says. Playing on E2E 1.1.2. If another player opens the same lootr container at the same time as me, the server crashes
[crash-2022-04-04_15.37.52-server.txt](https://github.com/noobanidus/Lootr/files/8412677/crash-2022-04-04_15.37.52-server.txt)
.

**Comment by noobanidus** [comment]
Hey! Hopefully `12.41` should fix this problem for you!
