### ISSUE TITLE
Immersive Engineering issues

### ISSUE THREAD

**Issue by freopt** [noobanidus/Lootr#94]
When Lootr and IE are installed, no loot spawns in the crates in IE village houses. Tested with just Lootr, IE and JEI, 1.18.2.

**Comment by noobanidus** [comment]
Thanks for the replication instructions. I'm currently working on the Fabric port of Lootr. Do you happen to have the `latest.log` file? If not, I can set about replicating it later today.

**Comment by freopt** [comment]
[latest.log](https://github.com/noobanidus/Lootr/files/8508995/latest.log)
Also it works fine if you set the crates as lootr chests in the config but not if you don't

**Comment by noobanidus** [comment]
Ah, that's strange. I might need to make that a default config.

**Comment by noobanidus** [comment]
So, by the look of it, there's no default config to support IE crates as chests. I'll need to check the tagging to determine why it's suddenly not supported -- unless it was only ever supported when placed in the config... but if that's the case, then no loot spawning in them is undesirable.

**Comment by Dreadp1r4te** [comment]
Is there a way to get this working temporarily until a public fix can be released? Some aspects of IE are intended to be found rather than crafted, like shaders and some blueprints. It would be preferable if IE's crates were not converted to Lootr crates, since the crate itself has value.

**Comment by noobanidus** [comment]
> Is there a way to get this working temporarily until a public fix can be released? Some aspects of IE are intended to be found rather than crafted, like shaders and some blueprints. It would be preferable if IE's crates were not converted to Lootr crates, since the crate itself has value.

Add the registry name of the block to the additional_chests configuration option.

**Comment by jerry1333** [comment]
FYI so You don't have to look for it like I did 😉 
`additional_chests = ["immersiveengineering:crate"]`
