### ISSUE TITLE
[Fabric] [1.18.2] Custom Chest invisible

### ISSUE THREAD

**Issue by pewblaze** [noobanidus/Lootr#96]
Hi the custom chests are invisible. The texture is missing ^^"

![2022-04-24_22 38 12](https://user-images.githubusercontent.com/96242065/165042695-6e1b3ceb-3a42-454b-b9fd-d570e7abb571.png)

**Comment by noobanidus** [comment]
Can you upload your log file? And what mod are you using for shaders? Do you have any performance mods that could be impeding things?

EDIT: And can you replicate it without shaders?

**Comment by pewblaze** [comment]
Sure here you go:
https://gist.github.com/pewblaze/6dc3b53342e4b6158a7d120132a9b468

Im using Iris & Complementary Shaders.
I disabled the shader same effect.
I disabled/deleted all my resource packs, same effect.
![2022-04-25_11 44 30](https://user-images.githubusercontent.com/96242065/165064476-fb7d1bce-a777-488e-837e-adda63b7bc0d.png)

Its also invis in REI
![2022-04-25_11 45 26](https://user-images.githubusercontent.com/96242065/165064452-130a4411-3e06-4181-a5cf-9c205e93aa94.png)

Yeah ive got Sodium etc. 
Ill try without my client side mods

**Comment by pewblaze** [comment]
Okay it works without my client side mods. Not sure which one causes it though. any ideas ^^"?

**Comment by pewblaze** [comment]
Doesnt work either :( 
My log without my client side mods
https://gist.github.com/pewblaze/f7c0919aa3f194a31f8c7dff49219cff

**Comment by noobanidus** [comment]
Oh, you meant the custom inventory? My apologies, I thought you meant chests in general weren't functioning properly. I'll look into this, I may have missed something during the porting.

EDIT: I forgot the translation was "Lootr Chest" instead of "Lootr Inventory". And I realise now you said custom chest in your title, I just misunderstood and thought you meant that *all* custom chest textures weren't displaying.

**Comment by noobanidus** [comment]
Okay, it looks like I forgot to register the renderer for the custom inventory. I've reinstated it, testing now, and I'll deploy an update presently.

**Comment by noobanidus** [comment]
This should be fixed in [0.3.18.54](https://www.curseforge.com/minecraft/mc-mods/lootr-fabric/files/3768266), which will hopefully be approved on CurseForge shortly.

**Comment by pewblaze** [comment]
Ah i see! Thanks a lot :D
