### ISSUE TITLE
Could not save data

### ISSUE THREAD

**Issue by crayzym0nkey** [noobanidus/Lootr#97]
###  **Server thread/ERROR Could not save data noobanidus.mods.lootr.data.AdvancementData@110dcb6e
27.04 23:07:00 [Server] INFO java.io.FileNotFoundException: ./HOBOCRAFT/data/lootr/Lootr-AdvancementData.dat (No such file or directory)**
27.04 23:07:00 [Server] INFO at java.io.FileOutputStream.open0(Native Method) ~[?:?]
27.04 23:07:00 [Server] INFO at java.io.FileOutputStream.open(FileOutputStream.java:293) ~[?:?]
27.04 23:07:00 [Server] INFO at java.io.FileOutputStream.<init>(FileOutputStream.java:235) ~[?:?]
27.04 23:07:00 [Server] INFO at java.io.FileOutputStream.<init>(FileOutputStream.java:184) ~[?:?]
27.04 23:07:00 [Server] INFO at net.minecraft.nbt.NbtIo.m_128944_(NbtIo.java:64) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.world.level.saveddata.SavedData.m_77757_(SavedData.java:40) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.world.level.storage.DimensionDataStorage.m_164865_(DimensionDataStorage.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
27.04 23:07:00 [Server] INFO at net.minecraft.world.level.storage.DimensionDataStorage.m_78151_(DimensionDataStorage.java:159) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.level.ServerLevel.m_8806_(ServerLevel.java:714) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.level.ServerLevel.m_8643_(ServerLevel.java:693) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:536) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.MinecraftServer.m_195514_(MinecraftServer.java:561) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:834) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
27.04 23:07:00 [Server] Server thread/ERROR Could not save data noobanidus.mods.lootr.data.AdvancementData@43491c51
27.04 23:07:00 [Server] INFO java.io.FileNotFoundException: ./HOBOCRAFT/data/lootr/Lootr-ScoreData.dat (No such file or directory)
27.04 23:07:00 [Server] INFO at java.io.FileOutputStream.open0(Native Method) ~[?:?]
27.04 23:07:00 [Server] INFO at java.io.FileOutputStream.open(FileOutputStream.java:293) ~[?:?]
27.04 23:07:00 [Server] INFO at java.io.FileOutputStream.<init>(FileOutputStream.java:235) ~[?:?]
27.04 23:07:00 [Server] INFO at java.io.FileOutputStream.<init>(FileOutputStream.java:184) ~[?:?]
27.04 23:07:00 [Server] INFO at net.minecraft.nbt.NbtIo.m_128944_(NbtIo.java:64) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.world.level.saveddata.SavedData.m_77757_(SavedData.java:40) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.world.level.storage.DimensionDataStorage.m_164865_(DimensionDataStorage.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
27.04 23:07:00 [Server] INFO at net.minecraft.world.level.storage.DimensionDataStorage.m_78151_(DimensionDataStorage.java:159) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.level.ServerLevel.m_8806_(ServerLevel.java:714) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.level.ServerLevel.m_8643_(ServerLevel.java:693) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:536) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.MinecraftServer.m_195514_(MinecraftServer.java:561) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:834) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23227!/:?]
27.04 23:07:00 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
27.04 23:22:48 [Server] Server thread/WARN Can't keep up! Is the server overloaded? Running 4403ms or 88 ticks behind

**Comment by noobanidus** [comment]
~~What version of Lootr & Minecraft is this?~~

Looks to be 1.18.2, I'll triple-check because I was quite sure I'd released a version that had already fixed this. I may have failed to properly release it, my bad.

**Comment by crayzym0nkey** [comment]
It's mc 1.18.1
The lootr version is 1.18-0.1.15.50

**Comment by noobanidus** [comment]
Yep, my bad.

I bumped the version and everything but never actually released it -- or perhaps the build failed for some reason and I didn't notice.

Releasing Lootr-1.18.2-0.2.16.51 now, and I'll make sure everything is backported to Lootr-1.18.0-1.15.51 and release that shortly.

**Temporary workaround**: Go into your server's `data` folder and create a `lootr` folder. This should prevent that crash from occurring.

**Comment by crayzym0nkey** [comment]
thank you for such a quick response.
